### ISSUE TITLE
Revert changes

### ISSUE THREAD

**Issue by Irbidan** [hellzerg/optimizer#1]
Add an option to restore or revert all/specific changes done because sometimes you change options unintentionally. Also could be great create a restore point.

Greets

**Comment by hellzerg** [comment]
ON/OFF switches for every option is in the to-do list. It will just take time..

**Comment by hellzerg** [comment]
ON/OFF toggles have finally been implemented in v3.7!
Try them out. There will probably be some bug hunting soon...
