### ISSUE TITLE
How to move config folder from C:\ProgramData into subfolder of installation dir?

### ISSUE THREAD

**Issue by pstein** [hellzerg/optimizer#100]
Well, Optimizer is not really portable.
It creates a config folder C:\ProgramData\Optimizer

How can I tell Optimizer to create this folder as a subfolder of the installation dir D:\tools\Optimizer\ instead?

**Comment by hellzerg** [comment]
The purpose of Optimizer is to keep the current config state per computer. 

It's portable in the sense that it doesn't need to install it anywhere. 

But, the Optimizer folder in ProgramData is necessary to keep the current state of each Windows installation per machine.

**Comment by pstein** [comment]
> But, the Optimizer folder in ProgramData is necessary to keep the current state of each Windows installation per machine.

This can be done with a subdirectory in installation folder as well.
Let the user decide what he wants to do and offer at least an option

**Comment by hellzerg** [comment]
Why bother? This folder is only 60kb maximum.
Also, what's the point of running the app on a computer, loading the state of another one?
