### ISSUE TITLE
Optimizer 12.0 doesnt work with win7 x64

### ISSUE THREAD

**Issue by Felipefpl** [hellzerg/optimizer#102]
Right at startup it says the program stopped working. Attached the log below.

[Optimizer.zip](https://github.com/hellzerg/optimizer/files/8200717/Optimizer.zip)

**Comment by hellzerg** [comment]
I'm a little busy for the next 3 weeks, I will fix it after that period.

**Comment by hellzerg** [comment]
Did you try deleting Optimizer folder in C:\ProgramData and relaunching the app?

**Comment by Felipefpl** [comment]
> Did you try deleting Optimizer folder in C:\ProgramData and relaunching the app?

Nope, that didnt come to mind before.

Strange, i downloaded again 12.0 to test it and now it works, i wonder if it got something to do with the new win7 build i downloaded, maybe it is so.

Thank you very much for this tool, for all your work with it and for your help with my problem, it's really nice, specially the links to download software, although it would be nice to have options to disable ALL apps from windows 10 plus ALL useless services, just a hint. ;)
