### ISSUE TITLE
Apps that can't be installed.

### ISSUE THREAD

**Issue by RG2N** [hellzerg/optimizer#106]
• Notepad++:
Link is no longer valid
-- https://notepad-plus-plus.org/downloads/v8.3.2/

• .NET Framework 4.7.2:
Link is no longer valid
-- https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472

**Comment by SniperWasTaken** [comment]
Did you try reinstalling it?

**Comment by RG2N** [comment]
Those issues above are what is wrong with it. They just need to fix the links

**Comment by hellzerg** [comment]
Guys I'll fix them later on weekend.
