### ISSUE TITLE
Issue detected by Defender Antivirus

### ISSUE THREAD

**Issue by Ziocash** [hellzerg/optimizer#11]
Trojan:Win32/Occamy.B
Detected by Microsoft Defender Antivirus

**Comment by hellzerg** [comment]
It's a false positive obviously.

**Comment by Ziocash** [comment]
Of course.
I suppose it's an issue related to "Disable Windows Defender" and the related code.

**Comment by hellzerg** [comment]
It could be related to registry tweaks or hosts file patching.
