### ISSUE TITLE
Seperate Hardware-Accelerated GPU Scheduling from DisabledXboxLive

### ISSUE THREAD

**Issue by DavisMcKenzie** [hellzerg/optimizer#111]
My recommendation is that seperate HAGS option from DisabledXboxLive 

"Registry.SetValue(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers", "HwSchMode", "00000002", RegistryValueKind.DWord);"

to its own category and prefer its own switch toggle since it doesnt related to Xbox Live at all, and i does affect some performance when resizeable bar is on and also when using Nvidia Broadcast which Im suggesting it to be seperate option.

![2022-03-15 22_32_27-Settings](https://user-images.githubusercontent.com/82803124/158402169-4606a4b4-ac75-48e3-94c1-51f68b3f9250.png)

**Comment by hellzerg** [comment]
Okay, will do a seperate toggle in the next version.

**Comment by DavisMcKenzie** [comment]
Nice! looking forward to it
