### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by S4moo0** [hellzerg/optimizer#112]
Wifi stopped working and pc start lagging and its slow now. It destroyed my pc i cant run anything....

**Comment by Jisll** [comment]
You need to activate the right settings, and dont turn off onedrive if your pc is cloud storaged.

**Comment by S4moo0** [comment]
I just turned on performance tweaks. Now i cant run the program to disable it

**Comment by Jisll** [comment]
Why you cant run the program?

**Comment by hellzerg** [comment]
Delete the Optimizer folder in C:\ProgramData.

**Comment by Jisll** [comment]
I have been working on a new version, the only thing missing is to check if everything is correct and can be published, then just try again! But if you have started Optimizer and used it, there should be a folder called (Optimizer) in Program Data on the C: drive, must turn on hidden elements.
