### ISSUE TITLE
im a bit retarded

### ISSUE THREAD

**Issue by BomOnTop** [hellzerg/optimizer#116]
i accidentally uninstalled one of the xbox thingies or whatever and ive tried reinstalling what i think it was but my xbox login is still fucked up, how do i fix it lmao

**Comment by SniperWasTaken** [comment]
Let me guess, gaming services? or game bars?

**Comment by BomOnTop** [comment]
probs both lmao, fosure gamebar but i reinstalled it and shits still not letting me login

**Comment by BomOnTop** [comment]
fixed it by resetting pc but keeping personal files and then updating shit
