### ISSUE TITLE
Romanian Translation 

### ISSUE THREAD

**Issue by okspy47** [hellzerg/optimizer#118]
Hi! I saw your app from a famous tech YouTube channel from România, and as a native Romanian speaker, I'm really interested to contribute to this project with a Romanian translation.

If you want to colaborare, or find more about me, feel free to ask!

**Comment by hellzerg** [comment]
I'll contact you soon, in the weekend.

**Comment by hellzerg** [comment]
@okspy47 
You should translate this file into Romanian.
[EN.json.txt](https://github.com/hellzerg/optimizer/files/8354872/EN.json.txt)

**Comment by okspy47** [comment]
Okey, I will do it.

**Comment by Jisll** [comment]
Any Update? Please respond.

**Comment by BeamingNG** [comment]
> 

Hey I am also a Romainian! I saw that he did not respond so I will try to translate the file. By today even if I can.

**Comment by Jisll** [comment]
> > 
> 
> Hey I am also a Romainian! I saw that he did not respond so I will try to translate the file. By today even if I can.

Hey, yea you can translate it!

**Comment by BeamingNG** [comment]
I will have it done by either tommarow or the day after, some things are a little confusing to translate.

**Comment by hellzerg** [comment]
Make sure you translate the latest EN.json in master branch.

**Comment by BeamingNG** [comment]
I will be done with it by either today or tommarow,

**Comment by BeamingNG** [comment]
> Make sure you translate the latest EN.json in master branch.

Sorry I don't understand this is how I am doing it--

[RO.json.txt](https://github.com/hellzerg/optimizer/files/8699146/RO.json.txt)

**Comment by hellzerg** [comment]
https://raw.githubusercontent.com/hellzerg/optimizer/master/Optimizer/Resources/i18n/EN.json

There is the latest one

**Comment by hellzerg** [comment]
@BeamingNG Will you complete the romanian translation or should I close the issue?

**Comment by BeamingNG** [comment]
Sorry I got caught up with unexpected work and I could not find the time to do it, and I forgot about it. Give me a timeframe for when the .json RO file should be submitted. As soon as possible I know but if I submit it by friday is it ok? Also do I have the latest .json file?

**Comment by hellzerg** [comment]
@BeamingNG 

The latest file is always reflected on this link:

https://raw.githubusercontent.com/hellzerg/optimizer/master/Optimizer/Resources/i18n/EN.json

So, use the above link to translate into Romanian.

Yes it's ok to be ready by Friday.

**Comment by BeamingNG** [comment]
Ok thank you and sorry again, i know that my actions do not reflect on the community.

**Comment by hellzerg** [comment]
@BeamingNG don't worry, you are okay

**Comment by BeamingNG** [comment]
In the .json file is btnkill meaning like kill a specific function? what context does this apply in?

**Comment by hellzerg** [comment]
Kill process

**Comment by BeamingNG** [comment]
Cool got it.

**Comment by BeamingNG** [comment]
I will release the .json file by tonight.

**Comment by BeamingNG** [comment]
I completed the translation to Romainian, and again sorry that I forgot about it for a couple weeks.
[RO.zip](https://github.com/hellzerg/optimizer/files/8875468/RO.zip)
For what ever reason I cannot submit a .json file here so I compressed the .json file to turn it into a zip file.

**Comment by hellzerg** [comment]
Good, will add it in the next update. Thanks for translating.

**Comment by BeamingNG** [comment]
Your very welcome
