### ISSUE TITLE
Issue detected by defender

### ISSUE THREAD

**Issue by unc134r** [hellzerg/optimizer#12]
Trojan:Win32/CryptInject!ml

seems like defender has to go

**Comment by truefriend-cz** [comment]
I have this problem too...
Versions 5.3 and 5.4 detected as virus.

**Comment by hellzerg** [comment]
Can you exclude it from Defender?

**Comment by unc134r** [comment]
Yup, that's what I'm doing now. Why is it getting triggered though?

**Comment by hellzerg** [comment]
Because it does hosts patching to block ads, I guess..

**Comment by truefriend-cz** [comment]
Same problem on McAfee Antivirus. Not running but block after downloading and moving to Quarantene.
