### ISSUE TITLE
Little typo on Italian translation.

### ISSUE THREAD

**Issue by Dydnt** [hellzerg/optimizer#120]
**Hello!** New user of the app.

I just want to report that the Italian translation of _Optimizer_ has a little typo: in the upper bar of the program, the Italian translation for architecture is missing a letter.

The current translation in the program is _Archiettura_, but the correct translation is _Architettura_.

An image is attached to prove that the correction is correct and valid, just in case.
![image](https://user-images.githubusercontent.com/94496939/159778060-5f56ab15-0650-4bad-b83d-eb1e32570cf5.png)

**Comment by hellzerg** [comment]
Will be fixed soon.
