### ISSUE TITLE
crashing but not going into not responding

### ISSUE THREAD

**Issue by jinja365** [hellzerg/optimizer#123]
so first i tried to toggle 'enhance privacy' and then it just freezed( didnt go into not responding mode though) and then i had to close it, end the background process via task manager, and run it again. but then when i ran it again i was able to toggle the module, but then  i turned on 'disable insider' and it did the same thing, and i had to close and reopen again, and then i was able to toggled the insider module
so it crashes after 1 module is toggled or something?

**Comment by hellzerg** [comment]
Please send me the Optimizer.log in C:\ProgramData\Optimizer

**Comment by Jisll** [comment]
Hello again, if you want us to help you further, you have to answer. We need the log from the optimizer, please send it to us.

**Comment by jinja365** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/8399335/Optimizer.log)
Sorry for the delay, was in school and didnt turn on my pc

**Comment by hellzerg** [comment]
Windows 10 or 11??

**Comment by jinja365** [comment]
@VinSheen you sure?

**Comment by VinSheen** [comment]
> @VinSheen you sure?

@jinja365 better try it for yourself though. That's all I did to fix the crashing issue.

**Comment by jinja365** [comment]
@VinSheen and has it been fixed for you?

**Comment by hellzerg** [comment]
Can you look the event viewer application log to see if there are any Optimizer errors?

**Comment by VinSheen** [comment]
@jinja365 YES, IT DID FIXED THE ISSUE ON CRASHING AND APP NOT RESPONDING OR SUDDEN CLOSING OF THE APP. JUST FOLLOW MY INSTRUCTIONS ABOVE.

**Comment by jinja365** [comment]
@hellzerg my issue has been fixed by reinstalling(i have no idea how), and i have no idea why @VinSheen is so mad
