### ISSUE TITLE
About Taiwan Province

### ISSUE THREAD

**Issue by btwise** [hellzerg/optimizer#124]
Taiwan province is a part of China, its language is called  Chinese Traditional, should identify China-Taiwan, should not use a separate flags, please fix!

**Comment by hellzerg** [comment]
Shouldn't be a different flag, so it can be apparent that it's another language?

**Comment by btwise** [comment]
> Shouldn't be a different flag, so it can be apparent that it's another language?

The national flag represents a country. Traditional Chinese is just a variant of Chinese. Please use the national flag of China

**Comment by hellzerg** [comment]
Ok, next version will have the Chinese flag instead of the Taiwanese one.

**Comment by Mchar7** [comment]
@hellzerg Traditional Chinese writing is used almost exclusively in Taiwan (and Hong Kong, though decreasingly so) so I think it would be best to keep the Taiwanese flag as a clear identifier. Taiwan has its own identity so I don't see why we need to willingly suppress it.

The translation was done by @H3XDaemon so if they want to choose, that would be best.

**Comment by hellzerg** [comment]
@Mchar7 Used to have Taiwanese flag but a user requested to change it to Chinese one.

**Comment by btwise** [comment]
> @hellzerg Traditional Chinese writing is used almost exclusively in Taiwan (and Hong Kong, though decreasingly so) so I think it would be best to keep the Taiwanese flag as a clear identifier. Taiwan has its own identity so I don't see why we need to willingly suppress it.
> 
> The translation was done by @H3XDaemon so if they want to choose, that would be best.

Taiwan is not a country, it belongs to China, there is only one China in the world, so the old  sky-sun flag should not be used
