### ISSUE TITLE
Missing Italian translation in the app.

### ISSUE THREAD

**Issue by Dydnt** [hellzerg/optimizer#126]
**Hello again!**

I want to report that there is a missing translation from English to Italian in _Optimizer_, for the option to disable network throttling.

Here's the translation, if you guys want to add it: Windows implementa un meccanismo di rallentamento della rete che limiterà il traffico di rete durante l'esecuzione di app multimediali. Può anche ridurre le prestazioni di rete mentre si gioca online.
![Desktop Screenshot 2022 03 27 - 12 24 55 40](https://user-images.githubusercontent.com/94496939/160277286-eb487b78-a43a-4af1-8983-985484ab094d.png)

**Comment by hellzerg** [comment]
Okay, will do it. Thanks for the contribution.
