### ISSUE TITLE
Bug that doesn't show the full phrase in a specific description.

### ISSUE THREAD

**Issue by Dydnt** [hellzerg/optimizer#127]
**Hello, thanks for adding the translation in today's update!**

I installed the update and noted that the phrase for the new translation may look arranged differently, in comparison of the other descriptions. Also, this leads to the last word to be not fully showing.

Sorry for this another issue report, hope I'm not disturbing you guys.
![Desktop Screenshot 2022 03 27 - 16 03 40 27](https://user-images.githubusercontent.com/94496939/160285426-b4d2d04e-eb45-476e-b24e-e231f278ee70.png)

**Comment by hellzerg** [comment]
Ok, will be fixed next update. Don't worry.
