### ISSUE TITLE
Uninstalls UWP packages that I didn't select

### ISSUE THREAD

**Issue by oGrqpez** [hellzerg/optimizer#129]
I tried to uninstall two specific apps from UWP; I checkbox them and then click uninstall, it verifies if I want to do it, and it shows the ones I selected; I proceed. It turns out it didn't uninstall those; instead, it uninstalls something else, and I'm scared of what it did. Am I the only one?

**Comment by oGrqpez** [comment]
That's the thing, I don't know what it uninstalled. I tried to uninstall Microsoft one note and skype from the list.

**Comment by oGrqpez** [comment]
[errors.txt](https://github.com/hellzerg/optimizer/files/8362250/errors.txt)

**Comment by hellzerg** [comment]
It didn't uninstall anything. OneNote and Skype have been removed?

**Comment by oGrqpez** [comment]
They have? Becuase it sitll shows in the optimizer list, even when I refresh

**Comment by hellzerg** [comment]
Search them in start menu and see. The optimizer list might show them but they are removed.

**Comment by oGrqpez** [comment]
https://user-images.githubusercontent.com/76074246/160392847-923856a7-0758-4008-afd9-64850a741d31.mp4

**Comment by oGrqpez** [comment]
Ok, I just tried it on skype. It turns out it worked just visually; it didn't change. I think we can call this solved with a new bug?

**Comment by hellzerg** [comment]
It's a known visual bug, but don't worry, the app gets uninstalled.
