### ISSUE TITLE
The little "arrow" pointing upwards on the taskbar which contained the system tray icons disappeared.

### ISSUE THREAD

**Issue by DRaKuLa89** [hellzerg/optimizer#133]
I don't know what tweak/option did this, But how do I get it back?
![image](https://user-images.githubusercontent.com/73628498/160592578-73daf431-85d7-4b6a-a5b3-75d2ced22485.png)

**Comment by hellzerg** [comment]
![image](https://user-images.githubusercontent.com/3146835/160593009-5815c64f-7fa5-450e-aae3-e5357ddf5380.png)

**Comment by DRaKuLa89** [comment]
Alright, thanks!
