### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by spXel** [hellzerg/optimizer#136]
First of all congratulations and thank you for this amazing software you created, it helped me a lot!
My sugestions are:
-a button to create the "ultimate performance" power plan
-enable windows dark theme
-disable mouse pointer enhancement
-in system advanced properties disable visual efects for max performance
-have like a "gaming mode "that turn on game mode" disable xbox game bar and recording"

Maybe i'm crazy but this are some sugestions that maybe are just placebo but idk

**Comment by hellzerg** [comment]
Thanks for using and enjoying my app!
Well:

- A button for an "ultimate" or "gaming" power plan/mode is not a good idea, as you can achieve the same, combining the respective options.
- Windows dark theme is very easy to enable, so I don't know if that would be very useful
- I will think about Mouse Pointer precision, though

**Comment by spXel** [comment]
the power plan that i was talking about is the energy scheme sorry! 
powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
yeah like i said, maybe a bit placebo but is just some ideas :P

**Comment by Jisll** [comment]
Hello, I've looked through everything and came to the conclusion that you do not need the power plan! If we're honest, these power saving plans are of almost no use, except for a few features like CPU speed to keep the highest speed... It never did anything for me, but thanks for your suggestions, we are grateful when we receive some features all the time! So if you have something different, feel free to send it to us!

**Comment by spXel** [comment]
As a gamer i always look for the maximum performance + minimum input lag for that "competitive advantage"
so i changed some things that i search and found.
- Disable keyboard filter keys
- keyboard advanced settings put the repeat rate on fast
- on windows advanced settings put it on performance -> https://www.google.com/search?q=windows+system+properties+advanced+performance&rlz=1C1CHZL_pt-PTPT697PT699&source=lnms&tbm=isch&sa=X&ved=2ahUKEwib68ev4u32AhW7gP0HHTpvAKgQ_AUoAXoECAEQAw&biw=1360&bih=625&dpr=1#imgrc=PsXyPPikSaV8-M
i don't remember more :/

**Comment by spXel** [comment]
> Hello, I've looked through everything and came to the conclusion that you do not need the power plan! If we're honest, these power saving plans are of almost no use, except for a few features like CPU speed to keep the highest speed... It never did anything for me, but thanks for your suggestions, we are grateful when we receive some features all the time! So if you have something different, feel free to send it to us!

As a gamer i always look for the maximum performance + minimum input lag for that "competitive advantage"
so i changed some things that i search and found.

Disable keyboard filter keys
keyboard advanced settings put the repeat rate on fast
on windows advanced settings put it on performance -> https://www.google.com/search?q=windows+system+properties+advanced+performance&rlz=1C1CHZL_pt-PTPT697PT699&source=lnms&tbm=isch&sa=X&ved=2ahUKEwib68ev4u32AhW7gP0HHTpvAKgQ_AUoAXoECAEQAw&biw=1360&bih=625&dpr=1#imgrc=PsXyPPikSaV8-M
i don't remember more :/

**Comment by DavisMcKenzie** [comment]
I Second the Gaming mode should be turned on as it reduce ram usage for other apps during gaming, and yep its not related to Game Bar at all.

 internal static void DisableGameBar() { Registry.SetValue(@"HKEY_CURRENT_USER\Software\Microsoft\GameBar", "AutoGameModeEnabled", "1", RegistryValueKind.DWord);

**Comment by hellzerg** [comment]
Okay, will be a separate toggle in nexf update.
