### ISSUE TITLE
My Antivirus (Kaspersky) detects the last UPDATE (12.4) as being a VIRUS!!

### ISSUE THREAD

**Issue by IBeniaminI** [hellzerg/optimizer#137]
![screen1](https://user-images.githubusercontent.com/102603092/160628069-8ebd5ce1-ad24-40a2-a4ae-158c461c6f49.PNG)

**Comment by Jisll** [comment]
False Positive, is open source and secure.

**Comment by hellzerg** [comment]
The app is 100% open source and clean. False positive.

**Comment by IBeniaminI** [comment]
> 

Yeah 😁, I just wanted you guys to know!!
