### ISSUE TITLE
Optimizer V12.4 is didnt opening.

### ISSUE THREAD

**Issue by karincaDev** [hellzerg/optimizer#138]
I want to open the program but always stucks in loading screen like this: Loading Hardware Specifiations, I waited for 10-15 minutes but always stuck, restarted the program too.

**Comment by hellzerg** [comment]
Can you please send me the Optimizer.log file in C:\ProgramData\Optimizer?

**Comment by karincaDev** [comment]
> Can you please send me the Optimizer.log file in C:\ProgramData\Optimizer?
[Optimizer.log](https://github.com/hellzerg/optimizer/files/8381936/Optimizer.log)

**Comment by Jisll** [comment]
Can you try to delete the folder "Optimizer" in C:\ProgramData\Optimizer? And maybe this will solve the problem, if not answer here!

**Comment by hellzerg** [comment]
I think the problem is that the hardware cannot be detected successfully.
Try running the .exe with `/disable=indicium` parameter.

**Comment by karincaDev** [comment]
Its worked thanks.


30 Mar 2022 Çar 21:52 tarihinde deadmoon ***@***.***> şunu
yazdı:
