### ISSUE TITLE
Feat. req. Don`t clutter Programdata, use tmp folders if needed

### ISSUE THREAD

**Issue by necros2k7** [hellzerg/optimizer#14]
subj

**Comment by hellzerg** [comment]
It's using only 48KB of files. Why do you think it's cluttering?

**Comment by necros2k7** [comment]
cause it keeps those files after closing

**Comment by hellzerg** [comment]
They are various .reg and .bat scripts that do some job. It's better to have them on disk rather than deleting them, because every time you run the app. it will write/delete them over and over. I had to avoid unnecessary disk activity.
