### ISSUE TITLE
When i scanned it in virus total, it detected Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by Jatin-Y** [hellzerg/optimizer#144]
Any idea about this, or is this a false alarm. Please tell the truth, I don't want my pc getting infected.

**Comment by hellzerg** [comment]
Don't worry it's not a virus. The app is 100% clean and open-source.

**Comment by BlueDrakoPT** [comment]
latest build flagged by Kaspersky as UDS.Dangerous.Object.Multi.Generic. Impossible to use.

**Comment by hellzerg** [comment]
It's 100% safe.

**Comment by DaSandman** [comment]
@BlueDrakoPT, at this point I trust Hellzerg 100% more than I trust Kaspersky....

**Comment by Jisll** [comment]
> latest build flagged by Kaspersky as UDS.Dangerous.Object.Multi.Generic. Impossible to use.

I already strongly watch out for viruses, and Kaspersky I can recommend very little... I also actively use Optimizer to clean my PC or change things in Windows 11 that helps me. So you can look through the source code here with pleasure, here will not happen except you activate Toggles... Otherwise the software will not do anything with your computer.

**Comment by BlueDrakoPT** [comment]
Ok, I admit it's clean, but why Kaspersky triggers 12.5 version and not old ones???

**Comment by Jisll** [comment]
> Ok, I admit it's clean, but why Kaspersky triggers 12.5 version and not old ones???

I dont know, i can figure it out, but i do this later.. But its for sure 100% false positiv.

**Comment by hellzerg** [comment]
@BlueDrakoPT Heuristic behavior analysis and predictive analysis, which means Kaspersky tries to predict why an executable is virus, without having a real piece of proof.

Every false positive's real cause is this mechanim.

**Comment by BlueDrakoPT** [comment]
Version 12.6 not triggered by Kaspersky. Thanks for the update. When my subscription of Kaspersky ends, I go to Norton or BitDefender... ;-)
