### ISSUE TITLE
Please add Indonesian language

### ISSUE THREAD

**Issue by Bintangp02** [hellzerg/optimizer#146]
Tolong tambahkan bahasa indonesia
Please add Indonesian language

**Comment by hellzerg** [comment]
[EN-prototype.txt](https://github.com/hellzerg/optimizer/files/8404080/EN-prototype.txt)

You should translate this file into your preferred language.

**Comment by Mameng57** [comment]
> [EN-prototype.txt](https://github.com/hellzerg/optimizer/files/8404080/EN-prototype.txt)
> 
> You should translate this file into your preferred language.

how can i help? should i make a PR with the json file?

**Comment by hellzerg** [comment]
You can upload it here.

**Comment by hellzerg** [comment]
Anyone willing to do the Indonesian translation? Or should I close the issue?

**Comment by Jisll** [comment]
I think you can close this now.
