### ISSUE TITLE
[BUG] Error translation

### ISSUE THREAD

**Issue by PoloNX** [hellzerg/optimizer#147]
**Describe the bug**
When I select the french language I have some text in spanish

**To Reproduce**
1. Launch the .exe
2. Select French
3. Go in "Universel"

**Expected behavior**
The text have to be in french

**Screenshots**
![Capture d’écran 2022-04-03 110000](https://user-images.githubusercontent.com/57038157/161420088-f1ed77a6-c46c-40ec-a31f-c65588869b7f.png)

**Desktop:**
 - OS: Windows 10 Pro N
 - Version 21H1

**Comment by hellzerg** [comment]
Missing translation texts. Can you translate them ?

**Comment by PoloNX** [comment]
Disabilita la telemetria di Visual Studio -> Désactiver la télémétrie de Visual Studio
Disabilita la telemetria di Visual Studio -> Désactiver la télémétrie de Visual Studio

**Comment by PoloNX** [comment]
Disabilita la telemetria di Visual Studio -> Désactiver la télémétrie de Visual Studio
Disabilita la telemetria di Firefox -> Désactiver la télémétrie de Firefox
Disabilita la telemetria di Chrome -> Désactiver la télémétrie de Chrome
