### ISSUE TITLE
add Arabic language

### ISSUE THREAD

**Issue by MesterPerfect** [hellzerg/optimizer#149]
hi
I translated optimizer into Arabic 
[AR.json.txt](https://github.com/hellzerg/optimizer/files/8405132/AR.json.txt)
I am looking forward to using the tool in Arabic 
thanks

**Comment by hellzerg** [comment]
Tell me which flag you want for Arabic.
Also, tell me the official word for Arabic in Arabic.

**Comment by MesterPerfect** [comment]
@hellzerg
Egypt flag 
the official word for Arabic is: العربية

**Comment by hellzerg** [comment]
Done. Update to v12.7
