### ISSUE TITLE
reactivate the system tray box

### ISSUE THREAD

**Issue by nxyoo** [hellzerg/optimizer#151]
hey, anyone know how to reactivate it? i donno how to do :/

**Comment by nxyoo** [comment]
and i watched everywhere on the app

**Comment by hellzerg** [comment]
Right click on taskbar and go to taskbar properties.
There you go, there is the setting you are looking for.

**Comment by nxyoo** [comment]
is it normal it's like that ? even in the settings i don't find :/
![image](https://user-images.githubusercontent.com/59174414/161819004-c2c7d9b8-3960-40e6-b573-36ae4f042092.png)
![image](https://user-images.githubusercontent.com/59174414/161819010-8e4ff70e-7ea3-4b40-9a3d-3f7c478df7d0.png)

**Comment by hellzerg** [comment]
Select which icons to show on taskbar option.
Look carefully

**Comment by nxyoo** [comment]
![image](https://user-images.githubusercontent.com/59174414/161819958-ec18bf0d-3bbc-4775-be8f-df031e189ab2.png)
![image](https://user-images.githubusercontent.com/59174414/161819971-fadfd7e8-1beb-4002-85e5-f45837f4f046.png)
all icons are activated and i don't find settings for the system tray

**Comment by hellzerg** [comment]
https://github.com/hellzerg/optimizer/issues/133

**Comment by nxyoo** [comment]
oh yeah i just have to disable the option to see all icons in the taskbar, thanks men appreciate it :)
