### ISSUE TITLE
I accidentally uninstalled something.

### ISSUE THREAD

**Issue by CxnnorUS** [hellzerg/optimizer#154]
I accidentally uninstalled a windows app that allowed me to sign into Microsoft. I don't know what it was or even if it was caused by this, but I'm assuming so as I've tried everything to fix it. I was wondering if there was a way to rollback an app like this?

**Comment by hellzerg** [comment]
You mean you uninstalled an UWP app?

**Comment by CxnnorUS** [comment]
I think so.

**Comment by CxnnorUS** [comment]
Everytime I try to sign in to Microsoft, it reloads three times and closes.

**Comment by CxnnorUS** [comment]
Unfortunately, I had to resolve the issue by factory resetting which deleted my apps, but not my files. There was probably another way of fixing this issue, but this was my last resort after trying practically everything.
