### ISSUE TITLE
Windows fingerprint stopped working

### ISSUE THREAD

**Issue by rexsopro** [hellzerg/optimizer#157]
After i used this optimizer somehow my fingerprint stopped working but i don't know what caused it. Can someone help? I also had a restore point but somehow it got deleted after i accidentally pressed disable system recovery so i can't restore it

**Comment by hellzerg** [comment]
Reset Sensor Services. It may work.

**Comment by rexsopro** [comment]
> Reset Sensor Services. It may work.

I tried it just now and it didn't work

**Comment by hellzerg** [comment]
Reset Enhance Privacy option.

**Comment by Zabooby** [comment]
Can confirm the Enhance Privacy option causes this issue. Is there a particular reason it is disabled?
