### ISSUE TITLE
Documents keep gettng deleted and unable to open Pictures

### ISSUE THREAD

**Issue by Rishtarded** [hellzerg/optimizer#163]
Help my Documents folder keep getting deleted everytime I restart my laptop

**Comment by Qauvet** [comment]
I meant by the files in the Documents folder keep getting deleted.

**Comment by hellzerg** [comment]
Do you have OneDrive sync account?

**Comment by Qauvet** [comment]
> Do you have OneDrive sync account?

Nope, I think I fucked up. I thought it'd keep my folders without a onedrive account. I uninstalled it due to lack of my device better perfomance.

**Comment by hellzerg** [comment]
So what's the cause of the problem?

**Comment by Qauvet** [comment]
Probably after I checked "Uninstall OnerDrive".

**Comment by hellzerg** [comment]
Why does everyone do this..?
