### ISSUE TITLE
Icons started to "jump" on taskbar

### ISSUE THREAD

**Issue by fire7d** [hellzerg/optimizer#169]
I used this program (I checked almost all switch-buttons) and program icons started to "jump" on taskbar (not notification area). The icons act like program got restarted and the icon got re-arranged. For addition, sometimes focus just flick to other app (and back or stay).

**Comment by hellzerg** [comment]
Windows 11?

**Comment by fire7d** [comment]
Nope, Win10 1903

**Comment by hellzerg** [comment]
Did you restart your computer?
Also, tell me which options have you enabled?

**Comment by fire7d** [comment]
Is there any config file? I dont want to run it again.

**Comment by hellzerg** [comment]
This behavior started after some Windows update or immediately after using the app? Because, 25th April is many days.

**Comment by fire7d** [comment]
I dont use Windows Update to be honest (I use it once per year / half the year). Last time I used Windows Update was 18.04, but this weird behaviour (movement on taskbar) right after using the app.

**Comment by hellzerg** [comment]
Okay, just open it and revert everything back, restart and see the result.

**Comment by fire7d** [comment]
Okay, I did revert everything back. I will give info in, I dont know, 12 hours.

**Comment by hellzerg** [comment]
Waiting.

**Comment by fire7d** [comment]
Seems to be fixed, thanks.

**Comment by hellzerg** [comment]
> Seems to be fixed, thanks.

Okay, but we didn't find the culprit.
