### ISSUE TITLE
Need help fast pls!

### ISSUE THREAD

**Issue by spXel** [hellzerg/optimizer#170]
When i apply the privacy improvement my desktop folders are gone, where are they? can i get them back?

**Comment by hellzerg** [comment]
You mean Enhance Privacy?

**Comment by spXel** [comment]
yes

**Comment by hellzerg** [comment]
Did you enabled the Uninstall OneDrive option?

**Comment by spXel** [comment]
i did

**Comment by spXel** [comment]
i had some folder in my desktop with some documents and they are all gone

**Comment by spXel** [comment]
![image](https://user-images.githubusercontent.com/102599825/166447213-205b0cf0-52ff-4b87-a183-e6e014b1352a.png)

**Comment by hellzerg** [comment]
You read the warning when you clicked Uninstall OneDrive, right?

**Comment by spXel** [comment]
i did it in version .7
damn

**Comment by hellzerg** [comment]
You have Microsoft-sync account setup on Windows?

**Comment by spXel** [comment]
i don't damn.
In this case, wich folders are safe so i can performe the unninstall and still keep my items?=

**Comment by hellzerg** [comment]
Uninstall OneDrive option is a hard one. 
Disable System Restore option can delete your current backups if enabled.
Print Service is required for printer functionality
Sensor Services are required if you have a tablet or a touch screen/rotating device.
Windows Ink provides support for inking/pen devices.

All the other options are safe.

**Comment by spXel** [comment]
nono, i mean, when i unninstall is there anywhere i can put my folders to dont get deleted?

**Comment by hellzerg** [comment]
You mean when you uninstall OneDrive?

**Comment by spXel** [comment]
Yes exacly

**Comment by hellzerg** [comment]
You need to move your files from your User account folder (C:\Users\<USERNAME>).
The best is to uninstall OneDrive on a fresh Windows installation, without using a Microsoft-sync account.
