### ISSUE TITLE
I Delete Microsoft Store

### ISSUE THREAD

**Issue by InvalidAccount69** [hellzerg/optimizer#171]
Hi.
I Remove Microsoft Store idk why
how to restore it

**Comment by hellzerg** [comment]
https://www.winhelponline.com/blog/restore-windows-store-windows-10-uninstall-with-powershell/

**Comment by InvalidAccount69** [comment]
And for xbox app?

**Comment by InvalidAccount69** [comment]
sorry
and i remove groovy app i dont know how restore it

**Comment by giffur** [comment]
xbox: https://frameboxxindore.com/windows/how-do-i-reinstall-the-xbox-app-on-windows-10.html
not sure about the groovy app

if @hellzerg sees this, mind adding [qview](https://interversehq.com/qview/) to installable programs under video&sound ? thanks :)

**Comment by hellzerg** [comment]
> sorry and i remove groovy app i dont know how restore it

You can install Groove music app from Microsoft store.

**Comment by hellzerg** [comment]
@giffur qView added in apps feed.
