### ISSUE TITLE
How to remove what I enabled?

### ISSUE THREAD

**Issue by YesPaul** [hellzerg/optimizer#173]
My VPN does not work anymore and I think it is because of Optimizer: how do i remove it ?

**Comment by hellzerg** [comment]
Revert everything back and see if it's working.
But I need more details for helping you.

**Comment by YesPaul** [comment]
How do i revert everything back ?
What details do oyu need ?

**Comment by hellzerg** [comment]
Switch off every toggle you enabled and restart your PC.

**Comment by hellzerg** [comment]
Can you send me the Optimizer.log file located in C:\ProgramData\Optimizer?

**Comment by YesPaul** [comment]
uhm its going to sound dumb but I deleted it(the whole folder), I thought it was going to revert it...

**Comment by hellzerg** [comment]
That's why the toggles have reverted back.
That folder was like a "save state" folder, with error logs.
You should not delete it again.

**Comment by YesPaul** [comment]
No cuz I deleted it like 10minutes ago, but it was already turned off before that

**Comment by hellzerg** [comment]
But I need that log file to see the errors.

**Comment by YesPaul** [comment]
Yeah I know I shouldn't have done that but thats not why my options were already turned off

**Comment by hellzerg** [comment]
It might be a permission problem.

**Comment by hellzerg** [comment]
You fixed your VPN?
