### ISSUE TITLE
Add Brave Browser

### ISSUE THREAD

**Issue by InvalidAccount69** [hellzerg/optimizer#176]
Title

**Comment by hellzerg** [comment]
You can download Brave Browser in Apps tab.

**Comment by InvalidAccount69** [comment]
Um? Add In Cleaner

**Comment by hellzerg** [comment]
Ok, will do tomorrow.

**Comment by InvalidAccount69** [comment]
kk

**Comment by hellzerg** [comment]
Test this build and see if it's all working good with Brave cleaner.

[Optimizer-TestBraveClean.zip](https://github.com/hellzerg/optimizer/files/8646399/Optimizer-TestBraveClean.zip)
