### ISSUE TITLE
It's A trojan??

### ISSUE THREAD

**Issue by Sag5206** [hellzerg/optimizer#177]
Because I check exe file in virus total it is saying it's a trojan
**JUST WHY**

**Comment by hellzerg** [comment]
False positive. Only one engine detects it as malicious.

**Comment by hellzerg** [comment]
Complete source code is open in this repo for almost 7 years.

**Comment by Sag5206** [comment]
It means Nothing happened on my computer???

**Comment by Jisll** [comment]
> It means Nothing happened on my computer???

Yeah, nothing will happend if you open the file.
