### ISSUE TITLE
Benchmark before/after

### ISSUE THREAD

**Issue by SkyEmie** [hellzerg/optimizer#18]
Hi,
Could we have a benchmark before and after ur optimisation script? because I highly doubt it...
"Speed up your system and network performance" yeah. I'm not so sure :s

**Comment by hellzerg** [comment]
Well, it's doing some well-known modifications to the Windows registry.
The performance change is not so noticeable if you have an SSD and a really fast modern PC.
But on older machines the change is more welcome.
