### ISSUE TITLE
Unable to open optimizer 12.7 or any new versions 

### ISSUE THREAD

**Issue by huzefas80** [hellzerg/optimizer#181]
Unable to open optimizer 12.7 or any new versions

**Comment by huzefas80** [comment]
I am on windows 11 and before it used to open but after the latest windows update it stopped working

**Comment by huzefas80** [comment]
Pls help

**Comment by hellzerg** [comment]
Can you send me the log file in C:\ProgramData\Optimizer?

**Comment by huzefas80** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/8688378/Optimizer.log)

**Comment by huzefas80** [comment]
@hellzerg

**Comment by hellzerg** [comment]
Did you try deleting Optimizer folder in ProgramData and running app again?

**Comment by huzefas80** [comment]
no i didnt try that

**Comment by huzefas80** [comment]
should i try?

**Comment by hellzerg** [comment]
Yes

**Comment by huzefas80** [comment]
still not working

**Comment by Jisll** [comment]
Hello, you can try to set the SysMain service in Services to Automatic, or turn it on for now. (if it is off.)

**Comment by hellzerg** [comment]
Try downloading new version v13.4.
