### ISSUE TITLE
Why I am getting this after using the app??? and how to fix it??

### ISSUE THREAD

**Issue by fisforfaheem** [hellzerg/optimizer#184]
![image](https://user-images.githubusercontent.com/35878088/169404115-7549c3ca-8f2d-4521-a62a-23ed7278d80b.png)

**Comment by hellzerg** [comment]
Turn off Disable Cloud Clipboard switch

**Comment by fisforfaheem** [comment]
it not work... i am so tired i tried resetting all setting from app as well

**Comment by hellzerg** [comment]
You want to re-enable clipboard history, right?

**Comment by hellzerg** [comment]
No, your pc is running fine, you can ignore these messages.

If you want to remove them, you should find the following keys and delete them:

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System, "AllowClipboardHistory"
            HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System, "AllowCrossDeviceClipboard"
            HKEY_CURRENT_USER\Software\Microsoft\Clipboard, "EnableClipboardHistory"
            HKEY_LOCAL_MACHINE\Software\Microsoft\Clipboard "EnableClipboardHistory"

**Comment by fisforfaheem** [comment]
Thank you! will do it, will it disable clipboard? or enable cloud
clipboard??

also see it's here too
[image: image.png]

**Comment by hellzerg** [comment]
Will enable it

**Comment by fisforfaheem** [comment]
Ok, thanks.
