### ISSUE TITLE
[FEATURE REQUEST] Would it be possible to add a 

### ISSUE THREAD

**Issue by tcortega** [hellzerg/optimizer#186]
It would be nice to have a way to actually PERSISTENTLY set the keyboard layouts and languages. Something that doesn't get affected in every windows restart. Only people that actually changes their layout, in my case because I have a 60% keyboard, now what a pain it is to deal with this in windows.

For instance, look at this bullshit:
![image](https://user-images.githubusercontent.com/60912483/169849755-55f19182-3d94-4c88-942c-9cb531415620.png)
Here we have only the US keyboard selected.

But at my available layouts:
![image](https://user-images.githubusercontent.com/60912483/169849843-1a2e19c1-3881-4db4-9691-bfa0811c6a7b.png)

So, idk what may be feasible here, but it'd be a nice addition.

**Comment by hellzerg** [comment]
Hmm... I didn't fully understand what you are trying to say. Could you explain more?

**Comment by tcortega** [comment]
> Hmm... I didn't fully understand what you are trying to say. Could you explain more?

Windows has a feature where it allows you to have multiple keyboard layouts selected. You can switch between layouts using CTRL + SHIFT or WIN + SPACE.

The problem is, the behavior that keyboard layouts have, is really limited and it is really buggy. My layout literally changes every restart, or randomly changes after I lock and unlock my computer. Something that also happens frequently, is that it shows layouts that I don't have selected. An example of this is the image above.

I had selected only the US QWERTY layout, but in the image below it, it shows that I have 3 different layouts selected.

It'd be a nice feature in your software if we could find a way to "fix" that. To only select what we actually want, to be able to change the order of the layouts, and to set it so it doesn't get reseted every restart.

**Comment by hellzerg** [comment]
I think that could be done using windows Settings

**Comment by hellzerg** [comment]
So, you want to make a layout as the preferred option permanently?
