### ISSUE TITLE
Enabling "Enhance Privacy" disables creating a fingerprint for log in.

### ISSUE THREAD

**Issue by BeamingNG** [hellzerg/optimizer#188]
From my understanding using biometric devices to log in to, uses windows hello which probably uses some kind of telemetry on it's own. Giving users the option to enable specific privacy options instead of just one button would allow for a balance of convenience and privacy.

**Comment by hellzerg** [comment]
Yeah, will try to implement something like this when I have spare time

**Comment by hellzerg** [comment]
You can just enable Biometrics service from services.msc and have them both on.

**Comment by BeamingNG** [comment]
Ok I will try that, I feel like an idiot for not thinking about seeing if the biometric service is on.

**Comment by BeamingNG** [comment]
Ok that did not work, it was already on and had automatic startup.

**Comment by BeamingNG** [comment]
Basically, the "Enhance privacy feature" disables biometrics completely. What I would do is keep the toggle that would enable all the privacy features, but also add a sub menu that would enable specific privacy features. No new features have to be added, only enable specific functions independently from each other, instead of one button enabling all of them. What do you think?

**Comment by hellzerg** [comment]
Did you try updating to v13.6 anf turn off the option?

**Comment by BeamingNG** [comment]
Yeah, I did and creating a fingerprint does work if you turn off "enhance privacy" but why not branch down the function to allow the fingerprint reader to work while having other privacy options enabled like disabling diagnostics from being sent to microsoft.

**Comment by hellzerg** [comment]
Can you check if Biometrics service is enabled in services.msc?

**Comment by BeamingNG** [comment]
Yes it is enabled.

**Comment by hellzerg** [comment]
So, how did you enable fingerprint functionality ?

**Comment by BeamingNG** [comment]
By disabling "Enhance privacy"
