### ISSUE TITLE
More performance options?

### ISSUE THREAD

**Issue by VanHoevenTR** [hellzerg/optimizer#190]
Is there more ways to improve performance for Windows 11 as much as possible? even I have applied some optimizer options and followed videos on youtube, the system sometimes still randomly lagging and reduced responsibility especially the UI and mouse cursor even less CPU and GPU usage, and the system making "dut dut dut dut" sounds when the lags is extreme. 

I don't think it's my hardware issue because it's also happen on Windows 10 on other hardware. I clean installed Windows like 3 months ago. I tried to keep my system clean as possible, and use portable apps and store most files on other drives to keep C drive clean

**Comment by hellzerg** [comment]
Maybe some driver issue or incompatibility?
It's weird that you have done a clean install with original Windows and still lagging.

**Comment by hellzerg** [comment]
Do you have the latest drivers from your official manufacturer's site?
