### ISSUE TITLE
A Bit of Trouble to Windows Insiders

### ISSUE THREAD

**Issue by Williamtung1** [hellzerg/optimizer#192]
First of all, I would like to say it is really a nice app to optimize Windows, my fans do keep quieter after using this. I sincerely appreciate all of the contributors' efforts. However, as a Windows Insider, I think some diagnostic data is blocked by the app even though I haven't choose about blocking diagnostic data at all. As the result, I cannot update my system. 
[edit]: After a while, I figured out that the option "Enhance Privacy" will disable some diagnostic data sending

**Comment by hellzerg** [comment]
Yes, Enhance Privacy option is pretty aggresive. But you can skip it, and you are good.
