### ISSUE TITLE
Scaling on 4k-Ultrawide Screens

### ISSUE THREAD

**Issue by itsweekly** [hellzerg/optimizer#193]
Yes, I know I can just change the resolution but this is still a bug that many people are probably experiencing. 

If you could fix the scaling for larger displays such as 3840x1600, 2560x1600 ultrawides that would be great.
![IMG_4669](https://user-images.githubusercontent.com/92674764/174471535-a62cdaa7-ff2a-4143-813d-d44e0174ba13.jpeg)
![IMG_4670](https://user-images.githubusercontent.com/92674764/174471538-2c5fb765-3c53-4dc2-b1b8-af0b4ef9034c.jpeg)

**Comment by hellzerg** [comment]
Oh, that is really bad. It needs some testing, I'll do it when I find spare time.

**Comment by BeamingNG** [comment]
I have been having this issue with my 19:10 display as well.

**Comment by hellzerg** [comment]
Previous versions have the same problem as well?

**Comment by BeamingNG** [comment]
Yeah

**Comment by hellzerg** [comment]
Only tab titles and apps list have the scaling problem?

**Comment by itsweekly** [comment]
No, also the whole section where you can install apps

**Comment by hellzerg** [comment]
So, only these 2 sections

**Comment by itsweekly** [comment]
Yep, only those too. IMO the easiest way to fix it is to fix the offsets and scaling.

**Comment by hellzerg** [comment]
Yes I know. Because they are custom controls.

**Comment by itsweekly** [comment]
Any progress?

**Comment by hellzerg** [comment]
I am busy this period, so I don't have time to experiment with the app. Please be patient.

**Comment by itsweekly** [comment]
No, also the whole section where you can install apps.

**Comment by hellzerg** [comment]
@itsweekly Apps section is fixed

**Comment by itsweekly** [comment]
> @itsweekly Apps section is fixed

dam man props to you you actually fixed it
