### ISSUE TITLE
Performance tweaks issue

### ISSUE THREAD

**Issue by taylostolo** [hellzerg/optimizer#195]
I am a computer tech and I use your program as a last step clean up and speed up on computers that come in and I don't know if its windows or your program but it SRTtrail BSOD's every computer use the performance tweaks button on and have to use a restore point to recover the system all using the newest version of windows 10 21H2

**Comment by hellzerg** [comment]
Maybe a driver issue? If you disable Performance Tweaks, problem is solved?
