### ISSUE TITLE
Win10, my laptop lanuches 3-5min after using this

### ISSUE THREAD

**Issue by arthures11** [hellzerg/optimizer#197]
So, after i disabled many unused stuff, windows update, windows defender etc. etc.
my laptop began to launch really really long time, instead of few seconds(i do have SSD) it is launching few minutes….
win10 1909 version 

unfortunately i can’t tell which option caused it because it happend few updates back and i already updated the optimizer, currently even if i disable ALL the options the slow launch is still happening..

**Comment by arthures11** [comment]
PS. i also used the optimizer to disable/remove some startup apps or services i guess(i don’t remember which one was actually doable in the program)

**Comment by arthures11** [comment]
PS2. Logs from ProgramData\Optimizer 
https://easyupload.io/49hqiv

**Comment by hellzerg** [comment]
Are you sure it's Optimizer's fault?

**Comment by arthures11** [comment]
Maybe its some UWP or Service Startup that i disabled/removed using Optimizer but yes, it started to happen instantly after i used Optimizer and restarted the pc for the first time.

Furthermore, apps like Malwarebytes BEFORE werent usually running on windows Startup (just sometimes- after a crash/bsod etc. i assume windows have "2 ways" of starting or something?) but since i used Optimizer, it is running on windows Startup always. Maybe this information can help to get into the source of a problem.

**Comment by hellzerg** [comment]
Optimizer cannot make apps run at Startup or something.

**Comment by arthures11** [comment]
> Optimizer cannot make apps run at Startup or something.

yeah but as i said it did happen before but just rarely, now it happens always, so nothing really changed if it comes to Starup apps.
Does windows sometimes run differently in cases of a normal restart or crash/bluescreen?
Like comparing normal run after Restart or run after a crash or blue screen etc. In my case the Startup apps in those two different cases would be different(or rather in the second case additinonal apps would run).

**Comment by hellzerg** [comment]
If you remove the apps in startup the problem is solved?

**Comment by arthures11** [comment]
> If you remove the apps in startup the problem is solved?

No, i tried before and just now i tried to remove everything but it still boots very long time around 3+ min.
The Task Manager "Startup" tab says BIOS only needed 9sec to run, so i really don't understand which would be the issue.

**Comment by hellzerg** [comment]
Which screen does it have the longest time? Blackscreen, Windows is loading, logo spinner?

**Comment by arthures11** [comment]
> Which screen does it have the longest time? Blackscreen, Windows is loading, logo spinner?

MSI Logo spinner, and after the logo there is blackscreen which is also long(before "Welcome" spinner shows up). Once i can see the "Welcome" it does run smoothly and fast as supposed.

**Comment by hellzerg** [comment]
So the longest time is when MSI logo spins?

**Comment by arthures11** [comment]
> So the longest time is when MSI logo spins?

yeah its now clearly like this, i recorded a short video so you can see: 
https://youtu.be/PYbpvPuz-zk

**Comment by hellzerg** [comment]
That's strange. Did you update WIndows before happening?

**Comment by arthures11** [comment]
> That's strange. Did you update WIndows before happening?

no, i wasnt updating windows for around 2 years

**Comment by hellzerg** [comment]
Wait, are you saying that you have unpatched Windows 10 build for 2 years long, without formatting to cleanup the PC?

**Comment by arthures11** [comment]
> Wait, are you saying that you have unpatched Windows 10 build for 2 years long, without formatting to cleanup the PC?

i am not sure what that means. I installed win10 around 2019 and the last updates around 2020(so i have ver1909 compilation 1863.1440) but since then i didn't really want to do any updates from windows update, is it wrong? Around start of 2022 i used optimizer to disable windows update especially because it was automatically downloading updates and was annoying.

**Comment by Jisll** [comment]
Hello, I have read through everything and it could be that it is a registry key.

Try to disable the ULPS (Ultra Low Power State).
You go into the regedit with Windows + R and search for it.
You have to set all ULPS to 0 except PP_ULPSDelay.

If there are no keys, then disconnect all drivers and restart your pc, if it is still not gone check your pc, the system (Windows 10) settings or CPU or RAM. 

I would because you have not yet made any new updates also install all updates times or simply reinstall the operating system completely (clean install).

**Comment by arthures11** [comment]
> Hello, I have read through everything and it could be that it is a registry key.
> 
> Try to disable the ULPS (Ultra Low Power State). You go into the regedit with Windows + R and search for it. You have to set all ULPS to 0 except PP_ULPSDelay.
> 
> If there are no keys, then disconnect all drivers and restart your pc, if it is still not gone check your pc, the system (Windows 10) settings or CPU or RAM.
> 
> I would because you have not yet made any new updates also install all updates times or simply reinstall the operating system completely (clean install).

Isn't that some AMD stuff? I am using Nvidia and Intel on my laptop(i7-9750h, geforce 1660ti+uhd graphics 630)

**Comment by Jisll** [comment]
> 

Oh well then you can remove this step already ^^
Just try the others, you can also disable the quick start so that it shuts down completely and then restarts.

**Comment by Jisll** [comment]
But I think it's because of the Windows updates, they fix most things like that ^^

**Comment by arthures11** [comment]
Windows updates did not help, sadly i assume the only working fix for me currently would be clean windows :( i am trying to avoid that really hard because i don't want to move important files to another drive etc.

**Comment by hellzerg** [comment]
Yeah, a clean install with newer build will be the best solution.

**Comment by arthures11** [comment]
> Yeah, a clean install with newer build will be the best solution.

so i did clean reinstall and everything works as supposed now, laptop launches within few seconds
