### ISSUE TITLE
Adding Silent Install to Apps 

### ISSUE THREAD

**Issue by Jisll** [hellzerg/optimizer#198]
I have listened to some feedback from the app, also from computer scientists, many said it would be very cool if the apps can still be installed with Silent Install, then the tab "Apps" would be perfect.

**Comment by hellzerg** [comment]
Yes, but that is kinda impossible. Many different install wizards and setups.

**Comment by itsweekly** [comment]
Many apps have the commands written in the installer, or inside the actual app. Most apps just have to be mentioned like this "app.exe /Q" or "app.exe -silent" - "app.exe /silent"
