### ISSUE TITLE
It would not launch after shuting down my pc.

### ISSUE THREAD

**Issue by imranoni** [hellzerg/optimizer#199]
hi, i downloaded the exe putted all of my settings that I want then after a while i shuted down my pc. Next day I wanned to launch the exe opimizer but it wouldnt launch, i run it as administartor and then nothing happends idk whats the problem i also used 13.5 and 13.6 version and delleted it and downloaded it again but when i run it it wouldnt launch. I really need a fix or explanation. Thank you

**Comment by hellzerg** [comment]
I need the optimizer.log file located in C:\ProgramData\Optimizer

**Comment by imranoni** [comment]
I deleted the optimizer folder in program app launched the optimizer and it sudenly launched corectly but if new issues appear il let u know. Thank you

**Comment by imranoni** [comment]
its maybe beacuse i already have some of its options disabled in regedit if u want my regedit customatization reply also i deleted the optimizator download folder from desktop

**Comment by hellzerg** [comment]
Yes, I know the problem. I will hotfix it in next version.
