### ISSUE TITLE
Peoples selling your software.

### ISSUE THREAD

**Issue by muratcansimsek** [hellzerg/optimizer#203]
In this video, people are wondering about the fps increase software that is sold for money and they buy it, after making a purchase in the video, another user connects to the computer and presents your program as his own. Peoples pay high money for your software.

https://www.youtube.com/watch?v=Vyp3_ixCw1k
The address of the site that sells your software to people for money : https://quartiy.org/

**Comment by Rooki2** [comment]
https://www.youtube.com/watch?v=367nxxL0_V4 same here sadly

I would prefer to copyright strike them

**Comment by hellzerg** [comment]
What can be done about that..?

**Comment by danielytuk** [comment]
> What can be done about that..?

You could submit a takedown request on those videos, and potentially remove the results from Google:
https://support.google.com/legal/troubleshooter/1114905#ts%3D1115658,1115673

> In this video, people are wondering about the fps increase software that is sold for money and they buy it, after making a purchase in the video, another user connects to the computer and presents your program as his own. Peoples pay high money for your software.
> 
> https://www.youtube.com/watch?v=Vyp3_ixCw1k The address of the site that sells your software to people for money : https://quartiy.org/

And also send an email to GoDaddy (their registrar); stating they're selling free software:
abuse@godaddy.com

Best wishes,
Daniel

**Comment by hellzerg** [comment]
Thanks for guiding me. I will try to stop them.

**Comment by Quartiy** [comment]
Hello, we used your software before in the application given on the link, but we were offering it to our customers for free, after this forum post was opened, we have completely removed it from our file content, we wish you a good day.
