### ISSUE TITLE
How to disable Windows Defender? 

### ISSUE THREAD

**Issue by Fused990** [hellzerg/optimizer#205]
How do you execute optimizer with the /restart=disabledefender command thing?

**Comment by PhoenixCODE2322** [comment]
For me i did this ..

Open cmd in the directory where optimizer.exe is present . To do this first go to that directory in file explorer then go in address bar and replace everything int that with  this without quote "cmd" press enter .. cmd will open 

Now , type optimizer.exe /restart=disabledefender

**Comment by PhoenixCODE2322** [comment]
@Fused990 also .. your device will restart two times so do not interrupt .. first it will restart in safe mode then it will restart in normal mode

**Comment by PhoenixCODE2322** [comment]
@Fused990 also .. your device will restart two times so do not interrupt .. first it will restart in safe mode then it will restart in normal mode

**Comment by PhoenixCODE2322** [comment]
@Fused990 also .. your device will restart two times so do not interrupt .. first it will restart in safe mode then it will restart in normal mode

**Comment by hellzerg** [comment]
@Fused990 exactly what @PhoenixCODE2322 typed.
Did you do it?

**Comment by Fused990** [comment]
@hellzerg I did do it, it worked.
