### ISSUE TITLE
Can't login to my microsoft account

### ISSUE THREAD

**Issue by JaviruloNT** [hellzerg/optimizer#207]
So, this started happening when I installed Optimizer. I can't login to my Microsoft account in some of their apps, like Xbox or Minecraft. The login pop-up will crash and won't let me log in.

I uplodaded a quick video with 2 examples & my Optimizer settings.

https://youtu.be/qq3CANx137c

**Comment by hellzerg** [comment]
Reset Xbox Live and Gamebar options, then restart and try again.

**Comment by JaviruloNT** [comment]
Disabling Xbox Live was causing the problem, now it works. Thank you.

**Comment by hellzerg** [comment]
Xbox Live services are tied to Xbox logins, so yeah.
