### ISSUE TITLE
Can't get windows hello to work

### ISSUE THREAD

**Issue by n0aaz** [hellzerg/optimizer#208]
Hi, as said since i have been using the optimizer, I have been unable to use Windows Hello facial recognition.
I've seen that #188 mentions disabling "enhance privacy" So I did exactly that. 
Also I have checked that the biometry service is on in services.msc but the issue remains : 

I can see the IR camera blink & recognize my face when i want to log in & it even gives me the "welcome [Name]" prompt but the computer doesn't unlock until i put on my passcode.

Any guidance?

**Comment by hellzerg** [comment]
Disable Sensor services are on or off?

**Comment by n0aaz** [comment]
> Disable Sensor services are on or off?

It was off but I found how to solve my problem : I just had to disable everything optimizer related first , reboot , then "improve hello recognition" and once it was done I could reenable anything in optimizer as long as I don't touch "enhance privacy" or "disable sensor services".

Maybe it doesn't revert back by itself when it's toggled off.

**Comment by hellzerg** [comment]
Okay, will fix it in next version.
