### ISSUE TITLE
Virus Detected!

### ISSUE THREAD

**Issue by Savit3r** [hellzerg/optimizer#209]
I ran a test on "VirusTotal" and the result indicated a virus... is it actually containing a **_Trojan Malware_**?

![image](https://user-images.githubusercontent.com/61334606/181774824-bf4fe344-8fe1-44e2-acb1-a6acc7cdbf37.png)

**Comment by Savit3r** [comment]
> No, it's clean. Just make sure you download the software from Github always.

Sure do, thx.

Also, I tried to enable the “classic right click” on windows 11; not sure what it is supposed to do. I can only think of it as it’s a feature to show the entire right-click pane like windows 10... if that’s so, it’s not working on my windows 11 :(

**Comment by hellzerg** [comment]
Did you try restarting?

**Comment by NotPhantomX** [comment]
if the right click menu isn't working then it could be because the explorer didn't restart so you can restart the computer or open task manager and find windows explorer and then press restart.

**Comment by Savit3r** [comment]
Issued Solved ✅
Thanks.
