### ISSUE TITLE
I can't open the .exe file

### ISSUE THREAD

**Issue by DukviL** [hellzerg/optimizer#21]
I downloaded the file and when I wanted to open the .exe, it doesn't work. I was thinking there's a problem with the file and I downloaded it again, but it isn't opening, what can I do? I even run it as administrator.

**Comment by hellzerg** [comment]
Maybe your antivirus blocked it? A crash? Something

**Comment by DukviL** [comment]
i think it was the antivirus, i wasn't thinking about that, thank you

**Comment by DukviL** [comment]
It isn't working, Idk what to do, bc I turned off my antivirus, but it's the same problem, that I can't open the .exe file.

**Comment by hellzerg** [comment]
Any error messages?

**Comment by tarekifla** [comment]
Same issue here, I can't open the .exe file

**Comment by hellzerg** [comment]
You have WIndows 7? There is a known crashing issue on Windows 7, I am currently working on it

**Comment by hellzerg** [comment]
Try the new update 4.6. It should work properly.

**Comment by ismatt3w** [comment]
Not even when deactivating the antivirus does it open the optimizer, and I have windows 10 just in case, the only version after 11.3 opens for me
