### ISSUE TITLE
64-bit download not working

### ISSUE THREAD

**Issue by flezus** [hellzerg/optimizer#211]
Is there any reason for this to happen? I've been using Optimizer for a long time, but every time I go to download programs, the 64-bit file never downloads.

• Discord:
No download available for 64-bit, downloading 32-bit

• Steam:
No download available for 64-bit, downloading 32-bit

• Spotify:
No download available for 64-bit, downloading 32-bit

**Comment by hellzerg** [comment]
there is no 64bit exe for these apps.
simple.

**Comment by flezus** [comment]
lol I didn't know, thanks for the explanation, I thought they all had it and for some reason the Optimizer was buggy.

**Comment by flezus** [comment]
lol I didn't know, thanks for the explanation, I thought they all had it and for some reason the Optimizer was buggy.
