### ISSUE TITLE
Disabling the DPS service breaks per app network monitoring in task manager

### ISSUE THREAD

**Issue by MrBridgeSix** [hellzerg/optimizer#212]
Disabling the DPS service is part of what the "Disable Telemetry Services" setting does, but it will also break per app network monitoring in task manager, I'm not sure if it's know or not but it took me a while to diagnose when I noticed it.

Windows 11 22621.317

**Comment by hellzerg** [comment]
Well, nice of you to notice this.
Will remove the DPS disable tweak in next version.

**Comment by MaximeMichaud** [comment]
Hi, I took me time too.
Network in Task Manager is no longer working properly, I don't know how I will fix it.

**Comment by hellzerg** [comment]
DPS service is not gonna be disabled from v13.7 and onwards.
