### ISSUE TITLE
Icon & launch option for UWP Uninstallation.

### ISSUE THREAD

**Issue by PhoenixCODE2322** [hellzerg/optimizer#213]
Currently it only shows package name and many of them are hard to recognize which app they are related too. An icon and also an option to launch those app would be a good start to make it easier for verification if thats the app user wants to unistall.

**Comment by hellzerg** [comment]
Icons for each UWP app added in v13.8.

**Comment by PhoenixCODE2322** [comment]
Thank You

**Comment by hellzerg** [comment]
Launching an UWP is complicated, I might add it later.

**Comment by PhoenixCODE2322** [comment]
> Launching an UWP is complicated, I might add it later.

its fine , just wanted a way to confirm what application was . now that icon is added it will be easy.
