### ISSUE TITLE
After optimization battery usage shows nothing

### ISSUE THREAD

**Issue by InterestingDarkness** [hellzerg/optimizer#214]
![image](https://user-images.githubusercontent.com/109194923/183955566-3f3403a4-dfec-4f14-843b-645f45f45443.png)
![image](https://user-images.githubusercontent.com/109194923/183956041-6b7db9c4-4212-45c1-8dd3-3637479302d5.png)

**Comment by InterestingDarkness** [comment]
After re-enabling the Diagnostic System Host it resumed working

**Comment by hellzerg** [comment]
Okay, I get it.

**Comment by hellzerg** [comment]
Service will no longer be stopped from v13.8.
