### ISSUE TITLE
ESET Reports: BAT/KillAV.NFF trojan

### ISSUE THREAD

**Issue by bhenstra** [hellzerg/optimizer#215]
Time;Scanner;Object type;Object;Detection;Action;User;Information;Hash;First seen here
10/08/2022 20:57:24;HTTP filter;file;https://codeload.github.com/hellzerg/optimizer/zip/refs/heads/master;BAT/KillAV.NFF trojan;connection terminated;VM-WS1234\LocalAdmin;Event occurred during an attempt to access the web by the application: C:\Program Files\Google\Chrome\Application\chrome.exe (8FBCC2973DA7EA0E109D8BA3F3119C994738E6B7).;84D446E3EDBF40C113ED3FEC82DE0FB0DBFCFB32;

**Comment by hellzerg** [comment]
Did you download the app from Github official repo?

Also, did you try to disable Chrome telemetry?
