### ISSUE TITLE
"Uninstalling onedrive" deleted everything on my desktop 

### ISSUE THREAD

**Issue by aozorabsl** [hellzerg/optimizer#219]
It seems for some reasons the default path of desktop on my win11 is under onedrive. It is not even normally visible as it only says \Desktop when you open the desktop directory. Just one click and I lost several hundred GB of data, and now I'm finding ways to recover it, though I'm not counting on my luck. At the end of the day maybe I'm too reckless. But it seems like a good idea to warn people of this potential issue.

**Comment by hellzerg** [comment]
First of all, I am warning the users of the problem with a dialog box before accepting to apply the Uninstall OneDrive button.

Did you not notice it?

Which version are you using?

**Comment by hellzerg** [comment]
Also, read the FAQ. 
I do warn the users of the problem.

https://github.com/hellzerg/optimizer/blob/master/FAQ.md

**Comment by aozorabsl** [comment]
Thanks for the reply. I will just admit the fact that aging hits bad against my eyesight.
