### ISSUE TITLE
My PC started to work INSANELY slow

### ISSUE THREAD

**Issue by ezluci** [hellzerg/optimizer#22]
When I put my cursor on my desktop icons, I need to wait around 2 seconds for Windows to highlight them. Everything works 5 times slower than before running this app. I don't know what's wrong or how do I get back to normal.

**Comment by ezluci** [comment]
Not sure why but this is happening after 30 seconds when you log in.
I solved it by disabling all the settings.
These are the settings that caused my problem:
![image](https://user-images.githubusercontent.com/68049793/107645538-7a196e00-6c81-11eb-9cdf-5c1c39e4be16.png)
![image](https://user-images.githubusercontent.com/68049793/107645592-8bfb1100-6c81-11eb-9d67-7eda161ddfdf.png)
Nothing else.

**Comment by hellzerg** [comment]
If you enable them again, they are causing the same behavior?

**Comment by ezluci** [comment]
Yes. I tried to disable some of them (the second try is in the above photos) and it had the exact same behavior. I will find the option which causes the problem and I will tell you.

**Comment by hellzerg** [comment]
Di you pinpoint the problem?

**Comment by ezluci** [comment]
I'm sorry but I don't want to try it. Maybe the problem is my PC, but I sent you the settings that caused the problem. You can try it for yourself in a virtual machine.
Sorry :)

**Comment by hellzerg** [comment]
Can you share with me your Windows 10 build, and your hardware configuration?

**Comment by ezluci** [comment]
Version 2204, OS build 19041.804
AMD Ryzen 5 3500U
16 GB RAM
Radeon Vega RX

I'm using a laptop.

**Comment by hellzerg** [comment]
Maybe the problem is Sticky Keys/Spelling/Ink options.
