### ISSUE TITLE
Version 13.9 breaks snap assist

### ISSUE THREAD

**Issue by GustavRaispits** [hellzerg/optimizer#223]
I've just found out that the Windows optimizer breaks the snap assist on build 22621.1, when I try to disable the "Disable snap assist" funciton, I can't use the snap assist anymore.

There are also some issues with UI scaling.

**Comment by hellzerg** [comment]
I know there are problems with UI scaling with tabs headers.

What do you mean you can't use snap assist? If you reset the option and restart your computer, it should work.

**Comment by GustavRaispits** [comment]
> I know there are problems with UI scaling with tabs headers.
> 
> What do you mean you can't use snap assist? If you reset the option and restart your computer, it should work.

Sadly it doesn't, on build 22621.1 [Which is a build coming from the beta channel] I can't restore snap assist anymore after disabling it through the tool, I've tried multiple times and I'm sure that it doesn't restore it at all. For restoring it I had to use another program because the Windows Optimizer couldn't do that, for some reason. That might be my problem probably?

**Comment by hellzerg** [comment]
I'll see what happens. It might be the beta channel changed something.

**Comment by peti-git** [comment]
it just happened to me as well. Fresh installation of 22000.918, after running Optimizer 13.9, drag to edge is not working anymore. Snapping with windows+arrow keys are OK.

**Comment by peti-git** [comment]
it's definitely something within hcku\control panel\desktop. Restored it from another user, and it is working again

**Comment by hellzerg** [comment]
Tell me how did you do it
@peti-git

**Comment by peti-git** [comment]
actually found the cause of the issue. optimizer creates/changes the DockMoving value as DWORD, but it should be String. Hence after reverting the Snap Assist setting the drag to snap feature did not work. 
PS. I believe the Snap Assist refers only to selecting an app to be snapped to the opposite part of the screen, so not sure if it has to disable all kinds of snapping at all.

**Comment by hellzerg** [comment]
Okay, nice point. Usually keys like 0/1, enable/disable are Dwords in registry.

Strange that this is a Reg string value.

I'll fix it.

**Comment by hellzerg** [comment]
Please update to v14.0 and the problem will be gone.
