### ISSUE TITLE
13.9 make taskbar smaller

### ISSUE THREAD

**Issue by nic-san** [hellzerg/optimizer#224]
Windows 11 only: when I activate this option, Make Taskbar smaller, the internet, sound, energy etc. icons are bugged, they apear "behind, lower" they should
this is the normal:
![image](https://user-images.githubusercontent.com/77157262/187467909-386994d9-e208-49d9-8a53-6bf59d27bd18.png)

**Comment by nic-san** [comment]
Here u can see the bug's
![image](https://user-images.githubusercontent.com/77157262/187478490-af5aa2be-952e-4f6b-8a83-1c7df265c27f.png)

**Comment by hellzerg** [comment]
That is Microsoft's bug, not mine, unfortunately.

**Comment by hellzerg** [comment]
it's a known bug since the first insider builds of Windows 11.

**Comment by nic-san** [comment]
ohh, i see, thanks man!

**Comment by nic-san** [comment]
im closing the issue. thx for the attention
