### ISSUE TITLE
New user 13.9

### ISSUE THREAD

**Issue by Meche697** [hellzerg/optimizer#225]
Just found your software. Thank you
Windows 10x64 21H2 Build 19044.1889
1) Not totally portable. Files saved to C:\ProgramData\Optimizer. Portable means nothing stays behind showing anyone you used the software. This program is not added to the Programs and the registry, but files remain (not deleted)
2) Startup, all items are unchecked with Type to Run. Not true. Several items were hand selected to run with MSConfig prior to this software. This tells me that it does NOT read the current state. I had some other tweaks, but neither universal or windows 10 tab explained what was being changed.
3) HOSTs is very intriguing and needto play with that more
4) Registry - Hovering over any item does NOT tell me what it's doing. Asking for a "blind" fix from the user.

The following were errors I got and not sure what to make of them

Windows 10 Home - 2009 (64-bit)
Optimizer 13.9 - .NET Framework 4.8 - Experimental build: False

[ERROR] [9/1/2022 12:18:20 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

[ERROR] [9/1/2022 12:25:42 PM] in function [Utilities.OpenSubKeyWritable]
Subkey VSStandardCollectorService150 not found.

-

[ERROR] [9/1/2022 12:25:42 PM] in function [Optimize.DisableVisualStudioTelemetry]
Object reference not set to an instance of an object.

   at Optimizer.Utilities.GrantFullControlOnSubKey(RegistryKey registryKey, String subkeyName)
   at Optimizer.Utilities.DisableProtectedService(String serviceName)
   at Optimizer.Optimize.DisableVisualStudioTelemetry()

[ERROR] [9/1/2022 1:44:15 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

[ERROR] [9/1/2022 1:53:13 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

[ERROR] [9/1/2022 1:56:35 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

**Comment by hellzerg** [comment]
I never said the app is portable. 
Of course an app that optimizes and configures Windows installations per computer NEEDS some config files behind, which are really tiny in size.

You can ignore those errors, if the app is working fine.

Registry fixes are necessary only when a malicious code disabled your task manager, registry editor, and other vital parts of Windows, so you can enable them again.

@Meche697
