### ISSUE TITLE
Optimizer gives a error when needs to restart to apply a setting.

### ISSUE THREAD

**Issue by Bluelytning16** [hellzerg/optimizer#228]
Hello, some days ago i just reinstalled windows and downloaded optimizer for w10. When finished with all the settings in upper right corner it says restart to apply settings and when i click on that button which is round (not where it writes because nothing is happening) it gives me an error.
![Screenshot 2022-09-21 185347](https://user-images.githubusercontent.com/114093892/191552296-c3ba0e8a-13b2-47e3-8f2a-cc1f03b85a65.png).
This is the error.

**Comment by hellzerg** [comment]
I am aware of this bug, I'll fix it soon.

**Comment by hellzerg** [comment]
Please update to v14.0 and the problem will be gone.
