### ISSUE TITLE
Google chrome telemetry  [Feature Removal]

### ISSUE THREAD

**Issue by fieraoh** [hellzerg/optimizer#230]
The Google chrome telemetry tweak is ineffective for most users as the loaded policies won't register to the browser unless it's connected to an active directory domain or enrolled in device management

Since the app has no tweaks geared toward Enterprise this feature looks misplaced especially that similar tweaks could be applied to Edge under the same constraints.

**Comment by hellzerg** [comment]
Okay, will look into that.
