### ISSUE TITLE
Suggestion : Make a default size of Windows for see all options

### ISSUE THREAD

**Issue by kalimaenergy** [hellzerg/optimizer#231]
Hello,

Maybe can great to have option or default value for display all settings on the screen.

We need to extend view for see all settings. 

Thank you for your amazing software and have a nice day,

**Comment by hellzerg** [comment]
Show me a picture of your screen with Optimizer on it.

**Comment by kalimaenergy** [comment]
Hello DeadMoon,

Thank you for your answer,

You can found bellow the screenshot of the issue.

I founded the root cause : it’s the scale of windows. I use 125% scaling for have better view and comfort with my display.

100% : no Issue
125% and higher : some missing settings on default view, I can extend the windows and view all settings.

Thank you and have a nice day,

Kalima

**Comment by kalimaenergy** [comment]
Hello Hellzerg,

Thank you for your answer,

You can found the screenshot of the issue with this link : https://imgur.com/a/R1b4YBv

I founded the root cause : it’s the scale of windows. I use 125% scaling for have better view and comfort with my display.

100% : no Issue
125% and higher : some missing settings on default view, I can extend the windows and view all settings.

Thank you and have a nice day,

Kalima

**Comment by hellzerg** [comment]
Okay, I will try to find a solution.
