### ISSUE TITLE
Personalization Lock Screen and Optimizer Menu

### ISSUE THREAD

**Issue by alyasboytigas** [hellzerg/optimizer#236]
Hi,

Just installed optimizer 2 things I'm struggling to figure out:

1. The personalization lock screen seems stuck on 1 image no matter what I do to change it, it wont change.

![Screenshot (5)](https://user-images.githubusercontent.com/57547739/194715425-0f97064a-1960-4c48-a497-f338113d5311.png)

2. The optimizer menu seems off, they're all cram together.

![Screenshot (6)](https://user-images.githubusercontent.com/57547739/194715508-e41ba32b-f870-4de1-97e8-b3844ba69e59.png)

thanks

**Comment by Jisll** [comment]
You have to choose slideshow, with "Picture" you have only the selected one all the time.

If I have misunderstood, please answer again.

**Comment by Jisll** [comment]
> So, it's not a bug or not?
> 
> @Jisll

The way I see it or read it, the screen is stuck on a picture, but it has "Picture" selected so it doesn't change anything. He must test it with "Slideshow

**Comment by hellzerg** [comment]
@alyasboytigas Try the new v14.2, the scaling problem on tabs is resolved.

**Comment by alyasboytigas** [comment]
@hellzerg thanks I'll try that new version now, and report back.

**Comment by alyasboytigas** [comment]
I tried the v14.2 seems looks the same as previous problem.


![Screenshot (12)](https://user-images.githubusercontent.com/57547739/197308610-94cb5be5-d945-4cf3-8abd-b80471b0e098.png)

As for the lock screen either I select any on the picture or the slideshow seems the same windows photo default.

![Screenshot (11)](https://user-images.githubusercontent.com/57547739/197308671-234337dc-c3fa-475a-bcd5-7b231c428fd8.png)

![Screenshot (10)](https://user-images.githubusercontent.com/57547739/197308673-276dade5-2a80-4e02-b72e-bbad8c21f24a.png)

**Comment by hellzerg** [comment]
What display resolution you have?

**Comment by hellzerg** [comment]
Also, which buil of Windows 11 you have installed?

**Comment by hellzerg** [comment]
@alyasboytigas 

If you don't answer to my questions, the problems won't get resolved.

**Comment by alyasboytigas** [comment]
Resolution is 3840x2160
I have Windows 11 Home Build 22621

Thanks.

**Comment by hellzerg** [comment]
Wallpaper pictures are working fine for me, same build.

I'll send you a test build for the menu scaling.

**Comment by hellzerg** [comment]
Yes, lockscreen wallpaper is fine for me.

**Comment by alyasboytigas** [comment]
Thanks, maybe problem with windows lock screen, no big deal. What matters my systems works really fast now... thanks for the help.

**Comment by hellzerg** [comment]
[OptimizerTest#236.zip](https://github.com/hellzerg/optimizer/files/9845951/OptimizerTest.236.zip)

Try this build for the menu scaling problem and report back.

**Comment by alyasboytigas** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/57547739/197417818-fc74a398-1681-4182-991d-93922400d342.png)

Perfect! Thank You!

**Comment by hellzerg** [comment]
Ok, I'll update the app in the next days.
