### ISSUE TITLE
Can't activate LTSC 2021 Volume Licensed Office after applying all tweaks.

### ISSUE THREAD

**Issue by SupLiCatinG** [hellzerg/optimizer#237]
Something disables service related to office activation.

**Comment by hellzerg** [comment]
Maybe Office Telemetry?

**Comment by SupLiCatinG** [comment]
Sorry for not responding. On W10 i can activate flawlessly but when i try on W11 it can't activate.

I did everything correct  but no success.

Do you know which services optimizer disables affecting Office ?

**Comment by hellzerg** [comment]
Office Telemetry only. Just reset the option.

@SupLiCatinG

**Comment by SupLiCatinG** [comment]
Thanks, i will give it a try.
