### ISSUE TITLE
24 engines detected this file

### ISSUE THREAD

**Issue by crazyyzarc** [hellzerg/optimizer#24]
Why?
https://www.virustotal.com/gui/file/8c4a4e8cff98581cea70b749fb78b257bca31b33e9b920b70a7144dc6d729278/detection

**Comment by rapdodge** [comment]
![image](https://user-images.githubusercontent.com/33513626/108335555-ad21ab80-7205-11eb-9bc9-6f307df4c378.png)

Screenshot of latest version of optimizer...

**Comment by hellzerg** [comment]
I can't do anything about that. It's false positive. Only by marking the file as trusted, we can make a difference.
