### ISSUE TITLE
A popup window

### ISSUE THREAD

**Issue by Olove521** [hellzerg/optimizer#243]
open it will show ![image](https://user-images.githubusercontent.com/90228929/197690036-ac1257e6-64d5-420a-bd05-9b94792007a6.png)
l think could remove this it  or repair .

**Comment by hellzerg** [comment]
Send me the log file located in C:\ProgramData\Optimizer.

**Comment by Olove521** [comment]
647556537
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hellzerg/optimizer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hellzerg/optimizer] A popup window (Issue #243)





 
Send me the log file located in C:\ProgramData\Optimizer.

**Comment by hellzerg** [comment]
That's not the log file.

**Comment by vadiscode** [comment]
For some reason it is blocking access to the raw.githubusercontent.com host and this happens during requests to the host. It is possible that the speed of the Internet does not allow to read quickly the information from the host. Basically, for these cases you can fix it with this method (as example).
```csharp
string latestVersion = string.Empty;
try 
{
    latestVersion = client.DownloadString(_latestVersionLink)
}
catch (WebException e) when (e.Status == WebExceptionStatus.NameResolutionFailure)
{
    // Here you need to implement a re-request to the host
}
```

**Comment by hellzerg** [comment]
Yes, it might be possible. One try will show us the real problem.
