### ISSUE TITLE
Deleted pictures, documents folder

### ISSUE THREAD

**Issue by thenasim** [hellzerg/optimizer#244]
I had activated some optimization and after restarting I lost all the files in pictures and documents. I had some important files in pictures and documents folder in C drive 😭. 
![image](https://user-images.githubusercontent.com/23162353/197717405-78f5ba15-85b2-4dca-8779-b0f41c860836.png)

**Comment by hellzerg** [comment]
Did you check Uninstall OneDrive option in Windows 11 tab?

**Comment by thenasim** [comment]
> Did you check Uninstall OneDrive option in Windows 11 tab?

Yes.

**Comment by hellzerg** [comment]
That's why. Did you read the warning message before applying the tweak?

**Comment by hellzerg** [comment]
Please read before choosing any option... Sorry for the inconvenience
