### ISSUE TITLE
Current settings not detected?

### ISSUE THREAD

**Issue by BlueDrakoPT** [hellzerg/optimizer#247]
I disabled Telemetry manually. Why optimizer don't detect that and switches "Telemetry" to "disabled" ???? (Windows 10 22H2)

**Comment by hellzerg** [comment]
Yes, it does not detect the changes on the system.
My software has a set of registry tweaks, file changes and commands to control internal windows settings. It's not possible to detect all of those tweaks on the system, or it might be that some of them are already applied, but not the whole set of it.

I hope you get the idea.
