### ISSUE TITLE
Laptop Camera

### ISSUE THREAD

**Issue by DemiLolvato** [hellzerg/optimizer#25]
My laptop camera is not working, not sure what should I enable.

**Comment by hellzerg** [comment]
You need drivers. Optimizer can't enable it.

**Comment by DemiLolvato** [comment]
I have drivers, after playing with your app it stopped working.

**Comment by DemiLolvato** [comment]
something from here that could have caused that?
![Untitled](https://user-images.githubusercontent.com/74899146/108627665-78a92c00-745f-11eb-864e-d8d02817f599.png)
![Untitled2](https://user-images.githubusercontent.com/74899146/108627668-7b0b8600-745f-11eb-9034-ac89413479fc.png)

**Comment by DemiLolvato** [comment]
oh nvm it's not from here

**Comment by hellzerg** [comment]
Maybe permissions problem, don't Disable Privacy Options & Sensor Services.

**Comment by DemiLolvato** [comment]
no, now I know why, I enabled  performance tweaks and then disable it. Now that I enabled that again it works, very weird

**Comment by hellzerg** [comment]
Go to Windows Settings > Privacy > Camera and check permissions.

**Comment by DemiLolvato** [comment]
I already did that.

**Comment by hellzerg** [comment]
Did you restart? It may fixed the issue.

**Comment by DemiLolvato** [comment]
Restarted a lot of times, but enabling performance tweaks again solved it

**Comment by DemiLolvato** [comment]
It works when I have performance tweaks enabled but dosen't when they are disabled.

**Comment by hellzerg** [comment]
Try manually disabling diagtrack service and see what happens

**Comment by DemiLolvato** [comment]
how it on has start and stop

**Comment by hellzerg** [comment]
Stop it and try the camera.

**Comment by DemiLolvato** [comment]
it's stopped by default and won't start

**Comment by hellzerg** [comment]
Right-click on service > Properties and change start type to Manual

**Comment by DemiLolvato** [comment]
I don't have the option in the task manager services and I don't have diagtrack in normal services

**Comment by hellzerg** [comment]
I don't understand why it behaves in that way..

**Comment by DemiLolvato** [comment]
My laptop has always been weird

**Comment by hellzerg** [comment]
what do you mean by that?

**Comment by DemiLolvato** [comment]
If I get a virus I have to reinstall the windows, bios and all the drivers to work normally again.

**Comment by hellzerg** [comment]
You have a virus now?

**Comment by DemiLolvato** [comment]
nope, I had like a year ago from somekind of rom

**Comment by hellzerg** [comment]
Well, I suggest you format and setup a fresh install of Windows.

**Comment by DemiLolvato** [comment]
I did that, took a fresh intall of win 10, looked on the internet how to format correctly with it and installed it.

**Comment by DemiLolvato** [comment]
The virus was no more but my pc was still acting weird until I reinstalled the bios and all the drivers

**Comment by hellzerg** [comment]
Well, if you want help, I can help you from Discord.

**Comment by DemiLolvato** [comment]
I mean my camera is ok but I just wanted you to know its from enabling and disabling performance tweaks. Maybe you can find a solution if anyone has the same problem.

**Comment by hellzerg** [comment]
I'll have it on my mind.. but it's so weird. Anyway, thanks.
