### ISSUE TITLE
Context Menu missing options

### ISSUE THREAD

**Issue by Afterro** [hellzerg/optimizer#250]
So, after using the optimizer, context menu is missing options. I can't even create a new text file. Any fixes pls? :<

**Comment by Afterro** [comment]
I checked errors in optimizer and there are alot of errors ;c
Here's a [link](https://pastebin.com/KuTyJrGs) to pastebin with those errors

**Comment by Afterro** [comment]
That's what context menu looks like now
![image](https://user-images.githubusercontent.com/112660815/198832566-a9e92ed9-425e-4e04-8b80-caca345059c3.png)

**Comment by hellzerg** [comment]
Optimizer does not touch anything in context menus, so something else might be, or it was always like this.

**Comment by Afterro** [comment]
So I suppose something from "Apps" tab, I installed some of them instantly but didn't think it might be something from there :/

**Comment by hellzerg** [comment]
How was it before?

**Comment by Afterro** [comment]
I searched for a bit and found this [page](https://www.tenforums.com/tutorials/24412-add-remove-default-new-context-menu-items-windows-10-a.html)
after using "Restore_ALL_default_New_context_menu_items.reg" it all went back to exactly what I want :D

Answering your question, before I used optimizer everything was fine, but after using some options AND installing apps like VS Code, notepad++, Steam, Discord, even the default Win 11 context menu was missing New file options. I think maybe I did something wrong. Anyways it works great now, thanks for answering :)

**Comment by hellzerg** [comment]
Maybe it's Windows 11 idiotic menu.
Anyway, I am happy you resolved your issue and everything works better now.
