### ISSUE TITLE
Miner trojan

### ISSUE THREAD

**Issue by Sizz2K** [hellzerg/optimizer#251]
So there was no issue what so ever before I installed your program,after reboot I got my gpu card bios changed,card overloads,system got laggy I thought it's false issue about "malwares" in it.
How do I get rid of it ?

**Comment by hellzerg** [comment]
You enabled Gaming Mode ?

@Sizz2K

**Comment by vadiscode** [comment]
@Sizz2K 
> So there was no issue what so ever before I installed your program,after reboot I got my gpu card bios changed,card overloads,system got laggy I thought it's false issue about "malwares" in it. How do I get rid of it ?

The program does not change what you are talking about, and especially does not use your GPU card.

**Comment by Sizz2K** [comment]
Okay I figured it out it's not a miner trojan it's a rootkit virus Don't download this crap of a utility.
