### ISSUE TITLE
game mode being disabled

### ISSUE THREAD

**Issue by DukeJukemEG** [hellzerg/optimizer#252]
theres a setting somewhere that disables game mode and idk if its the disable xbox live or the game bar option or something else but if i check enable game mode FIRST and then hit the mystery button that re disables it...well it kinda sucks and technically undoes a tweak. the program also doesnt reflect that game mode is disabled when this happens. i have to manually re enable game mode in windows even though optimizer is saying game mode is enabled.

**Comment by hellzerg** [comment]
Yes, i know the problem. It's gamebar. I'll fix it today.
