### ISSUE TITLE
Duplicate: Google Chrome Telemetry 

### ISSUE THREAD

**Issue by fieraoh** [hellzerg/optimizer#253]
As mentioned in #230 

The policies do not register inside of the Chrome browser and get ignored:
![image](https://user-images.githubusercontent.com/72320316/199502024-6a814232-6a5e-4627-9757-c94503827971.png)

The folks at O&O Shutup have figured out a way to get the policies to work on Edge:
![image](https://user-images.githubusercontent.com/72320316/199501717-1423f1e2-96c7-4fb1-8d5d-2dcef41a9ae6.png)

So unless you can implement a similar workaround, the feature should not ship with the program.

**Comment by hellzerg** [comment]
You have Windows Home or Pro edition?

Chrome will ignore the policies set on a Windows Home edition computer, because, well Google logic.

@fieraoh
