### ISSUE TITLE
Rootkit virus be aware

### ISSUE THREAD

**Issue by Sizz2K** [hellzerg/optimizer#255]
Don't download this crap of utility still can't get rid of this rootkit shit,my gpu's bios got changed.
U gonna get new users in your windows after reboot,also
Rootkits really hard to detect,messed my regedit.

**Comment by hellzerg** [comment]
@Sizz2K 

From where did you download the software?
Also, show us images of your problem.

This is at all rootkit.

**Comment by dalisoft** [comment]
@Sizz2K Thank you for reporting issues but can you clarify the case before reporting such invalid issue without example and showcase.
And about GPU bios, for flash GPU need additional codes and tools and it takes time to code which on author may be have not. I am using this tool within 1 years and no issues yet.
After all, no one forced you use this tool.
