### ISSUE TITLE
Can't open app anymore

### ISSUE THREAD

**Issue by DStevens5833** [hellzerg/optimizer#256]
Not sure what happened, but the GUI closes after the "checking for requirements" message appears. 

Edit: Also deleted my nvidia control panel. I had to reinstall my driver to detect my g-sync monitor's capabilities as well as restore the context menu.

**Comment by hellzerg** [comment]
Did you use any of the tweaks?

**Comment by DStevens5833** [comment]
Yes, I did. I didn't use all of them, but I think it had something to do with removing the "bloatware." I say this because GeForce Experience wanted me to re-download the NVIDIA Control Panel through the Microsoft Store... which had already been removed. Obviously I just re-installed my driver--which includes the control panel. However, there looked to be a lot of Microsoft "apps" (outside of the original bloat) that were removed, including things linked to visual studio/runtimes; dependencies, maybe? I still can't get Optimizer to open.

**Comment by hellzerg** [comment]
Send me the log file in C:\ProgramData\Optimizer.

Also, did you uninstall all the UWP apps in the list?

**Comment by DStevens5833** [comment]
I did, unfortunately. I didn't look closely enough before I ran it. 

```
Windows 10 Home - 21H2 (64-bit)
Optimizer 14.3 - .NET Framework 4.8 - Experimental build: False


[ERROR] [11/3/2022 1:58:07 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()


[ERROR] [11/3/2022 2:18:56 PM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()



```

**Comment by hellzerg** [comment]
Hm, okay, send me the json file also.
And then delete whole folder and it should run again

**Comment by DStevens5833** [comment]
Looks like "AppsFolder" being null might be the culprit?

```
{
  "Theme": "0, 0, 0, 0",
  "AppsFolder": null,
  "EnableTray": false,
  "ShowHelp": false,
  "AutoStart": false,
  "LanguageCode": 0,
  "EnablePerformanceTweaks": false,
  "DisableNetworkThrottling": false,
  "DisableWindowsDefender": false,
  "DisableSystemRestore": false,
  "DisablePrintService": false,
  "DisableMediaPlayerSharing": false,
  "DisableErrorReporting": false,
  "DisableHomeGroup": false,
  "DisableSuperfetch": false,
  "DisableTelemetryTasks": false,
  "DisableCompatibilityAssistant": false,
  "DisableFaxService": false,
  "DisableSmartScreen": false,
  "DisableCloudClipboard": false,
  "DisableStickyKeys": false,
  "DisableHibernation": false,
  "DisableSMB1": false,
  "DisableSMB2": false,
  "DisableNTFSTimeStamp": false,
  "DisableOffice2016Telemetry": false,
  "DisableVisualStudioTelemetry": false,
  "DisableFirefoxTemeletry": false,
  "DisableChromeTelemetry": false,
  "DisableNVIDIATelemetry": false,
  "DisableOneDrive": false,
  "EnableLegacyVolumeSlider": false,
  "DisableQuickAccessHistory": false,
  "DisableStartMenuAds": false,
  "UninstallOneDrive": false,
  "DisableMyPeople": false,
  "DisableAutomaticUpdates": false,
  "ExcludeDrivers": false,
  "DisableTelemetryServices": false,
  "DisablePrivacyOptions": false,
  "DisableCortana": false,
  "DisableSensorServices": false,
  "DisableWindowsInk": false,
  "DisableSpellingTyping": false,
  "DisableXboxLive": false,
  "DisableGameBar": false,
  "DisableInsiderService": false,
  "DisableFeatureUpdates": false,
  "EnableLongPaths": false,
  "RemoveCastToDevice": false,
  "EnableGamingMode": false,
  "TaskbarToLeft": false,
  "DisableSnapAssist": false,
  "DisableWidgets": false,
  "DisableChat": false,
  "TaskbarSmaller": false,
  "ClassicRibbon": false,
  "ClassicMenu": false,
  "DisableTPMCheck": false,
  "CompactMode": false,
  "DisableStickers": false,
  "DisableVBS": false
}
```

**Comment by DStevens5833** [comment]
For what it's worth, here are the remnants of the UWPs:

```
Microsoft.WindowsStore
Microsoft.UI.Xaml.2.7
Microsoft.UI.Xaml.2.7 (dupilcate for some reasion?)
Microsoft.NET.Native.Framework.2.2
Microsoft.NET.Native.Framework.2.2 (another duplicate)
Microsoft.NET.Native.Runtime.2.2
Microsoft.NET.Native.Runtime.2.2 (another duplicate)
Microsoft.VCLibs.140.00
Microsoft.VCLibs.140.00 (another duplicate)
NVIDIACorp.NVIDIAControlPanel
```

**Comment by hellzerg** [comment]
You should not uninstall UWP with names you don't recognize or it's strange.

Yes, it might be the null in AppsFolder that causes the crash. I'll fix it.

**Comment by DStevens5833** [comment]
I agree, but most people are going to click everything....

**Comment by DStevens5833** [comment]
I still appreciate your effort. Thanks for the optimization

**Comment by hellzerg** [comment]
@DStevens5833 That's not how the program is designed to work. You are not supposed to blindly select every option. You use common sense. It's a tool that configs many many aspects of the Windows...

**Comment by DStevens5833** [comment]
Obviously. Maybe you should consider that, though? Do most people with computers use common sense?

**Comment by hellzerg** [comment]
@DStevens5833 

But, that is not my problem.

**Comment by omegartlx** [comment]
So has it been fixed because it is still happing

**Comment by hellzerg** [comment]
@omegartlx Better delete the entire Optimizer folder in C:\ProgramData

**Comment by omegartlx** [comment]
ok thx for fast reply
