### ISSUE TITLE
Add Another Feature

### ISSUE THREAD

**Issue by KingKrex69** [hellzerg/optimizer#257]
Add a Feature where you can disable "Sysmain" and "Windows Search" in "Services" tab, it decreases disk usage

**Comment by hellzerg** [comment]
Sysmain is disabled in Disable Superfetch option

@KingKrex69

**Comment by KingKrex69** [comment]
> 

What about "Windows Search"?

**Comment by hellzerg** [comment]
I'll include an option for windows search service in next version
