### ISSUE TITLE
Need add hosts without www

### ISSUE THREAD

**Issue by Margular** [hellzerg/optimizer#259]
Now when I add a custom host(ex. aaa.com) via optimizer, it will add www.aaa.com automatically. Can I disable this feature?

**Comment by hellzerg** [comment]
No, but why do you want not to include www?

**Comment by Margular** [comment]
Just because I don't need www prefix, such as I have a intranet domain portal.company.com, I don't need www.portal.company.com obviously. Expect for this feature thx!

**Comment by hellzerg** [comment]
Ok, in the next version soon.
