### ISSUE TITLE
Windows 10 20H2 - Considered Win32/Ymacco.AA64

### ISSUE THREAD

**Issue by bonitobonita24** [hellzerg/optimizer#26]
Hi, i just installed windows 10 version 10 20H2 and from windows defender it was detected as Win32/Ymacco.AA64. is it a false positive?
![Untitled](https://user-images.githubusercontent.com/9140721/111061883-7aa35f80-84e0-11eb-8076-2e7f2276600e.png)

**Comment by hellzerg** [comment]
It's obviously a false positive.

**Comment by hellzerg** [comment]
![image](https://user-images.githubusercontent.com/3146835/111652327-ac356700-880f-11eb-9774-9d08c430f5cd.png)

Detection removed from Microsoft Defender!
