### ISSUE TITLE
Windows Date and Time settings

### ISSUE THREAD

**Issue by sl4shjay141** [hellzerg/optimizer#262]
I dont know what switch does this but whenever i go to my date and time settings, time zone sync is greyed out (so i cant enable it) and every time i restart my pc, time sync auto-disables itself aswell as a few other buttons are greyed out, any solutions to this ?

**Comment by hellzerg** [comment]
Windows 11 or 10?

@sl4shjay141

**Comment by sl4shjay141** [comment]
windows 10

**Comment by sl4shjay141** [comment]
any fixes ?

**Comment by hellzerg** [comment]
Didn't find anything related to Optimizer tweaks. 
Maybe you have used some other software?

@sl4shjay141

**Comment by sl4shjay141** [comment]
i only have used winaero tweaker

**Comment by hellzerg** [comment]
Maybe it's that, because the Optimizer does not touch the date and time settings at all.

**Comment by Jisll** [comment]
You need to make sure if you have disabled the Windows Time service, if so enable it and start it.
The next thing that can be is the group policies, feel free to check there as well.

**Comment by IanArad** [comment]
I had a similar problem, only the option to set the **time automatically was disabled** for me.

I described the problem on [https://answers.microsoft.com/en-us/windows/forum/all/time-synchronization-error-time-has-a-delay-of/108abecc-8121-4fc5-bae8-a08fb1e44765](https://answers.microsoft.com/en-us/windows/forum/all/time-synchronization-error-time-has-a-delay-of/108abecc-8121-4fc5-bae8-a08fb1e44765)

In the end i ended up reinstalling Windows 11 Pro.
