### ISSUE TITLE
Weather is disabled without "Restore Classic File Explorer" on

### ISSUE THREAD

**Issue by sl4shjay141** [hellzerg/optimizer#263]
i just did a full reset of my pc, time zone sync is still greyed out and after redoing all of my tweaks w/out classic file explorer on, i proceed to reboot my pc to apply the changes, and suddenly, weather disappeared from my taskbar. And when i go to my taskbar settings, weather is now greyed out too (again i cant enable it).

**Comment by hellzerg** [comment]
Try enabling Classic File Explorer and then resetting it

**Comment by sl4shjay141** [comment]
reset my whole pc again ??

**Comment by hellzerg** [comment]
No, enabling and disabling Restore Classic File Explorer and then restart.

**Comment by sl4shjay141** [comment]
ok ill try this

**Comment by sl4shjay141** [comment]
didnt work. i even tried to update my gpu driver and nothing happened

**Comment by hellzerg** [comment]
Okay, I will try to find a solution next week. I'm busy right now.

**Comment by hellzerg** [comment]
Did you try deleting **ShellFeedsTaskbarViewMode** key in **HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Feeds** ??

**Comment by sl4shjay141** [comment]
no but i found a solution that works perfectly until i change something on the optimizer, setting the "IsFeedsAvailable" regkey to 1 works and the weather switch in taskbar settings is not greyed out anymore and i switched it on, but please fix whatever might be causing the weather to disappear without classic file explorer on in ur optimizer, tysm !!!!

**Comment by hellzerg** [comment]
Okay, will fix it.

**Comment by hellzerg** [comment]
But, I don't even touch this **IsFeedsAvailable** key anywhere in my Optimizer.
So, this might be set up by another tweaking app you used before, maybe.

@sl4shjay141
