### ISSUE TITLE
Problem with Optimizer 14.5

### ISSUE THREAD

**Issue by Felipefpl** [hellzerg/optimizer#264]
Go to Cleaner - Click the "Select All" link in the bottom right doesnt select all settings in the left side. My specs:

Processors
	Intel(R) Celeron(R) CPU G460 @ 1.80GHz
		Cores: 1
		Threads: 2
		Virtualization: -
		Data Execution Prevention: Yes
		L2 Cache: 256 KB
		L3 Cache: 1.54 MB
		Stepping: Intel64 Family 6 Model 42 Stepping 7
		Revision: 10759
Memory
	Module 2
		Manufacturer: Hynix/Hyundai
		Size: 4 GiB
		Memory Type: Unknown
		Speed: 1067 MHz
		Form Factor: DIMM
	Virtual Memory
		Total: 7.25 GiB
		Available : 4.91 GiB
		Used: 2.34 GiB
Graphics
	Intel(R) HD Graphics
		Video Memory: 1.86 GiB
		Video Memory Type: Unknown
		DAC Type: Internal
		Current Resolution: 1600 x 900
		Current Refresh Rate: 60 Hz
Motherboard
	ASUSTeK COMPUTER INC.
		System: System Product Name
		Chipset: Canal de IDE
		Product: P8H61-M LE/BR
		Model: 
		Version: Rev x.0x
		Revision: 
	BIOS
		Manufacturer: American Megatrends Inc.
		Manufacturer: BIOS Date: 05/13/13 10:27:34 Ver: 43.07
		Version: _ASUS_ - 1072009
		Build Number: 
Storage
	Disk Drives
		ST3500641AS ATA Device
			Size: 500.11 GB
			Firmware Revision:   3.AJJ
			Media Type: Fixed hard disk media
			Bytes/Sector: 512
	Partitions
		 (C:)
			File System: NTFS
			Size: 500.11 GB
			Used Space: 34.4 GB
			Free Space: 465.71 GB
			Indexing: No
			Compressed: No
			Drive Type: Local Disk
			Block Size: 4096
Network Adapters
	Physical Adapters
		Realtek PCIe GbE Family Controller
			Manufacturer: Realtek
			Adapter Type: Ethernet 802.3
			MAC Address: 30:85:A9:EA:38:4B
			Service Name: RTL8167
	Virtual Adapters
		WAN Miniport (SSTP)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: RasSstp
		WAN Miniport (IKEv2)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: RasAgileVpn
		WAN Miniport (L2TP)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: Rasl2tp
		WAN Miniport (PPTP)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: PptpMiniport
		WAN Miniport (PPPOE)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: RasPppoe
		WAN Miniport (IPv6)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: NdisWan
		WAN Miniport (Network Monitor)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: NdisWan
		WAN Miniport (IP)
			Manufacturer: Microsoft
			Adapter Type: 
			MAC Address: 
			Service Name: NdisWan
		Adaptador do Microsoft ISATAP
			Manufacturer: Microsoft
			Adapter Type: Tunnel
			MAC Address: 
			Service Name: tunnel
		RAS Async Adapter
			Manufacturer: 
			Adapter Type: 
			MAC Address: 
			Service Name: 
Audio
	Realtek High Definition Audio
		Manufacturer: Realtek
		Status: OK
Peripherals
	Keyboards
		Dispositivo de Entrada USB
			Layout: 00000416
			Function Keys: 12
			Status: OK
			Locked: No
	Pointing Devices
		Dispositivo de Entrada USB
			Manufacturer: (Dispositivos padrão do sistema)
			Buttons: 0
			Pointing Type: Unknown
			Device Interface: USB
			Hardware Type: Dispositivo de Entrada USB
			Status: OK
			Locked: No

**Comment by hellzerg** [comment]
That's not what this button does.
Cleaner works like this:

1. Select which folders you want to analyze from left panel
2. Click analyze to see whole size you can free up
3. Select all or some files and click clean
4. 
@Felipefpl

**Comment by Felipefpl** [comment]
@hellzerg - i see, sorry for writing a non-issue, thanks for the help.
