### ISSUE TITLE
NTFS timestamp

### ISSUE THREAD

**Issue by davedave85** [hellzerg/optimizer#265]
Hi,

im trying this feature but when i enabled it and after reboot i check into registry and its enabled.

**Comment by hellzerg** [comment]
The NTFS timestamp is not set in registry, but using cmd command. You should check it there.

@davedave85

**Comment by davedave85** [comment]
oh gotcha, but it doesnt conflict with the registry?

**Comment by hellzerg** [comment]
Show me the registry key.

@davedave85

**Comment by hellzerg** [comment]
Ah, I know the problem. Setting gets resetted by OS on reboot, because my config does not user UserManaged key.
It will be fixed in next update.

If you want to persistently disable it, before the update, change the key to **80000001**

@davedave85

**Comment by davedave85** [comment]
its ok! i wait the next update
thats why i create other thread with detailed tweaks, so the community can check this flags!
