### ISSUE TITLE
Detailed tweaks

### ISSUE THREAD

**Issue by davedave85** [hellzerg/optimizer#266]
Will be good to have a detail of what values it changes into system,

**Comment by Jisll** [comment]
This function already exists, put your mouse on the text and you will see what it does.

**Comment by davedave85** [comment]
its not detailed

**Comment by hellzerg** [comment]
@davedave85 

It's so many tweaks in the Optimize Performance toggle that can't list them all. But the most important ones are there.

**Comment by davedave85** [comment]
yes, but will be possible to create a readme for this detail in github, so every person can check it

**Comment by hellzerg** [comment]
@davedave85 

You mean a readme in the github page with the details?

**Comment by davedave85** [comment]
yes
