### ISSUE TITLE
Windows Automatic Updates

### ISSUE THREAD

**Issue by themegaxandy** [hellzerg/optimizer#268]
I noticed that turning on the option to disable automatic updates from Windows Update not only turns off automatic updates, but manual ones as well. I noticed this when I got an error when trying to look for updates on Windows Update and Microsoft Store. It only returned to normal when I disabled that option and restarted the computer.

So, three things:
1 - Disabling automatic updates disables manual ones as well.
2 - It disables Microsoft Store downloads as well.
3 - It is necessary to restart the computer to apply the updates (Optimizer does not indicate this).

Windows 11 22H2

**Comment by hellzerg** [comment]
Okay, will look into Microsoft store updates.

But, what do you mean the manual updates get disabled ?
You mean, you can't download and install any updates at all?

@themegaxandy

**Comment by vadiscode** [comment]
> I noticed that turning on the option to disable automatic updates from Windows Update not only turns off automatic updates, but manual ones as well. I noticed this when I got an error when trying to look for updates on Windows Update and Microsoft Store. It only returned to normal when I disabled that option and restarted the computer.
> 
> So, three things: 1 - Disabling automatic updates disables manual ones as well. 2 - It disables Microsoft Store downloads as well. 3 - It is necessary to restart the computer to apply the updates (Optimizer does not indicate this).
> 
> Windows 11 22H2

Of course, the program turns off updates completely, therefore, even manual installation will not work, to make it work you have to turn on updates again.

**Comment by hellzerg** [comment]
@themegaxandy 

Wait, wait... The option Disable Automatic Updates does exactly that.
Maybe something changed in Windows 11 and breaks the updates?

In Windows 10 (any edition), all it's working fine. I'm updating manually for years.

**Comment by themegaxandy** [comment]
> @themegaxandy
> 
> Wait, wait... The option Disable Automatic Updates does exactly that. Maybe something changed in Windows 11 and breaks the updates?
> 
> In Windows 10 (any edition), all it's working fine. I'm updating manually for years.

Well, that's weird. But this is exactly the behavior that is happening to me (as I described). It might be because of the Windows version as you mentioned.

**Comment by hellzerg** [comment]
@themegaxandy 

Show me a screenshot of Windows Update section in Settings.
Is there an error or a message?

**Comment by themegaxandy** [comment]
Yes, there is an error code 0x80004002.

![image](https://user-images.githubusercontent.com/7902295/206582011-f16c9672-b230-4a32-bc94-3144131fdc15.png)

It shows "downloading - 0%", and then it fails right after that. It doesn't even reach 1%.

**Comment by hellzerg** [comment]
@themegaxandy 

Try clearing the Windows Update cache using Way 3, in the following link:
https://www.minitool.com/news/clear-windows-update-cache.html

Also, check if Windows Update services are enabled properly in Services.msc.

Then restart your PC and try again.

**Comment by themegaxandy** [comment]
I cleaned Windows Update cache (Way 3 on the article), restarted, and checked Windows Update services (wuauserv, cryptSvc, bits, msiserver). Tried to update with Optimizer's option activated, and still the same issue. I can't manually update Windows via Windows Update, and I can't update nor install new apps on Microsoft Store. 

I can disable that Optimizer option if I really want to update as I stated before. It's not a big deal. But I will help you if that is not the behavior you want with your tool.

**Comment by hellzerg** [comment]
Windows 11 Home or Pro edition?

@themegaxandy

**Comment by themegaxandy** [comment]
This is Windows 11 Pro edition. Build 22623.1028.

**Comment by themegaxandy** [comment]
This is my Optimizer settings. 

![image](https://user-images.githubusercontent.com/7902295/206701128-d7b447b0-4fb8-4278-a746-913dea21c27f.png)

![image](https://user-images.githubusercontent.com/7902295/206701164-d1200929-8e52-4a6e-9dee-00acd92ee7b2.png)

I narrowed it down to that Disable Automatic Updates option. And I'm sure that if I disable that option, and restart the pc, the updates goes back to normal.

**Comment by hellzerg** [comment]
![image](https://user-images.githubusercontent.com/3146835/206702971-70a5df8a-7aca-4254-a4ae-669aaa9279e1.png)

Try navigating to AUOptions and AutoDownload with registry editor and delete them.

AUOptions is for Windows Update
AutoDownload is for Microsoft Store updates.

**Comment by themegaxandy** [comment]
Deleted AUOptions and AutoDownload entries, restarted the PC. Those entries remained deleted after restart. I tried again and got the same 0x80004002 error on both Windows Update and Microsoft Store.

**Comment by themegaxandy** [comment]
Deleted SystemSettingsDownloadMode entry, restarted the PC. Those entries remained deleted after restart. I tried again and the updates completed on both Windows Update and Microsoft Store :)

**Comment by hellzerg** [comment]
Hmmm, okay... that's really strange. Maybe I need to change my tweaks, or remove some of them.

**Comment by themegaxandy** [comment]
Yes, I think it would be a good idea to test it on another Windows 11 computer as well, to see if this is just me.
