### ISSUE TITLE
Disabling Enable Performance Tweaks remove SystemResponsiveness

### ISSUE THREAD

**Issue by GabPierre08** [hellzerg/optimizer#27]
When I disable "Enable Performance Tweaks" it deletes "SystemResponsiveness" dword value at
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile

**Comment by hellzerg** [comment]
What's the default value of "SystemResponsiveness" before using Optimizer?

**Comment by GabPierre08** [comment]
14

**Comment by hellzerg** [comment]
I think if you delete the value, Windows will reset to default value, right?

**Comment by GabPierre08** [comment]
no it just deletes it

**Comment by GabPierre08** [comment]
also turning off disable network throttling deletes "NetworkThrottlingIndex" value

**Comment by GabPierre08** [comment]
If I turned on "enable performance tweaks" it will change the systemresponsiveness value to 1 and when i turn it off it just deletes the dword instead of setting the value back from 1 to default (14)

**Comment by hellzerg** [comment]
![image](https://user-images.githubusercontent.com/3146835/111651823-3d580e00-880f-11eb-8f03-c4e0149de14e.png)

**Comment by GabPierre08** [comment]
its 14 for me

**Comment by hellzerg** [comment]
Probably, it depends on the hardware?

**Comment by GabPierre08** [comment]
https://www.tenforums.com/performance-maintenance/132649-regedit-defaults.html

**Comment by hellzerg** [comment]
Okay, newer builds, newer defaults. But the question remains, if I delete the value completely, Windows resets it?

**Comment by GabPierre08** [comment]
no I have to manually add it back it does not reset

**Comment by GabPierre08** [comment]
Turning on "Enable Performance Tweaks" restores it

**Comment by hellzerg** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_7-networking/ping-problems/af7aaf26-c5e3-478c-b1b8-2b1443d1306b

**Comment by hellzerg** [comment]
SystemResponsiveness will default to 14 in v7.1.
