### ISSUE TITLE
Unable to use Phone Link

### ISSUE THREAD

**Issue by JaviruloNT** [hellzerg/optimizer#270]
Hello. I don't know what option might be causing this, if you could guide me to fix it, I would appreciate it.
![image](https://user-images.githubusercontent.com/110173052/207762455-7fce4f88-db26-4bfd-b451-e333e59aa121.png)
![image](https://user-images.githubusercontent.com/110173052/207762499-cd30a3f0-40b2-463e-87dd-9e263c55a72d.png)

**Comment by JaviruloNT** [comment]
Forgot to show the error message sorry
![image](https://user-images.githubusercontent.com/110173052/207762558-9c5fa1e6-377e-43e9-a7d9-5dcfa2ed40a8.png)

**Comment by hellzerg** [comment]
Try going to 

HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\System
-AND
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows

And if you see EnableMmx value in both keys, delete it and restart.

@JaviruloNT

**Comment by JaviruloNT** [comment]
It was only in the first one, I deleted it and it worked, thanks.
