### ISSUE TITLE
'Enhance Privacy' blocks and resets the already fragile Phone Link application

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hellzerg/optimizer#272]
Microsoft's Phone Link application is hard to configure and goes wrong a lot. So it was especially unwelcome when enabling this option

![image](https://user-images.githubusercontent.com/47056543/208311134-96edc891-8682-4b51-9511-209df1734f61.png)

and rebooting produced this:

![image](https://user-images.githubusercontent.com/47056543/208311157-2d5dff89-fe56-4c94-9684-7e4e0419b542.png)

Once I had disabled the 'Enhance Privacy' option within the Optimizer, I found that some settings on the Phone Link had been reset, such that I had to set up the 'link' again.

I cannot confirm this report - cannot confirm the causation I allege - because, I am afraid, I am not willing to re-enable the seemingly problematic Optimizer option. For, I don't want to risk making things go wrong again.

EDITED to add the images.

Optimizer 14.6
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by hellzerg** [comment]
That is how the Phone link reset works.
You have to set it up again

**Comment by LinuxOnTheDesktop** [comment]
Yet,  I did not tell the Phone Link app to reset itself - not knowingly. Rather, and as I said: I used an option within your program, and the result was - well, please re-read my original report.

**Comment by hellzerg** [comment]
Maybe I should move the Phone Link tweak to a single toggle.

**Comment by johanson** [comment]
> Maybe I should move the Phone Link tweak to a single toggle.

Adding to the description that it breaks Phone Link would be useful as well.
