### ISSUE TITLE
Running the program produces 'Optimizer Downloads' desktop directory, whether one wants it or not

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hellzerg/optimizer#273]
Seemingly one cannot get rid of this (even though I do not even know what the program might want to download):

![image](https://user-images.githubusercontent.com/47056543/208311183-4f44ff63-6d5b-4034-bac6-1bd7b0191237.png)

Well, one can delete it; but one cannot, I think, stop it from being created upon execution of the Optimizer.
Optimizer 14.6
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by hellzerg** [comment]
Go to Apps folder and change the location

**Comment by LinuxOnTheDesktop** [comment]
Aha!
