### ISSUE TITLE
Slow, visible window redraw upon any movement of the main window

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hellzerg/optimizer#274]
https://user-images.githubusercontent.com/47056543/208311328-a84c7e63-2089-4295-a0ea-ab74ea45052d.mp4

Optimizer 14.6
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by hellzerg** [comment]
I designed it that way for performance because the main window has a whole lot of controls.

**Comment by LinuxOnTheDesktop** [comment]
Aha. But it _looks_ like a bug. So some warning for the user - at least on your github README page - might be an idea.

**Comment by hellzerg** [comment]
Well, the functionality of the app is not affected at all, so it's not really a problem.
