### ISSUE TITLE
enable verbose messages

### ISSUE THREAD

**Issue by ghost** [hellzerg/optimizer#279]
great tool, thank you.

It would be nice if you can add: "Enable Verbose Messages"
It's done via Registry or Group Policy change:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/enable-verbose-startup-shutdown-logon-logoff-status-messages

**Comment by hellzerg** [comment]
How is that gonna help as an extra option?
@tygital

**Comment by tygital** [comment]
Windows offers to display detailed information status messages which shows exactly whats going on when the system starts up, shutdown, logon, and logoff operations. These are referred as to as verbose status message but by default they are disabled by Windows.

**Comment by tygital** [comment]
just an idea :)

**Comment by kalimaenergy** [comment]
+1 for this option :)

**Comment by hellzerg** [comment]
Really strange, because this option is so rarely used. 

Okay will include it, but we need a non-cryptic name for it.

**Comment by stuckydev** [comment]
Non-cryptic examples:

- Enable Detailed Login Screen
- Enable Detailed Login Screen
- Enable Login Screen Details
- Enable Login/Logut Screen Details

**Comment by hellzerg** [comment]
Okay, that is somewhat good, but it will certainly need an extra explanation.

**Comment by stuckydev** [comment]
"Shows status messages which show exactly whats going on during logon and logoff operations."

**Comment by hellzerg** [comment]
I will add new Tab named Advanced or something similar and there will be added this, along with other tweaks.

But this tab will only be visible when running Optimizer with /unsafe.

What do you say, is this okay?

@stuckydev 
@kalimaenergy

**Comment by stuckydev** [comment]
This is a great idea, perfect.

I will provide other advanced tweaks/ideas as soon as I can.

Thank you for your work!

**Comment by hellzerg** [comment]
The feature will be included in v15.0 today or tomorrow!

**Comment by stuckydev** [comment]
You sir, are a great guy :), thx!
