### ISSUE TITLE
It wonte open

### ISSUE THREAD

**Issue by LuckyStrikeOriginal** [hellzerg/optimizer#28]
I open, but not open. 

whey?

**Comment by hellzerg** [comment]
What's your Windows version? Also, send me the log file in C:\ProgramData\Optimizer.

**Comment by LuckyStrikeOriginal** [comment]
i open where u said to go but no log there? what canai do?

**Comment by LuckyStrikeOriginal** [comment]
Thank you very much for the fast reply, so I have tried to look for the log file. but there was nothing there like that. What did I do wrong?

**Comment by LuckyStrikeOriginal** [comment]
oopsy D:

**Comment by Aida-Enna** [comment]
New release is detected a virus by Windows Defender.

**Comment by gnialXD** [comment]
The same thing happens to me, too, what do I do?

**Comment by gnialXD** [comment]
![image](https://user-images.githubusercontent.com/82129025/113955783-0491d000-97e2-11eb-8f2d-af90d050746f.png)

**Comment by gnialXD** [comment]
![image](https://user-images.githubusercontent.com/82129025/113955853-1d01ea80-97e2-11eb-8a07-3ab91b080c92.png)

**Comment by hellzerg** [comment]
Try excluding it from Windows Defender.

**Comment by LuckyStrikeOriginal** [comment]
I did exclude it, but to no avail. It still wont open.

**Comment by hellzerg** [comment]
Does it crash or anything?

**Comment by LuckyStrikeOriginal** [comment]
Yeah, directly from the release page. called "Optimizer-6.9".

**Comment by hellzerg** [comment]
Delete the folder Optimizer in ProgramData, and try to re-run the app.

**Comment by LuckyStrikeOriginal** [comment]
I did as you asked, but nothing. the log file didn't create. just the Optimizer JSON file which I presume isn't the log.

**Comment by hellzerg** [comment]
Check your Event Viewer for some .NET errors. You might find something in there.

**Comment by LuckyStrikeOriginal** [comment]
`Application: Optimizer-6.9.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemInfo.set_Attributes(System.IO.FileAttributes)
   at Optimizer.MainForm.chkReadOnly_CheckedChanged(System.Object, System.EventArgs)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(System.EventArgs)
   at Optimizer.ColoredCheckBox.OnCheckedChanged(System.EventArgs)
   at System.Windows.Forms.CheckBox.set_CheckState(System.Windows.Forms.CheckState)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean)
   at Optimizer.MainForm.GetHostsEntries()
   at Optimizer.MainForm..ctor()
   at Optimizer.Program.Main(System.String[])
`

**Comment by hellzerg** [comment]
Try this version, and tell me if it's okay.

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer.exe

**Comment by LuckyStrikeOriginal** [comment]
This one actually opened.

**Comment by hellzerg** [comment]
Send me the log file, I'm sure it now exists.

**Comment by LuckyStrikeOriginal** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/6279589/Optimizer.log)

**Comment by hellzerg** [comment]
Okay, please don't keep the file I've just sent you, delete it, when I'll release the v7.0 soon.

**Comment by hellzerg** [comment]
You can download v7.0 :D
