### ISSUE TITLE
windows search broken

### ISSUE THREAD

**Issue by MaCrO093** [hellzerg/optimizer#280]
whenever i search something that isnt the name of a file it comes up with "No results found for "_____""
also im using MSEdgeRedirect which worked before i used optimizer so im not sure if thats interfering with optimizer or a different cause
here is an example + what i have toggled
![image](https://user-images.githubusercontent.com/107784730/210300300-afffdbcd-4e5b-4c9b-904b-a0fbf93497d9.png)
![image](https://user-images.githubusercontent.com/107784730/210300314-f427c9dc-15ce-4497-8344-dbe9fa6b8184.png)
![image](https://user-images.githubusercontent.com/107784730/210300321-eb20c488-c4d4-4ae6-ba07-6e37ad6037b7.png)
did i toggle anything that may have caused this? the first time i did it i also disabled xbox live and game bar but after turning them off it still proceeded

**Comment by hellzerg** [comment]
@MaCrO093 
Try enabling Start Menu ads.

**Comment by MaCrO093** [comment]
> 

this worked thank you
