### ISSUE TITLE
fix this

### ISSUE THREAD

**Issue by baaannnaaannn** [hellzerg/optimizer#282]
![изображение](https://user-images.githubusercontent.com/55044749/211150829-65c69e0a-3c3c-47c2-9a51-55d6657c7ada.png)

**Comment by baaannnaaannn** [comment]
after tweaks  i got this

**Comment by baaannnaaannn** [comment]
![изображение](https://user-images.githubusercontent.com/55044749/211153862-819483a7-ca76-4678-8b6a-6efef5b6a07c.png)

**Comment by baaannnaaannn** [comment]
translated image

**Comment by baaannnaaannn** [comment]
https://www.youtube.com/watch?v=4ea6t0m-FNs
https://www.youtube.com/watch?v=85Lf4q2cNUw

**Comment by hellzerg** [comment]
Install .NET framework 4.8 runtime and it'll work.

**Comment by hellzerg** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer

**Comment by hellzerg** [comment]
Also, describe the problem more accurately. Any detail is useful.

**Comment by baaannnaaannn** [comment]
> 

i have this problem after restarting or starting my pc

**Comment by baaannnaaannn** [comment]
> ![изображение translated](https://user-images.githubusercontent.com/55044749/211160146-fe0e398f-0cb0-46b1-9dbe-8883d028b578.jpg)

and im update translated image

**Comment by baaannnaaannn** [comment]
> Install .NET framework 4.8 runtime and it'll work.

![изображение](https://user-images.githubusercontent.com/55044749/211160429-5ff228dc-e5b3-4468-b528-4b03d25b213e.png)

**Comment by hellzerg** [comment]
How this error relates to the optimizer?

**Comment by hellzerg** [comment]
This process is from AMD drivers.
Reinstall them and hopefully it will get fixed.

**Comment by baaannnaaannn** [comment]
> How this error relates to the optimizer?

i see this after reastarting pc after apply tweaks

**Comment by baaannnaaannn** [comment]
> This process is from AMD drivers. Reinstall them and hopefully it will get fixed.

its not fixed after reinstall
and its started showing error after using tweaker

**Comment by hellzerg** [comment]
Which options did you enable?

**Comment by baaannnaaannn** [comment]
> Which options did you enable?

after disabling tweaks the error disappeared

**Comment by baaannnaaannn** [comment]
> Which options did you enable?

I'm sorry, I already disabled everything (there is no error) and I don't want to enable it again

**Comment by hellzerg** [comment]
Okay, that is really strange.
