### ISSUE TITLE
Energy Options not opening

### ISSUE THREAD

**Issue by PhilippPaeslack** [hellzerg/optimizer#287]
Hi,
when i have the SensoryServices (? Sensordienste in german) deactivated, Energyoptions windows settings fails to start. When i select Energy Options from the Systems Settings board, the window crashes and disappears immediately. Turning back on and restarting, it works fine again.
{Win11Pro 22H2; Lenovo P16s AMD R7Pro 6850U}

**Comment by PhilippPaeslack** [comment]
Hi,
yes.

**Comment by hellzerg** [comment]
@PhilippPaeslack 

Show me a screenshot of the problem, so I can understand better.

**Comment by PhilippPaeslack** [comment]
When i enable this option right here:
<img width="314" alt="Screenshot 2023-01-31 153039" src="https://user-images.githubusercontent.com/123968129/215889866-f8b315e4-25e9-4d83-b25e-4137142a5c35.png">
I can not acces this settings page anymore:
<img width="954" alt="Screenshot 2023-01-31 153132" src="https://user-images.githubusercontent.com/123968129/215889861-461c7370-9a7f-4274-933e-962c2907d8f2.png">

**Comment by hellzerg** [comment]
Well, apparently your laptop's battery depends on a sensor service to display details about itself, so the sensor services must be running.

Just don't use this option and you are good.

@PhilippPaeslack
