### ISSUE TITLE
does not open optimizer 7.0

### ISSUE THREAD

**Issue by gnialXD** [hellzerg/optimizer#29]
I want to open optimizer 7.0, when opening it closes (seen in task manager)
![image](https://user-images.githubusercontent.com/82129025/114107534-d02c1b80-9896-11eb-815d-7a878453d851.png)
after a few seconds
![image](https://user-images.githubusercontent.com/82129025/114107577-e33eeb80-9896-11eb-9c4c-b69faf59f9bd.png)
lol

**Comment by hellzerg** [comment]
I need the log file in C:\ProgramData\Optimizer.

**Comment by gnialXD** [comment]
I can't find the log 
![image](https://user-images.githubusercontent.com/82129025/114229155-0f14ac80-993d-11eb-8c08-96ece90dc9c8.png)

**Comment by hellzerg** [comment]
Okay... try searching in Event Viewer for some .NET crash.

**Comment by gnialXD** [comment]
I found a .NET Runtime in the error box
![image](https://user-images.githubusercontent.com/82129025/114232000-d37be180-9940-11eb-87fd-6fc2f8df7c00.png)

**Comment by hellzerg** [comment]
I need details of the specific entry.

**Comment by gnialXD** [comment]
![image](https://user-images.githubusercontent.com/82129025/114232434-7fbdc800-9941-11eb-81b1-31e1655ed454.png)

**Comment by gnialXD** [comment]
Do you want me to put the details in English?

**Comment by hellzerg** [comment]
Yes.

**Comment by gnialXD** [comment]
Ok wait a moment

**Comment by hellzerg** [comment]
I think I fixed your problem. Try this and tell me if it's ok.

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/optimizer-exp.exe

**Comment by gnialXD** [comment]
oh ok ( I'm sorry I couldn't put the details in English)

**Comment by gnialXD** [comment]
it works thanks bro

**Comment by hellzerg** [comment]
Okay, delete the experimental build, and wait for v7.1.
I'm releasing it now.
