### ISSUE TITLE
Phone Link app stopped working

### ISSUE THREAD

**Issue by silvehh** [hellzerg/optimizer#290]
The android your phone link app says "This app has been blocked by your administrator", Only got this issue when I used the optimizer, I know it is one of the options I turned on I just dont know what, can someone help me?

**Comment by hellzerg** [comment]
Just turn off Enhance Privacy.
@silvehh

**Comment by silvehh** [comment]
> Just turn off Enhance Privacy. @silvehh

Thank you.
