### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by 10GO-dev** [hellzerg/optimizer#293]
Windows Defender detected Wacatac Trojan, deleted it and don't even let me download it anymore.
![image](https://user-images.githubusercontent.com/60454093/219967339-0c128852-7960-49f1-832a-47d4fafc7521.png)
![image](https://user-images.githubusercontent.com/60454093/219967392-eeba40c5-e25a-4d58-8a6d-bfdb71a35588.png)

**Comment by hellzerg** [comment]
Include the file in exclusions list, in Windows Security.
It's a false positive.

@10GO-dev

**Comment by Samael9999** [comment]
No parece muy seguro.
![Captura de pantalla (9)](https://user-images.githubusercontent.com/125828187/219971209-8ec904e3-7236-4777-9958-5d067730ea92.png)

**Comment by hellzerg** [comment]
It's just a false positive. The app is 100% open-source and it's established and trusted from Github since 2017.
@Samael9999

**Comment by DaSandman** [comment]
This is a trusted app.  Bitdefender Total Security finds it 100% clean.

**Comment by vadiscode** [comment]
Antivirus considers the optimizer a virus only because it contains in its resources ready-made batch files. You can also find them in the solution under "Optimizer/Resources/".
