### ISSUE TITLE
Optimizer 14.9 won't run on Windows 10 22H2

### ISSUE THREAD

**Issue by DaSandman** [hellzerg/optimizer#294]
Executing optimizer-14.9.exe throws a "This app can't run on your PC", which is a Windows 10 22H2 machine.  14.8 runs without issue.

**Comment by hellzerg** [comment]
Yes, try installing .NET 4.8 first.
If it persists not running, go to event viewer and find the error associated with Optimizer crash and send here the details.

@DaSandman
