### ISSUE TITLE
Optimizer not able to connect to internet .. problem also showing in older versions

### ISSUE THREAD

**Issue by Pro-cyber-byte** [hellzerg/optimizer#297]
Hey guys , been using optimizer for quite a while but ever since 14.xx versions rolled out , dunno why but the program is unable to connect to the internet on my machine for some reason .. initially it just stays on the fetching feed for a long time then a error pops saying "Unable to connect to remote server" and then opens the main window , on using any internet based utility like installing apps , it shows the same error , tried it on my other machine too .. is there something I'm not configuring properly on my PC or is this a bug because I don't see anyone else mentioning this issue .. If there is something I have to do to fix this please let me know ..

![Optimizer-14 9_NfTXfElP5j](https://user-images.githubusercontent.com/67885593/220333723-309913d2-d2ec-4777-a864-11f9062497ac.png)

**Comment by hellzerg** [comment]
Well, I will need the optimizer.log file located in C:\ProgramData\Optimizer

@Pro-cyber-byte

**Comment by Pro-cyber-byte** [comment]
Here's the link to the Optimizer folder located in C:\Program Data .. figured the whole folder might help more than just the log file ..

https://drive.google.com/file/d/1viLx3A0Jo4tlgC48yAxS8nYJjGWzr2R7/view?usp=share_link

**Comment by hellzerg** [comment]
Okay. Just check something for me.

If you click on the links below, can you access them or you receive an error message?

https://raw.githubusercontent.com/hellzerg/optimizer/master/images/feed.zip
https://raw.githubusercontent.com/hellzerg/optimizer/master/version.txt

@Pro-cyber-byte

**Comment by Pro-cyber-byte** [comment]
No actually .. cant access them , just keeps loading but never actually completely loads ..
Strange .. do you think this is problem from Windows Firewall ? 
Or is it something else , btw , I do you use a customized highly debloated version of windows that I created (and just to confirm that isnt just my version of windows , I installed stock Win 11 as well but the problem persisted) but other apps are able to connect to remote servers with no problems .. what do you think might be the issue , let me know ..

**Comment by hellzerg** [comment]
Something blocks requests to github.com.
It might be Windows firewall, your router or the other optimization scripts you run.

Ideally Optimizer should be used on clean Windows. Custom ISOs or already run similar apps might create conflicts.

If it is your router blocking you from accessing the links, you can try them on others devices/smartphones in the same network.

All in all, it's a networking issue.

@Pro-cyber-byte
