### ISSUE TITLE
Error TakeOwnershipExists

### ISSUE THREAD

**Issue by RotBiGo** [hellzerg/optimizer#298]
Windows 10 Pro - 22H2 (64-bit)
Optimizer 14.9 - .NET Framework 4.8 - Experimental build: False

[ERROR] [2/20/2023 1:00:36 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

[ERROR] [2/22/2023 12:51:08 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.Integrator.TakeOwnershipExists()

**Comment by hellzerg** [comment]
That's a business logic error.
If you don't experience any issue with the app, then it's okay.

@RotBiGo
