### ISSUE TITLE
Fake Copy of this Github Repository

### ISSUE THREAD

**Issue by Grenade-Inspector** [hellzerg/optimizer#299]
I don't know any other way of contacing you, but I saw this while searching around https://github.com/vinilolah09/Bes-Optimizer

**Comment by Grenade-Inspector** [comment]
Seems like the guy who did it, doesn't really care if someone finds out 
![image](https://user-images.githubusercontent.com/88556789/221334732-49b6173d-3408-4791-a3ab-2938791c21e0.png)

**Comment by hellzerg** [comment]
@Grenade-Inspector 

Unfortunately, there's not much we can do about this.
