### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by mendel3** [hellzerg/optimizer#3]
Can you add some more detailed descriptions in the readme to some of the vague options, such as Enable Preformance Tweaks, and also add some warnings to things that might break something? Also, what does Disable network throttling exactly do?
Thanks!

**Comment by hellzerg** [comment]
Performance Tweaks are a collection of several registry tweaks. You can find every tweak and its use here:

https://www.askvg.com/collection-of-registry-tweaks-for-windows-7/

Also, you can take a look about what Network Throttling is here:

https://www.speedguide.net/articles/gaming-tweaks-5812

**Comment by LinuxOnTheDesktop** [comment]
I think that the reply above should be added to the ReadMe.
