### ISSUE TITLE
starting from version 7.2 application dont start

### ISSUE THREAD

**Issue by rulezzzzz** [hellzerg/optimizer#30]
Приложение: Optimizer-7.6.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.FormatException
   в System.Number.ParseSingle(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   в Optimizer.MainForm.CheckForUpdate(Boolean)
   в Optimizer.MainForm..ctor()
   в Optimizer.Program.Main(System.String[])

**Comment by hellzerg** [comment]
Can you give me the log file at C:\ProgramData\Optimizer ?

**Comment by rulezzzzz** [comment]
it not created when i start any version larger than 7.1

**Comment by rulezzzzz** [comment]
but at event viewer i am find error that send at first comment

**Comment by rulezzzzz** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/6316389/Optimizer.log)
 this one from 7.1

**Comment by hellzerg** [comment]
Try checking for update in Options, with v7.1.

**Comment by rulezzzzz** [comment]
![image](https://user-images.githubusercontent.com/52334210/114840954-00684280-9de0-11eb-9be7-376005aee0bb.png)

**Comment by rulezzzzz** [comment]
input string has wrong format

**Comment by rulezzzzz** [comment]
looks as localization issue ... after i chane display lang to enlish , all start work as a charm

**Comment by hellzerg** [comment]
Okay, I will fix it, but I need you to test it.

**Comment by hellzerg** [comment]
This should work.

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-test.exe

**Comment by rulezzzzz** [comment]
still crash when display lang set to russian

**Comment by hellzerg** [comment]
That one?

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-Test2.exe

**Comment by rulezzzzz** [comment]
moreover , it is regional formats ... when display lang is russian, but regional formats setted as English(USA), all is work

**Comment by rulezzzzz** [comment]
the same ...

**Comment by hellzerg** [comment]
This...

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-Test3.exe

**Comment by rulezzzzz** [comment]
still crash

**Comment by hellzerg** [comment]
It should display a number before crashing.

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-Test4.exe

**Comment by rulezzzzz** [comment]
the problem with the separator of the integer and fractional parts of a number, in Russian it is a comma ... as soon as I put a dot in the setting, the application starts

**Comment by rulezzzzz** [comment]
![image](https://user-images.githubusercontent.com/52334210/114854077-1d574280-9ded-11eb-9d24-29dc5d57c53e.png)

**Comment by rulezzzzz** [comment]
think that dot in this variable must be string and not part of number

**Comment by rulezzzzz** [comment]
or the entire variable must be strictly reduced to be a string

**Comment by hellzerg** [comment]
Tell me it's ok..

https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-Test5.exe

**Comment by rulezzzzz** [comment]
crash

**Comment by hellzerg** [comment]
https://raw.githubusercontent.com/hellzerg/optimizer/master/experiments/Optimizer-Test6.exe

**Comment by rulezzzzz** [comment]
looks as ok

**Comment by hellzerg** [comment]
working?

**Comment by rulezzzzz** [comment]
yes

**Comment by hellzerg** [comment]
Wait for the next update, soon.
