### ISSUE TITLE
Download of 14.9 is broken

### ISSUE THREAD

**Issue by MPC7500** [hellzerg/optimizer#301]
When I download 14.9 two files appear:

- Optimizer-14.9.exe (0KB)
- Optimizer-14.4OGqNW8z.9(1).exe.part (2.146KB)

I need to rename the part file. Then Optimizer can be started.

I tried this with two PCs with different operating systems. Same behavior.
Download of 14.8 generates only one (exe) file. As expected.

**Comment by hellzerg** [comment]
@MPC7500 

Where did you download the app from?
That seems to be a virus you downloaded there, from untrusted source.

**Comment by MPC7500** [comment]
This is the URL:
https://github.com/hellzerg/optimizer/releases/download/14.9/Optimizer-14.9.exe

Tried with Windows11 and MacOS X.
![Bildschirmfoto 2023-03-02 um 20 02 39](https://user-images.githubusercontent.com/70668364/222526510-96a038e4-5422-441b-9d91-85260a43d90b.jpg)

**Comment by hellzerg** [comment]
I think your browser is unable to complete the download. Maybe the Windows smartscreen or some antivirus interferes with the download process.

@MPC7500

**Comment by MPC7500** [comment]
Yes. Weird. That's why I have tried MacOS X as well. I scanned the part-file with Virustotal. This is the result
![Bildschirmfoto 2023-03-02 um 20 22 46](https://user-images.githubusercontent.com/70668364/222531506-b9dc7857-d288-4228-bd59-f714f46aa5ba.jpg)

Only these three vendors are reporting a Troja, BTW.

You could close the issue since it isn't really an issue. Downloading 14.8 works without an issue.

**Comment by hellzerg** [comment]
I will try it on my devices too. But it is unlikely that the issue will happen. Something else is interfering in your case.

**Comment by MPC7500** [comment]
I just saw on the Firefox pull-down Downloads menu the message:
"This File is not commonly downloaded"

I could click on "allow download", then it changes from .part to .exe and I can start the application.
It's some sort of security feature of Firefox (at least).

Tried now Safari on MacOS, and it worked, OOTB.
Tomorrow, I will also try Microsoft Edge on Windows 11.

If you are interested in my result, I can post it. If not, feel free to close the issue.
I just want you to know that this problem can occur. For whatever reason. 
And now I know how to solve it.

Sorry for the trouble and good work, BTW. I appreciate it!

**Comment by hellzerg** [comment]
@MPC7500 

So, what's the result of your tests?

**Comment by MPC7500** [comment]
Sorry, sorry, sorry. I totally forgot ...

With Microsoft Edge, it works the other way around. It asks me in advance if I really want to download it. Because the file could be dangerous.

So it's not a Microsoft security feature, but a browser security feature.
This effects only 14.9, not 14.8.

**Comment by hellzerg** [comment]
Okay, I got it.
Thanks for your report, anyway.

The app has been around the internet for at least a solid 5 years. It's completely open source and trusted.

I don't understand why the browsers security features
