### ISSUE TITLE
Can't disable classic ribbon in explorer

### ISSUE THREAD

**Issue by ech0ing** [hellzerg/optimizer#302]
![image](https://user-images.githubusercontent.com/61727188/223100873-ef698a75-ef6d-4777-8be5-7d4adf2df675.png)
I try to close this option, but the button is still open when I restart my computer.

Although the button is enabled, the explorer ribbon is still the new ribbon for Windows 11.

**Comment by hellzerg** [comment]
I will examine this, I suspect it broke with latest Windows 11 updates.

@ech0ing

**Comment by ech0ing** [comment]
> 

Yes, I am so sorry to forget to paste my os version.
OS Version: Windows 11 22H2 22621.1344

**Comment by hellzerg** [comment]
Unfortunately, 22h2 build version stopped supporting the classic ribbon from Windows 10.

So, nothing can be done about this.
I will remove the functionality from my app.
