### ISSUE TITLE
backup restore config

### ISSUE THREAD

**Issue by MadhavMendpara** [hellzerg/optimizer#309]
its actually a request not issue 

if there is a backup and restore option that will restore config from the backup file like o&oshup would be good for saving some time for user.

![Screenshot (1)](https://user-images.githubusercontent.com/41751430/226404012-a034ade8-cd11-414f-8b02-47aba690f348.png)

**Comment by hellzerg** [comment]
You can use conf files to achieve the same actually. I know it's not the friendliest way, but it works and it is reusable.

@MadhavMendpara

**Comment by MadhavMendpara** [comment]
got it has to copy the config folder.

**Comment by hellzerg** [comment]
No, no, that's not correct. Copying the config folder will not apply the settings. It's just a storage. 

Take a look here: 
https://github.com/hellzerg/optimizer/blob/master/CONFS.md#you-can-execute-optimizer-silently-applying-tweaks-according-to-a-configuration-file

@MadhavMendpara

**Comment by MadhavMendpara** [comment]
tnx can use this.

**Comment by hellzerg** [comment]
@MadhavMendpara Thanks, will include it in next version.
