### ISSUE TITLE
Optimizer 7.7 crashes at start

### ISSUE THREAD

**Issue by linuxjourney** [hellzerg/optimizer#31]
This is what came up in Event Viewer for .NET crashes.

--
Application: Optimizer-7.7.exe Framework Version: v4.0.30319 Description: The  process was terminated due to an unhandled exception. Exception Info:  System.IO.DirectoryNotFoundException at System.IO.__Error.WinIOError(Int32,  System.String) at System.IO.FileSystemEnumerableIterator`1[[System.__Canon,  mscorlib, Version=4.0.0.0, Culture=neutral,  PublicKeyToken=b77a5c561934e089]].CommonInit() at  System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib,  Version=4.0.0.0, Culture=neutral,  PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String,  System.String, System.IO.SearchOption,  System.IO.SearchResultHandler`1<System.__Canon>, Boolean) at  System.IO.Directory.GetFiles(System.String, System.String,  System.IO.SearchOption) at Optimizer.Utilities.GetStartupItems() at  Optimizer.MainForm.GetStartupItems() at Optimizer.MainForm..ctor() at  Optimizer.Program.Main(System.String[])
--

**Comment by hellzerg** [comment]
try v7.8. It should be okay now.

https://github.com/hellzerg/optimizer/releases

**Comment by linuxjourney** [comment]
Works, thanks for the help.
