### ISSUE TITLE
Bad Romanian Translation and untranslated options

### ISSUE THREAD

**Issue by DefaultUser9148** [hellzerg/optimizer#312]
The Romanian translation is bad and not accurate, some options arent even translated and some dont make sense. #

**Comment by hellzerg** [comment]
@DefaultUser9148 

Do you want to contribute and make the corrections for Romanian language?

**Comment by DefaultUser9148** [comment]
Sure, i'd like to.

@hellzerg

**Comment by hellzerg** [comment]
@DefaultUser9148 

Cool, I am waiting for your Romanian translation update!

**Comment by DefaultUser9148** [comment]
Uhh.. What? What do i do to make the update?

**Comment by hellzerg** [comment]
You can examine this file and edit it accordingly, then send the new one to me.

https://raw.githubusercontent.com/hellzerg/optimizer/master/Optimizer/Resources/i18n/RO.json

@DefaultUser9148

**Comment by DefaultUser9148** [comment]
Thank you @hellzerg , I will make them right because they were made with Google Translate and not by a native Romanian. I will get them to you in less than like 3 days... I hope!

**Comment by DefaultUser9148** [comment]
**Alright**! @hellzerg , Here is the improved translation file, I didnt use Google Translate like the first person who made the translation. You can open it if u wanna check it! 
[RO.txt](https://github.com/hellzerg/optimizer/files/11071717/RO.txt)

**Comment by hellzerg** [comment]
@DefaultUser9148 
Okay, I will need you to translate some more for the next version.

Disable Edge Discover
Disable Edge Telemetry
Removes Discover Bar in Edge.
Disables SmartScreen, Spotlight and Telemetry services in Edge.
Advanced
Enable Detailed Login Screen

**Comment by DefaultUser9148** [comment]
Okay,, Here:
Dezactiveaza Descoperirea pe Edge
Dezactiveaza Telemetria pentru Edge
Scoate Bara de Descoperire din Edge
Dezactiveaza SmartScreen, reflectoarele si Serviciile de Telemetrie din Edge
Avansat
Activeaza Ecranul Detaliat de conectare.

The new update seems interesting, i cant wait to fully eliminate edge!
