### ISSUE TITLE
How can I totally remove this program from my computer?

### ISSUE THREAD

**Issue by JaviruloNT** [hellzerg/optimizer#315]
Title

**Comment by hellzerg** [comment]
The app is portable, meaning you just delete it and it's done.

But, before this, reset every option.

@JaviruloNT

**Comment by Zabooby** [comment]
> The app is portable, meaning you just delete it and it's done.
> 
> But, before this, reset every option.
> 
> @JaviruloNT

Related question, once I have set my preferred settings can I delete the .exe knowing the changes will persist?

**Comment by hellzerg** [comment]
@Zabooby Yes, the options are persistent.
But it's good to have the app locally in case you need to turn off/on any options again.
