### ISSUE TITLE
chrome malware 

### ISSUE THREAD

**Issue by MadhavMendpara** [hellzerg/optimizer#319]
after applying to disable google chrome telemetry option this thing appeared I'm not sure if is this from the optimizer or some malware.
![image](https://user-images.githubusercontent.com/41751430/230170649-28be974a-8fad-428d-b6c1-dd672244f2e4.png)

**Comment by hellzerg** [comment]
@MadhavMendpara 
It's from Optimizer. You can go to chrome://policy and examine the policies enabled by the app.
