### ISSUE TITLE
Windows defender reports trojan

### ISSUE THREAD

**Issue by zedstar** [hellzerg/optimizer#32]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSpursint.F!cl&threatid=2147717281 

Trojan:Win32/Spursint.F!cl

**Comment by hellzerg** [comment]
It's a false positive obviously.

**Comment by zedstar** [comment]
well other similar onens dont report this?

Debotnet
Privatezilla

why optimizer?

**Comment by hellzerg** [comment]
I don't know, I filed a false positive report several days ago to Microsoft, but hasn't changed anything.
