### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by switchy7** [hellzerg/optimizer#320]
does iit works on windows 11?

**Comment by hellzerg** [comment]
@switchy7 Yes, it's working.

**Comment by switchy7** [comment]
Please tell me how can i delete option that disables AV or so cause virustotal is saying there is a virus: 

https://www.virustotal.com/gui/file/cc81be39adcb8ea105c75106084f7b6809014aede70b52fd7eb2f41d5c7c288c

why is that?

**Comment by hellzerg** [comment]
@switchy7 they are all false positives. The app is 100% clean and secure to use.

**Comment by switchy7** [comment]
i knowi guess it is because it has options to disable smart screen or etc... how can i fix it... i need to be clean on the virus total too
