### ISSUE TITLE
Unable To Connect To the remote Server

### ISSUE THREAD

**Issue by FranklinOP-IND** [hellzerg/optimizer#321]
![image](https://user-images.githubusercontent.com/64591314/230873594-c0324c22-c3f5-40fc-884a-983a882c8cd5.png)
can't enable Windwos update

**Comment by hellzerg** [comment]
@FranklinOP-IND 

I need the optimizer.log file in C:\ProgramData\Optimizer

**Comment by FranklinOP-IND** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/11189473/Optimizer.log)

**Comment by FranklinOP-IND** [comment]
> 

![image](https://user-images.githubusercontent.com/64591314/230876073-13aae488-7770-40f0-8049-0439948f80af.png)
how can  i enable windwos update !!

**Comment by hellzerg** [comment]
The app is not opening?
@FranklinOP-IND

**Comment by hellzerg** [comment]
I cannot understand what you are saying

@FranklinOP-IND
