### ISSUE TITLE
Camera Disabled

### ISSUE THREAD

**Issue by johnfromstatefarm** [hellzerg/optimizer#326]
Hello, I was using your app, and some setting seemed to have disabled the camera entirely. I had deleted the Optimizer leftover folder in ProgramData, so none of my toggles saved. What exactly does your app do when you select Enhance Privacy or disable Telemetry Services, or similar? Does it mess with gpedit and registry? I can't get my laptop camera to work, but it works on a live usb.

**Comment by hellzerg** [comment]
Did you try turning off Enhance privacy and disable sensor services?

@johnfromstatefarm

**Comment by johnfromstatefarm** [comment]
> Did you try turning off Enhance privacy and disable sensor services?
> 
> @johnfromstatefarm

Yes, I have tried to turn back on and off the enhance privacy setting. Once again, the toggles did not save once I deleted the Optimizer folder from ProgramData to clear the reninant.

**Comment by hellzerg** [comment]
You  don't delete that folder. Just do the changes. Also go to settings privacy and check for camera section

@johnfromstatefarm

**Comment by johnfromstatefarm** [comment]
> You don't delete that folder. Just do the changes inside the app. Also go to settings privacy and check for camera section
> 
> @johnfromstatefarm

I am saying I had deleted it in the past, and now noticed my camera was not working.

I have checked all of that, this is the error code I receive: 0xA00F4244
The physical camera button is turned on, and camera works on a live boot.

**Comment by hellzerg** [comment]
Where do you receive this code?
Windows version?
Also what's the settings in Camera section in Settings?

@johnfromstatefarm
