### ISSUE TITLE
Silent option doesn't work

### ISSUE THREAD

**Issue by fa1rid** [hellzerg/optimizer#329]
It's not affecting any settings and there is no output from cmd.

![image](https://user-images.githubusercontent.com/6115961/233972877-5d08b81d-1435-4a8d-acb2-32140c2885fd.png)

**Comment by hellzerg** [comment]
If you open the app after running the script, the options you selected as true is not enabled?

@fa1rid

**Comment by fa1rid** [comment]
That's correct! They are not getting enabled or disabled when I open the GUI app.

**Comment by hellzerg** [comment]
@fa1rid 

First, does windowsversion in conf matches the actual version?

**Comment by fa1rid** [comment]
Yes, I'm using Windows 10.

**Comment by hellzerg** [comment]
Ok, I should check it.
@fa1rid

**Comment by hellzerg** [comment]
@fa1rid Hi

Finally I noticed that the documentation on this is old.

You should pass /config=<FILE>

Sorry for the inconvenience
