### ISSUE TITLE
Ping seems not working

### ISSUE THREAD

**Issue by radiolondra** [hellzerg/optimizer#33]
After clicking the Ping button it seems it's doing nothing and the button is disabled.
![optimizer](https://user-images.githubusercontent.com/20070559/115271915-207c6680-a13e-11eb-9d2d-c0ae2d941c9e.png)

**Comment by radiolondra** [comment]
![optimizer1](https://user-images.githubusercontent.com/20070559/115348347-d1244d80-a1b2-11eb-8963-211a16efcc13.png)

**Comment by hellzerg** [comment]
Did you try another IP, like 8.8.8.8 in app?

**Comment by NameLord** [comment]
For me it works really great the Pinger.
![image](https://user-images.githubusercontent.com/27507408/115532927-eb3b5a00-a29e-11eb-98a0-504756e9d26d.png)

**Comment by hellzerg** [comment]
Have you checked your internet connection?
