### ISSUE TITLE
virustotal and chrome flags optimizer as trojan

### ISSUE THREAD

**Issue by rhtj8** [hellzerg/optimizer#330]
that's pretty much it
![Screenshot 2023-04-27 175314](https://user-images.githubusercontent.com/131987466/234901440-ca128e7b-0a6e-4b24-9672-fc2b4541063c.png)

**Comment by rhtj8** [comment]
vt link
https://www.virustotal.com/gui/file/b4cddb66686bc6998609e824a173eb4fa0b5ac154845c0b47df4bd3af0fb558b

**Comment by hellzerg** [comment]
@rhtj8 It's false positive.
