### ISSUE TITLE
Welcome screen taking a longer period of time

### ISSUE THREAD

**Issue by vnzoliveira** [hellzerg/optimizer#332]
Hey, i'm having this issue where after applying some options in the optimizer, everytime i boot my pc and windows starts up, after login the welcome loading till desktop pops up is taking about 3-4 seconds longer than before.

Notes: I applied the settings on a brand new gaming laptop, SSD, the optimization was the first thing i did, no additional software was downloaded, neither any heavy programs were installed.

**Comment by hellzerg** [comment]
Hi,

Yes, the slightly longer time on the login welcome screen may be related to a feature of Windows called Fast Startup. It's in the advanced power options view in Control panel.

This feature is disabled if you clicked on Disable Hibernation in Optimizer.

You can revert this option, restart and change Fast Startup to enabled

@vnzoliveira

**Comment by vnzoliveira** [comment]
Thanks for the answer, I'll do that
