### ISSUE TITLE
Hi dear deadmoon - Disable Privacy Options

### ISSUE THREAD

**Issue by FreddyKaza** [hellzerg/optimizer#333]
Although you are advised not to use the Disable Privacy Options function if I'm using win10 build 1809 or greater, I ended up disabling the function, and now some audio applications need it activated. I disabled it through Optmier version 6.9. Is there any way to enable the privacy functions again without having to reinstall widows? If so, I'll be very grateful, as my system is quite complicated to tune. Thanks in advance, Fredy.

**Comment by hellzerg** [comment]
Hi. First of all v6.9 is very very old version the the app. You should not use any version below v13.0 really. 

Anyway, you should download the latest version and try to reset the option to false from the new. It is the best method to reset it the right way.

@FreddyKaza

**Comment by FreddyKaza** [comment]
Hi many thanks for repy!  in the new versions I belive there is no Disable Privacy Options anymore

**Comment by hellzerg** [comment]
It's renamed to Enhance Privacy 
@FreddyKaza

**Comment by FreddyKaza** [comment]
Maybe I'll need to reistall OS since reset option still give me the message over most Privacy itenms: * Some of these setings are hiddem or mangaged by tour org.

**Comment by hellzerg** [comment]
Which setting needs to be reset so your program has proper access to it?

@FreddyKaza

**Comment by FreddyKaza** [comment]
I am tryaing to use an VST plugin that relies on a backgraund task. it is the 'waves head tracker'
 that works in the back ground captures images from a wencam and forwards it to the plugin in the daw

**Comment by hellzerg** [comment]
Which option do you need to enable?
@FreddyKaza

**Comment by FreddyKaza** [comment]
![privacy](https://user-images.githubusercontent.com/132179074/235748659-6ea1090a-a729-4948-8cec-cef92a8934d6.JPG)

Inside PRIVACY - App Permissions - Camera  ( * some of these settingsor managed by your organiztion) includded Allow access to the camera o this devece,  Allow apps to access your camera, choose which microsoft store can access your camera...

I can't caccess overall Privacy settings https://drive.google.com/file/d/1yAKOiALgGY8Am6cPDvTEQulBo6OvigCi/view?usp=share_link

**Comment by hellzerg** [comment]
Ok I will look into it
@FreddyKaza

**Comment by FreddyKaza** [comment]
I tried some tweaks at GPEDIT.MSC with no sucssess... Mr @hellzerg

**Comment by hellzerg** [comment]
@FreddyKaza 

Look this link and check the registry keys
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.AppPrivacy::LetAppsAccessCamera

You might need to delete those keys

**Comment by FreddyKaza** [comment]
> @FreddyKaza
> 
> Look this link and check the registry keys https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.AppPrivacy::LetAppsAccessCamera
> 
> You might need to delete those keys

Thank you very much for your effort and support. I also do PC maintenance here in Brazil and I will always share your tool. Best Regards! It's working now.
![nx](https://user-images.githubusercontent.com/132179074/235862600-e706f8b2-08f8-44ba-9c29-4c68b7f2aac3.JPG)

**Comment by hellzerg** [comment]
Nice. I'll try to improve my code based on that for future releases.
@FreddyKaza

**Comment by hellzerg** [comment]
Nice, nice!
