### ISSUE TITLE
Important Issue with Win 8.1 Network

### ISSUE THREAD

**Issue by NameLord** [hellzerg/optimizer#34]
Without Optimizer The wifi works perfectly connecting , working etc etc etc
BUT with Optimizer Has some wierd things. Like when i start the pc on i need to wait up to 5+ Minutes to wifi work , connect and etc etc etc.

**Comment by hellzerg** [comment]
Switch Disable Network Throtting to OFF and see if the problem remains.

**Comment by gliczide** [comment]
and i can't run up optimizer since no wifi. 
version: windows 10 21h1
