### ISSUE TITLE
can't show all the options in windows11 pro 22H2

### ISSUE THREAD

**Issue by derek7087** [hellzerg/optimizer#340]
dear sir,seems that some options can't show completely in windows 11 pro 22H2
![PIC-230514115101](https://github.com/hellzerg/optimizer/assets/64677036/b0230d64-a23b-444c-9911-5e505ac9a232)

**Comment by hellzerg** [comment]
@derek7087 did you solve it?

**Comment by derek7087** [comment]
Thanks for following up

I think that issue only happens when I connect a second monitor(1920*1680) to my notebook so it's not that big of a deal.



 
From: deadmoon
Date: 2023-05-14 14:20
To: hellzerg/optimizer
CC: derek7087; Mention
Subject: Re: [hellzerg/optimizer] can't show all the options in windows11 pro 22H2 (Issue #340)
@derek7087 did you solve it?
