### ISSUE TITLE
Restore Windows 10 Photo Viewer

### ISSUE THREAD

**Issue by robertgro** [hellzerg/optimizer#342]
According to this article https://www.techradar.com/how-to/how-to-restore-and-use-windows-photo-viewer-in-windows-10 there is .reg file from bleepingcomputer which allows you to restore the windows 10 photo viewer in case the default photos app doesn't fit someone's needs. Would be a nice addition in my opinion if you could include this in a future version of this app!

**Comment by hellzerg** [comment]
Okay, will be incorporated.
@robertgro

**Comment by robertgro** [comment]
Thank you. I appreciate your efforts! @hellzerg

**Comment by hellzerg** [comment]
Feature added in v15.4.
Please, update to the latest version to use it.
@robertgro

**Comment by robertgro** [comment]
Thank you @hellzerg. I'll update all of my clients ASAP.
