### ISSUE TITLE
建议点击重启后,有个提醒框,确定是否重启

### ISSUE THREAD

**Issue by sysfn339** [hellzerg/optimizer#343]
![666](https://github.com/hellzerg/optimizer/assets/71576119/8142f648-c41f-4a66-83ee-e00e66aa6c7b)

**Comment by abbaccadd0** [comment]
> I don't understand what's the problem? @sysfn339

He means to add a second confirmation for the "Restart" button.

**Comment by hellzerg** [comment]
I might add a confirmation dialog in later versions.

**Comment by hellzerg** [comment]
Fixed in v15.5. Please update your app.
