### ISSUE TITLE
Why does VirusTotal show a virus?

### ISSUE THREAD

**Issue by VkProfi** [hellzerg/optimizer#344]
![image](https://github.com/hellzerg/optimizer/assets/112758911/266bf68e-50d9-4e05-acfd-c11149f7891a)
The last version, downloading for GitHub

https://www.virustotal.com/gui/file/0f225c69528a10e2e4616bf00cb5164b8a010f630d774ac2989916d477cf75fd?nocache=1

**Comment by VkProfi** [comment]
The last version

**Comment by hellzerg** [comment]
@VkProfi False positive.

**Comment by MezMedicianoIntelligentMedia** [comment]
WIndows 11 Defender is saying it is a serious ransomware virus

**Comment by hellzerg** [comment]
If it was random ware now you're files would be encrypted and gone. 
It's false positive.
@MezMedicianoIntelligentMedia
