### ISSUE TITLE
Disable windows tips and tricks

### ISSUE THREAD

**Issue by Lachine1** [hellzerg/optimizer#346]
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
SystemPaneSuggestionsEnabled, SubscribedContent-338387Enabled, SubscribedContent-338388Enabled
all to 0

**Comment by hellzerg** [comment]
This is already done. Just use the Disable start menu ads toggle.

@Lachine1
