### ISSUE TITLE
[Add feature] Disable Microsoft Device Association Root Enumerator

### ISSUE THREAD

**Issue by kalimaenergy** [hellzerg/optimizer#347]
Hello,

Can be great if we can disable this driver with your app :)

https://windowsreport.com/microsoft-rras-root-enumerator/

Many user disable that for avoid stuttering
https://us.forums.blizzard.com/en/d4/t/stuttering-still-happening/24182/26?page=2

THank you

**Comment by hellzerg** [comment]
I think it's not possible to properly disable a device using C#
