### ISSUE TITLE
Windows 22H2 update issue

### ISSUE THREAD

**Issue by DRYN07** [hellzerg/optimizer#348]
I have an update issue with a freshly installed latest Win11 22H2.

I usually disable Win update in the optimizer (this download button for manual action is amazing) but let the store apps be enabled. But after 22H2, the store app updates are also blocked and I get the error code 0x80004002. I would appreciate any idea to solve this :/

Also, could you tell me please how you made this update preference? I mean to disable automation of the updates but let the system search for them and be able to download them if the user interacts. I can't find any reg/policy or any other solution for this, only in this app. I would really appreciate it.

**Comment by DRYN07** [comment]
@hellzerg 
Yes, it is on. It's weird because on my other machine which has no fresh install, it is working... Can I read somewhere what the "Windows 11" tab options modify to check on the two machines (gpedit/regedit/hosts etc)? I checked "Windows update" in both of gpedit and regedit but I don't find any changes when I change options.

What I am most curious that what options make Windows update only manual and let the store be enabled.  

Thanks :)

**Comment by hellzerg** [comment]
@DRYN07 

Maybe you can try checking/enabling Delivery Optimization service and check if Store updates are restored

**Comment by hellzerg** [comment]
@DRYN07 any updates on the matter?

**Comment by DRYN07** [comment]
Well on my new machine, it is working, but I did not find the cause of the "broken" one :/ 

However, I made that Windows iso with NTlite so I may have messed up something there.

**Comment by hellzerg** [comment]
Yes it's possible. On clean installed Windows 11 it works fine? @DRYN07

**Comment by luke-beep** [comment]
> Yes it's possible. On clean installed Windows 11 it works fine? @DRYN07

Yes, it works fine on stock Windows 11. I tried it on a Windows 11 23H2 image, worked there as well.

**Comment by hellzerg** [comment]
So, the issue originates from custom ISO.

**Comment by StrangeCorvus** [comment]
I'm currently having the same issue, I downloaded the tool a few weeks ago, works wonders! But now the microsoft store and minecraft bedrock no longer work. The Microsoft store gives me a loading error, and minecraft bedrock doesn't allow me to login with my microsoft account. I reverted all the options I had selected and even made a complete reboot on the store application, but nothing.

**Comment by hellzerg** [comment]
@StrangeCorvus Try using thr built in troubleshooters. Run the one related to Windows update.

**Comment by StrangeCorvus** [comment]
@hellzerg The store app is up to date, and so is my Windows, I have no updates available. I already ran the troubleshooting but it doesn't detect anything to be out of the ordinary.

**Comment by hellzerg** [comment]
Did you try any of that?
https://support.microsoft.com/en-us/account-billing/microsoft-store-doesn-t-open-126a875d-8b72-def1-0af6-d325276a058b

@StrangeCorvus

**Comment by StrangeCorvus** [comment]
@hellzerg Yes I have. It didn't work. I was able to get Minecraft back working by disabling the "disable Xbox live" option (or something similar, I forgot what the option was called), but the store still refuses to work.
