### ISSUE TITLE
my fingerprint was disabled after using the optimizer and idk how to fixed pls help

### ISSUE THREAD

**Issue by jdemanuel7** [hellzerg/optimizer#349]

**Comment by hellzerg** [comment]
@jdemanuel7 

Try resetting Sensor services and Enhance Privacy

**Comment by abhith** [comment]
Reverting "Enhance Privacy" enabled Facial Recognition and Fingerprint but both didn't work with the previous set of data, so had to re-enroll on each service.

**Comment by hellzerg** [comment]
So, problem resolved?

**Comment by abhith** [comment]
> So, problem resolved?

Yes
