### ISSUE TITLE
ET JA3 Hash - Possible Malware - Various Eitest

### ISSUE THREAD

**Issue by renz-dev** [hellzerg/optimizer#35]
Saw this on VT.
https://www.virustotal.com/gui/file/0f1dcfa65ec193aebddef34287635c01e06390baddee98addfe6742bd6734ee4/detection

**Comment by hellzerg** [comment]
It's a false positive, obviously.

**Comment by Remo** [comment]
In case anyone wonders, Microsoft also complained today )-: 

![image](https://user-images.githubusercontent.com/129864/121316797-f9eed680-c909-11eb-8e9d-e63e9c56c1ce.png)

**Comment by hellzerg** [comment]
Microsoft will forever complain until you pay to sign your app with a valid signature.
