### ISSUE TITLE
Startup Items

### ISSUE THREAD

**Issue by baldsealion** [hellzerg/optimizer#350]
Startup item deletion is very buggy.

Go to delete and it removes the item below the one that is checked.

**Comment by baldsealion** [comment]
Actually it's not even consistent with that either, sometimes it will delete an entry that is 2 rows below the one that is checked. Very inconsistent.

**Comment by hellzerg** [comment]
@baldsealion Are you sure you have the latest list by using Refresh? Also, you need to check before you delete.
