### ISSUE TITLE
Unclear on how to access the Advanced tab with /unsafe

### ISSUE THREAD

**Issue by grimreaperT** [hellzerg/optimizer#351]

**Comment by hellzerg** [comment]
@grimreaperT 

You just use the cmd to execute the file with /unsafe command.

**Comment by grimreaperT** [comment]
oh so you just go into the cmd prompt and execute optimizer with /unsafe?

**Comment by grimreaperT** [comment]
if that's the case can you give me the command so i can put it into the prompt without messing up anything

**Comment by hellzerg** [comment]
@grimreaperT 

You need basic knowledge of how command prompt works on Windows.
The basic idea is that you open command prompt, navigate with it to where your app is, and execute it with /unsafe parameter.

https://www.wikihow.com/Run-a-Program-on-Command-Prompt

**Comment by grimreaperT** [comment]
alright, thanks
