### ISSUE TITLE
 Detected on Virus Total: W32.AIDetectMalware, Trojan.BAT.KillAV, MachineLearning/Anomalous.97%, Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by jebarpg** [hellzerg/optimizer#355]
https://www.virustotal.com/gui/file/b62ab6e0fabfc3e58b7af5777fb4bdbc5fdd807f4a44f7cf91dbf9518721f2b1

These are some major issues that need to be addressed.

**Comment by hellzerg** [comment]
These are all false positives. Because my app has functions that disable Windows Defender. Totally predictable.

**Comment by hellzerg** [comment]
https://github.com/hellzerg/optimizer/blob/master/Optimizer/Resources/Scripts/DisableDefenderSafeMode1903Plus.bat

@jebarpg
