### ISSUE TITLE
Slower Boot Time

### ISSUE THREAD

**Issue by blazeoflate** [hellzerg/optimizer#356]
After using Optimizer, my boot time shot up from aroudn 30s to around 140s. However my shut down went down from about 20s to 3s.

I turned off all optimisations but the problem still persists. **Disable TMP Check** was unable to disabled at first at came up with an error although i am currently unable to reproduce this.

Are there any particualr settings that could be the direct cause?

**Comment by hellzerg** [comment]
Fast Startup in Power Options @blazeoflate

**Comment by hellzerg** [comment]
It may be more slow to start (marginally though) but the PC is more responsive overall after booting.

**Comment by blazeoflate** [comment]
> Fast Startup in Power Options @blazeoflate

That doesn't appear to be an option in my Power Options. I am using an SSD as well.

![image](https://github.com/hellzerg/optimizer/assets/136813548/9d487b7b-8cd8-4aaa-b5fd-03953fa05471)

**Comment by hellzerg** [comment]
Click on "Choose what the power buttons do".
On the left pane.
@blazeoflate

**Comment by blazeoflate** [comment]
> Click on "Choose what the power buttons do". On the left pane. @blazeoflate

I get these options but nothing about a Fast Startup.
![image](https://github.com/hellzerg/optimizer/assets/136813548/322da581-4c6b-4be0-abc3-a1feb5cb119e)

**Comment by blazeoflate** [comment]
Okay had to renable hibernate in Command Prompt but it is enabled now. 

Now start up from after shuting down is back to 7s, but restarting is still the same. Which kinda sucks but better than before.

**Comment by hellzerg** [comment]
Restart is always like this.
But generally, you over-analyze it without a reason.
You can trade a little more secs on startup for overall responsiveness.
