### ISSUE TITLE
Issue with restart

### ISSUE THREAD

**Issue by porthospan** [hellzerg/optimizer#357]
This is the first time I download and run Optimizer. There´s no way I can find the "Restart to apply changes" button and I don´t understand if I have to make it manually or it has a massive bug with it
![Optimizer](https://github.com/hellzerg/optimizer/assets/63429248/d608c0cb-877f-426a-86c2-d1510650cf73)

**Comment by hellzerg** [comment]
It's probably a bug. Restart manually for now.

**Comment by vdbhb59** [comment]
Same here. This got introduced in 15.4, as till the previous version, this was showing.
Another thing, can the theme also allow to change between dark/light/auto. This dark shade is very much unfriendly.

**Comment by hellzerg** [comment]
No. The UI is undergoing a redesign, either way.
Just restart manually. That's not so critical.
@vdbhb59 @porthospan
