### ISSUE TITLE
Feature Request: add ability to replace default Windows font

### ISSUE THREAD

**Issue by jamesxujoy** [hellzerg/optimizer#358]
Hi, there, this tool is very useful for me, thanks for your hard work.
Is it possible to add ability to replace the default Windows font?

**Comment by hellzerg** [comment]
Cool. I will research into it and might include it in later versions. Thank you.

**Comment by ionuttbara** [comment]
Hi👋!
a example of registry file which it can change Windows Default font to Samsung One Font.
before to do that, backup the default entires first, and...
install the font file (must be ttf file)
create the registry file and apply it.
sign out or reboot. 
*Warning* This is working on Legacy Windows Things such as File Explorer, MMC Snap-ns , Control Panel, and in Windows 10 Legacy Taskbar and in some programs. Not working in UWP Apps , and Windows 11 Taskbar and another UWP-ish.
[Samsung One Font file for testing](https://github.com/hellzerg/optimizer/files/12294810/SamsungOne-400.zip)

``` 
Windows Registry Editor Version 5.00
; .ttf file mandatory
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]
"Segoe UI (TrueType)"="SamsungOne-400.ttf"
"Segoe UI Bold (TrueType)"="SamsungOne-400.ttf"
"Segoe UI Bold Italic (TrueType)"="SamsungOne-400.ttf"
"Segoe UI Italic (TrueType)"="SamsungOne-400.ttf"
"Segoe UI Light (TrueType)"="SamsungOne-400.ttf"
"Segoe UI Semibold (TrueType)"="SamsungOne-400.ttf"
; here font names (check in Notepad -> font)
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"Segoe UI"="SamsungOne 400"
"Arial"="SamsungOne 400"
"Times New Roman"="SamsungOne 400"
```

**Comment by ionuttbara** [comment]
i'll atach the run dialog in windows 11 Canary, written in Samsung One Font.
![image](https://github.com/hellzerg/optimizer/assets/76656855/232c3776-c617-4b9b-a356-3fb9cd1abab8)

**Comment by hellzerg** [comment]
@jamesxujoy @ionuttbara 

Hello, the Font Changer functionality is added in v15..
You can find it in Integrator > Fonts.

**Comment by ionuttbara** [comment]
i don't tested that. but i will give a try...

**Comment by ionuttbara** [comment]
yeah such UWP which are using separate fonts than Windows's stock fonts.
