### ISSUE TITLE
Problem on Universal and Windows 10 tab

### ISSUE THREAD

**Issue by denzellejohn120** [hellzerg/optimizer#36]
I just finish setting up the universal and windows 10 tab after restarting my computer (windows update,windows defender and other programs) suddenly a text appeared saying (some settings are managed by your organization) this not happened to me before just only this version 7.8

**Comment by hellzerg** [comment]
That's just Windows 10 behavior when you set custom policy rules through Registry, like disabling updates. Nothing to worry.

**Comment by denzellejohn120** [comment]
Can u fix it on next update so the (some settings are managed by your organization) dont appear again, also after I restart all I configured on universal and windows 10 tab are all turned off tried it to turn on again many times restart it also but still turn off by itself

**Comment by hellzerg** [comment]
Impossible to remove this message. It's the way Windows 10 notifies you about the changes.
I will need the log file in C:\ProgramData\Optimizer to look into your problem regarding switches turning off.
