### ISSUE TITLE
Optimizer-15.4 软件一打开启动就出错！

### ISSUE THREAD

**Issue by iideerii** [hellzerg/optimizer#360]
![963](https://github.com/hellzerg/optimizer/assets/130234436/de24b7ac-c7de-446d-8f22-cd2029817ff6)
【Optimizer-15.4 】为什么一打开就出错？

**Comment by hellzerg** [comment]
I need logs.

**Comment by abbaccadd0** [comment]
> ![963](https://user-images.githubusercontent.com/130234436/251459457-de24b7ac-c7de-446d-8f22-cd2029817ff6.png) 【Optimizer-15.4 】为什么一打开就出错？

🤔请上传%ProgramData%\Optimizer中的Optimizer.log
否则除了上帝以外，恐怕没人能知道发生了什么错误

🤔Please upload the Optimizer.log from %ProgramData%\Optimizer.
Otherwise I'm afraid only God knows what happened to cause the error.
