### ISSUE TITLE
Loads of UX issues

### ISSUE THREAD

**Issue by gqqnbig** [hellzerg/optimizer#362]
I found Optimizer through https://www.kocpc.com.tw/archives/499202 but I faced loads of user experience issues.

1. Tranditional Chinese is 正體中文, not 繁體中文 (Complicated Chinese).
1. Optimizer has no light theme. "Choose your theme" doesn't change the black background.
1. I wanna uninstall Wallet, but the dialog says uninstall the following. What is _the following_? (Figure 1)
![Figure 1](https://github.com/hellzerg/optimizer/assets/614159/c94fcf29-2811-4ee7-818b-22e5d5ee8ab1)
1. For the _Set download folder_ field in the Apps tab, can't you use [the system download folder](https://support.microsoft.com/en-us/windows/find-my-downloads-in-windows-10-de903ee9-7d37-256b-9145-f0f016c5aed8) instead of inventing your own? 

Too many zhingzhong products disrespect Windows default paths, eg. 迅雷, XX音樂盒.

5. No way to select all categories in the Cleaner tab. The Select all link, I guess, selects all found items.
1. Finally and most importantly, if I made any changes, the top right corner has text "Restart to apply changes".  I've no idea it's to restart Optimizer or restart the computer. I clicked around, and suddenly my computer restarts! 

You should show a message box to confirm! (dup of #343) Also make the clickable area be a link or a button.

**Comment by hellzerg** [comment]
1. It will be incorporated in next version.
2. Light theme is NOT an issue but a feature.
3. The app will get uninstalled, if it's not a built-in app of Windows.
4. I will consider that.
5+6 Will be done in next version.

**Comment by hellzerg** [comment]
Most of the issues/features are included in v15.5. Please update your app.
