### ISSUE TITLE
Low resolution\big font qiuck fix?

### ISSUE THREAD

**Issue by SoNickRND** [hellzerg/optimizer#366]
Still have that old win8.1 TEN INCH tablet with a 1366 x 768 screen and 150% scale (or I can't see it even with goggles)

Some of the Optimizer tabs don't fit, and I can't scroll them.

Maybe add scroll bars if the window is smaller than all visible elements on it?

<img width="683" alt="Снимок" src="https://github.com/hellzerg/optimizer/assets/125238/8a820af2-8656-4b5d-bac0-01226c60f75a">

**Comment by hellzerg** [comment]
@SoNickRND 
You can use the arrows to scroll the tabs

**Comment by hellzerg** [comment]
Ok, app is not designed to work on this low resolution with such high DPI scaling

**Comment by hellzerg** [comment]
Fixed in v15.5. Please update your app.
