### ISSUE TITLE
Start menu configuration problem

### ISSUE THREAD

**Issue by SDNarcia** [hellzerg/optimizer#368]
Hi, when applying the options that I show in the screenshots, the start menu does not save the configurations of the live tiles of the start menu, when restarting the computer, certain live tiles that I had already deleted return (Spotify, Netflix, Prime Video, etc). Thank you
![OPTIMIZER 1](https://github.com/hellzerg/optimizer/assets/140036668/fbc96ff3-1869-4bdb-a94f-8b809a90e620)
![OPTIMIZER 2](https://github.com/hellzerg/optimizer/assets/140036668/d6849694-54d6-4717-9c99-5d175e523364)
![OK](https://github.com/hellzerg/optimizer/assets/140036668/8bc5a1e4-cca4-4d77-b72c-05dd1fa1cc74)
![PROBLEM 2](https://github.com/hellzerg/optimizer/assets/140036668/bbe3d3ed-e925-4c81-b7dc-e77ef856d2fc)

**Comment by hellzerg** [comment]
@SDNarcia Hello.
Did you try resetting all the options and try again?

**Comment by Ryuyin** [comment]
> @SDNarcia Hello. Did you try resetting all the options and try again?

Hello hellzerg, may I ask how do you actually reset all the options to default? without using a restore point? Thanks.

**Comment by hellzerg** [comment]
@Ryuyin Just turn each option to off and restart your computer
