### ISSUE TITLE
Error When Start 

### ISSUE THREAD

**Issue by Djalil62** [hellzerg/optimizer#37]
![SharedScreenshot](https://user-images.githubusercontent.com/69215842/119351640-9b362580-bc98-11eb-830d-7397039aac32.jpg)

**Comment by hellzerg** [comment]
Send me the log file in C:\ProgramData\Optimizer, please.

**Comment by Djalil62** [comment]
[Optimizer.zip](https://github.com/hellzerg/optimizer/files/6553489/Optimizer.zip)
This One Bro ?

**Comment by hellzerg** [comment]
Not this. You need to check Event Viewer.

**Comment by Djalil62** [comment]
[Log1.txt](https://github.com/hellzerg/optimizer/files/6554671/Log1.txt)
[Log2.txt](https://github.com/hellzerg/optimizer/files/6554672/Log2.txt)
This is The Errors

**Comment by Djalil62** [comment]
Got it.

**Comment by hellzerg** [comment]
Check to see if this experimental build works and tell me.

https://raw.githubusercontent.com/hellzerg/optimizer/master/lab/Optimizer-TryBuild.exe

**Comment by Djalil62** [comment]
Works 100% Thanks

**Comment by hellzerg** [comment]
Okay, wait for v7.9.
