### ISSUE TITLE
[Feature request] Add a 'refresh' button to refresh status of the options

### ISSUE THREAD

**Issue by abbaccadd0** [hellzerg/optimizer#371]
🤔Windows modifies or restores some options via Windows Update, but optimizer doesn't currently know which ones have been modified, and those options remain as they were the last time they were opened.

Would it be possible to add a refresh button that would allow optimizer to recheck if options are on, or would it be possible to revert all options to off? Right now the only way to quickly reset these options is to clean up the files in ProgramData, or else people have to double-click on each of the buttons to make sure they're working properly.

**Comment by hellzerg** [comment]
@abbaccadd0 
Unfortunately, the modifications done by each option is huge in number and complex to detect the state of them. 

So, that's practically impossible.
But, Windows Updates do not modify those options recently. 

So, you're safe. You can also prepare a personal template file and reapply your desired options quickly and effortlessly.
