### ISSUE TITLE
Can no longer access the microsoft store, and microsoft apps that require a microsoft login.

### ISSUE THREAD

**Issue by StrangeCorvus** [hellzerg/optimizer#373]
A few weeks ago I downloaded the tool, works wonders. But I noticed it removed me the ability to access the Microsoft store, at the time I wasn't using it all that much so I just thought "i'll just enable it whenever I need to use it". Fast forward to when I needed to use it, I realized that checking and unchecking store updates didn't do anything. Resetting my pc also had no effect. I made sure that the store app was on the latest release available, and it was.

I have no idea what the tool did but it rendered my microsoft store completely useless, I followed multiple tutorials but couldn't fix it for the life of me. It also affected programs that depend on microsoft logins. Like minecraft bedrock for example. I can no longer log into my account.

(I know I left a previous comment, sorry if this comes off as spammy, I just thought I could leave a comment in case anyone is also having the same issues)

**Comment by hellzerg** [comment]
@StrangeCorvus 
I pinpointed the issue in Windows 11 only.
I found a way to fix it. I'll rollout an update soon.

**Comment by hellzerg** [comment]
@StrangeCorvus 

Hello.
For anyone that struggles with this issue, you can update to v15.7 and try turning on and off the Disable Microsoft Store Updates.
Then, try launching the Microsoft Store, go to settings, and toggle off/on the app updates option.
Then, restart, and the problem should be gone.

**Comment by StrangeCorvus** [comment]
@hellzerg Hi. Just downloaded the new version.
I followed the steps, and unfortunately, it didn't work. 

An update, yesterday I learned that Microsoft Office is also affected, I am not able to use any programs like Word, powerpoint, etc. I just get an error message, similar to the one in the store.
