### ISSUE TITLE
Selective Performance Tweaks

### ISSUE THREAD

**Issue by superspartan300** [hellzerg/optimizer#374]
Hello, Under the performance tweaks, I like them all except for the delay menu slideout options, that causes issues in some apps like when I right click on my VPN icon to select locations, it immediately collapses the menu. So please gives us an option to selectively choose what tweaks we want rather than all or nothing

**Comment by hellzerg** [comment]
I understand. I will try to think something about this.

**Comment by hellzerg** [comment]
Added option in v16.1. You have to re-apply the toggle based on the check.
