### ISSUE TITLE
not starting, nothing , many versions tested

### ISSUE THREAD

**Issue by mohammadwildali** [hellzerg/optimizer#38]
not starting, nothing , many versions tested

**Comment by mohammadwildali** [comment]
Faulting application name: Optimizer-7.8.exe, version: 0.0.0.0, time stamp: 0x607acada
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000007fe8e2085cd
Faulting process id: 0x604
Faulting application start time: 0x01d750e02f40caba
Faulting application path: C:\Users\FUNERAL\Downloads\Optimizer-7.8.exe
Faulting module path: unknown
Report Id: 6d295db4-bcd3-11eb-877c-ac72899a520d

----------------------------------------

Application: Optimizer-7.8.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Optimizer.ToggleSwitchRenderer..ctor()
   at Optimizer.ToggleSwitch..ctor()
   at Optimizer.MainForm.InitializeComponent()
   at Optimizer.MainForm..ctor()
   at Optimizer.Program.Main(System.String[])

**Comment by hellzerg** [comment]
Send me the log file in C:\ProgramData\Optimizer, please.

**Comment by hellzerg** [comment]
Did you try latest version?

**Comment by mohammadwildali** [comment]
i tried latest  8.3
there is no logs in path
![log](https://user-images.githubusercontent.com/1033588/120239017-133ab780-c266-11eb-9ed5-cb926d936a71.jpg)

**Comment by mohammadwildali** [comment]
![log2](https://user-images.githubusercontent.com/1033588/120239204-6f9dd700-c266-11eb-87e6-1f57668e406d.jpg)

**Comment by mohammadwildali** [comment]
update 
after deleting all files on path C:\ProgramData\Optimizer
the software starts
here is log 

[ERROR] [5/31/2021 11:18:11 PM] in function [Utilities.GetFolderStartupItemsHelper]
Unable to cast COM object of type 'System.__ComObject' to interface type 'Shell32.Shell'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

   at Optimizer.Utilities.GetShortcutTargetFile(String shortcutFilename)
   at Optimizer.Utilities.GetFolderStartupItemsHelper(List`1& list, String[] files, String[] shortcuts)

**Comment by hellzerg** [comment]
Okay, so it works all right?

**Comment by mohammadwildali** [comment]
> Okay, so it works all right?

It's running now .but another issues now.
All functions in all tabs works except first tab. 
The app hangs when choosing to disable any telemetry function .
When restarting the app and choosing another options like optimization tweaks .
Hitting apply and restart the pc .
Re-opening the app and then seeing no changes..
Should i open a new issue to make this closed?

**Comment by hellzerg** [comment]
Disabling any telemetry need some seconds, let it do the job and it will unhang.
So, regarding no changes, I think I know how to fix it. Try to make a change and close the app from the X button, in right-corner.
Re-open it and see if it changed something.
