### ISSUE TITLE
National Flag WRONG

### ISSUE THREAD

**Issue by THZrry** [hellzerg/optimizer#380]
My English is not so good, hope it's ok

First, the software is pretty good and helped me a lot.
But in Optimizer 14, the national flag of Tranitional Chinese was correct, but 15 isn't.
Taiwan is a part of China, 中华民国(1912~1949)已经灭亡了。

**开源精神是好的，但不应该与政治挂钩。**
**The spirit of open source is good, but it should not be tied to politics.(bing translated)**

If you dont know what flag to use and mistook the wrong flag with the correct one, it's better to leave it blank in my opinion
thanks to change it.

![yes](https://github.com/hellzerg/optimizer/assets/140677303/2747a0d7-a5ef-4660-9a4b-7318c5f42f8e)
![no](https://github.com/hellzerg/optimizer/assets/140677303/7d063241-7857-4383-a361-b355bc737dc6)

**Comment by hellzerg** [comment]
Hello.
I did not know which of the flag is right or wrong.
I will change it in the next version.
Thank you @THZrry

**Comment by THZrry** [comment]
Thank you, trouble you :-)

**Comment by hellzerg** [comment]
@THZrry 

Hello, the flag is changed in v15.7.
