### ISSUE TITLE
Optimizer  does not open

### ISSUE THREAD

**Issue by mike3141** [hellzerg/optimizer#383]
**Descrition of the bug:**
optimizer does not open, I tried with 15.7, 15.4 and 14.8

I would be very grateful if you could tell me how to solve this problem :)

**Logs**

**Translation of the log: 
Cannot load file or assembly System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'  not one of its dependencies. The system cannot find the specified file.

Windows 11 Pro - 22H2 (64-bit)
Optimizer 15.7 - .NET Framework 4.8 - Experimental build: False

[ERROR] [22/08/2023 13:59:40] in function [Program.Main-LoadSettings]
No se puede cargar el archivo o ensamblado 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

   at Optimizer.Options.LoadSettings()
   at Optimizer.Program.LoadSettings()

[ERROR] [22/08/2023 17:48:53] in function [Program.Main-LoadSettings]
No se puede cargar el archivo o ensamblado 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

   atOptimizer.Options.LoadSettings()
   atOptimizer.Program.LoadSettings()

Windows event log does not show any error message after trying to run the program.

thanks in advance, great program

**Comment by hellzerg** [comment]
@mike3141 
Here's the framework:
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer

**Comment by mike3141** [comment]
I'm pretty sure I had it installed, but I've reinstalled it just in case.

After doing it and deleting the route that you have indicated, I am having the same error

the first log entry is a run of optimizer with no arguments and the second is from the optimizer /restart=disabledefender command.

The error translation is the same as above:
"Cannot load file or assembly System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' not one of its dependencies. The system cannot find the specified file."


thanks again for the support

Windows 11 Pro - 22H2 (64-bit)
Optimizer 15.7 - .NET Framework 4.8 - Experimental build: False


[ERROR] [23/08/2023 17:49:33] in function [Program.Main-LoadSettings]
No se puede cargar el archivo o ensamblado 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

   en Optimizer.Options.LoadSettings()
   en Optimizer.Program.LoadSettings()


[ERROR] [23/08/2023 17:57:49] in function [Program.Main-UnhandledException]
No se puede cargar el archivo o ensamblado 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

   en Optimizer.Options.SaveSettings()
   en Optimizer.Utilities.Reboot()
   en Optimizer.Program.RestartInSafeMode()
   en Optimizer.Program.Main(String[] switches)

**Comment by hellzerg** [comment]
Okay, something strange seems to be missing on your windows installation... @mike3141

**Comment by hellzerg** [comment]
Did the problem get solved?

**Comment by Galamooth** [comment]
Tengo el mismo problema.... no se abre  encontró alguna solución?

**Comment by Galamooth** [comment]
I just found the solution. Check that the downloads folder has the default location correctly. And the program will start by default, create the optimizer downloads folder in this location.

**Comment by hellzerg** [comment]
@Galamooth Okay, seems to be a bug. Will hotfix it in next version.

**Comment by Galamooth** [comment]
I have the system in Spanish language so the downloads folder should be "Descargas" in spanish
Optimizer always changes it to "downloads" which causes the route to break. Can you fix that too? Thank you

**Comment by Galamooth** [comment]
When I use optimizer. The program creates a folder in  "Downloads" Since my system is in Spanish. The correct name is "Descargas" So the program creates a folder called downloads in addition to my original downloads folder. Sometimes it replaces the original folder by removing system properties as defaults I must Manually adjust folder every time I use optimizer and reset folder Descargas As the default folder this somehow caused the problem mentioned optimize just wouldn't open

**Comment by Galamooth** [comment]
Excuse my bad English, I'm using a translator.

**Comment by hellzerg** [comment]
@Galamooth 
Okay, can you tell me the value of AppsFolder in C:\ProgramData\Optimizer\optimizer.json?

**Comment by Galamooth** [comment]
Also note that optimize will only replace my downloads folder if it is empty. 
[Optimizer.txt](https://github.com/hellzerg/optimizer/files/12848258/Optimizer.txt)

**Comment by Galamooth** [comment]
just rename it and put it in the correct directory. but this problem was the reason why optimizer did not open

**Comment by hellzerg** [comment]
That's strange. because even if the folder path set in AppsFolder value not exists, it creates it. It does not crash.

**Comment by Galamooth** [comment]
Well, I'm not the only one this happened to. You should identify the name of the downloads folder by different languages ​​just to avoid these problems.

**Comment by hellzerg** [comment]
Can you go to Registry -> HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
and tell me if the value of {374DE290-123F-4565-9164-39C4925E467B} key is correct?

@Galamooth

**Comment by Galamooth** [comment]
@hellzerg 
![Captura de pantalla 2023-10-09 110813](https://github.com/hellzerg/optimizer/assets/90434643/fddfb6cf-3f31-43bd-aaf0-8acfa952c874)

**Comment by hellzerg** [comment]
Okay, I will retrieve the folder with translation from there.

**Comment by Galamooth** [comment]
Apart of this. Will you implement more improvements or adjustments? 
Some option to import and export energy plans would be interesting.
