### ISSUE TITLE
Managed by Organization

### ISSUE THREAD

**Issue by NoYouPickAUsername** [hellzerg/optimizer#384]
All of a sudden, after applying some tweaks. My Chrome browser suddenly says an organization manages it, It was fine before using tweaks from the optimizer app, as I was still able to use a secure DNS earlier. I just wanted to ask if maybe it's some bug or maybe a tweak that triggered this so I know what to do not apply.

**Comment by hellzerg** [comment]
Apparently, you disabled Chrome telemetry. So this message notifies you that some chrome internal settings have been set. Don't worry.

@NoYouPickAUsername

**Comment by NoYouPickAUsername** [comment]
much appreciated
