### ISSUE TITLE
feed.json

### ISSUE THREAD

**Issue by Alfonso7206** [hellzerg/optimizer#386]
it seems that the feed.json file updated with new links is not loading

**Comment by hellzerg** [comment]
@Alfonso7206 

What do you mean? My feed is working fine in the app.

**Comment by Alfonso7206** [comment]
> @Alfonso7206
> 
> Cosa intendi? Il mio feed funziona correttamente nell'app.



> @Alfonso7206
> 
> What do you mean? My feed is working fine in the app.


I noticed that it works online, but there are no updated files online, you also need to add an off-line mode to customize the links and update them via the feed.jason file

**Comment by hellzerg** [comment]
The apps download IS an online-feature. No need for offline mode

**Comment by Alfonso7206** [comment]
what a pity! I wanted to keep it as a download manager for programs, but I can't use it like this... Thanks!

**Comment by hellzerg** [comment]
How can be used like download manager if you are OFFLINE? I told you it works online.
