### ISSUE TITLE
Adding Custom Tweaks

### ISSUE THREAD

**Issue by XxShyW0lf** [hellzerg/optimizer#387]
Could be a very user-friendly way to add your own registry keys or batch files to the tool. This would save time for people because they would no longer have to use different tools for different things.

**Comment by hellzerg** [comment]
But wouldn't that be dangerous?

**Comment by XxShyWolf** [comment]
Well, this would be just for the users tool that's on their pc. It's up to the user to put beneficial custom tweaks in it.

**Comment by hellzerg** [comment]
I am pretty sure that if something like this would be implemented, the signature of the app will be flagged as suspicious by most of AV providers, because it could serve as a potential script engine.
