### ISSUE TITLE
Re-apply settings or status check

### ISSUE THREAD

**Issue by Th3EvilGod** [hellzerg/optimizer#389]
It difficult to understand if certain features have been applied or not, it would be great to have a re-apply settings feature so it would rerun the commands making sure the selected options are in place. Alternatively, it could go over all settings by checking the status of each and show if it has been applied or not.

**Comment by hellzerg** [comment]
@Th3EvilGod 

Hello.

It's impossible to check if all options are applied or not, because every option has a ton of tweaks and various operations done.

Well, some kind of reapply function could be done, though.

**Comment by Th3EvilGod** [comment]
looking forward to it!

**Comment by hellzerg** [comment]
A new button "Reinforce policies" got introduced in Options, which you can use to re-apply your current selected tweaks.
The app will restart after it's done.
