### ISSUE TITLE
Version without the Defender BAT.Disabler

### ISSUE THREAD

**Issue by Logic-Elliven** [hellzerg/optimizer#391]
VirusTotal (and Kaspersky) goes nutz! when you try to download Optimizer:
https://www.virustotal.com/gui/file/e790cd5ea36f48da2df32726221cd16de32192f54e9a01b4b600e13841763f1a?nocache=1

So I suggest a version without the Defender disabler with the advice that people install Kaspersky Free or Bitdefender Free as a means of getting faster I/O.
**Both will disable Defender on install** and show good speed and detection rates:
https://www.av-comparatives.org/tests/real-world-protection-test-february-may-2023/
https://www.av-comparatives.org/tests/performance-test-april-2023/

I chose Kaspersky due to less false positives and due to Bitdefender slowing down web page loads dramatically.
(I note that there are newer tests showing Avast/AVG to be flavour of the month but NB their effects on load times...

I believe there will be a lot more downloads of Optimizer if the download isn't blocked and deleted by default.

**Comment by hellzerg** [comment]
You mean to publish two different releases? One with the ability to disable Defender and one which does not have it?

**Comment by hellzerg** [comment]
Βw careful. The link you sent me to virustotal is not the same as the Optimizer's hash.

**Comment by hellzerg** [comment]
You have some tampered file that you think is the optimizer. Delete it and try the official one. @Logic-Elliven
