### ISSUE TITLE
Ransomeware

### ISSUE THREAD

**Issue by SuperDuckyy** [hellzerg/optimizer#392]
**Describe the bug**
When i try to download it Windows defender stop the download saying its a RansomWare

**Expected behavior**
just downloading normaly

**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/145851553/d81f94fd-d1df-43e6-8274-7a0adee29ec8)
![image](https://github.com/hellzerg/optimizer/assets/145851553/8923db49-f402-4453-bc32-71864ceba2c0)

**Desktop (please complete the following information):**
 - windows 11 idk what is a build
- what is .net thing
 - idk latest ig

**Comment by hellzerg** [comment]
This master .zip you are trying to download it's the source code, not the actual app. Anyways it's false positive
