### ISSUE TITLE
more privacy option disable the news and interest widget in taskbar (win10)

### ISSUE THREAD

**Issue by djsolidsnake86** [hellzerg/optimizer#393]
i found this bug, is possible fix?

**Comment by hellzerg** [comment]
You mean that News and interest widget does not get disabled?

**Comment by djsolidsnake86** [comment]
i mean that enhance privace actually disable that widget
why it disable? i think it was a bug

**Comment by hellzerg** [comment]
It's not a bug. It's by design.

**Comment by djsolidsnake86** [comment]
i see, can you please write in the description of enhance privacy? and if you can create a enhance privacy that not disable that widget? thanks

**Comment by hellzerg** [comment]
Added option in v16.1. You have to re-apply the toggle based on the check.

**Comment by 0xLunch** [comment]
After disabling this, my widgets no longer work. Get the old style icon in the task bar and does nothing. It should have returned to the weather / news in the corner.
![image](https://github.com/hellzerg/optimizer/assets/152280144/e1c9122a-2a14-4d33-84bb-2da8e8b0990d)

**Comment by hellzerg** [comment]
@0xLunch you should enable widgets separately. there is a toggle for this in the app.

**Comment by 0xLunch** [comment]
I reset thru windows update and kept files.
________________________________
