### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by DreamUFO** [hellzerg/optimizer#394]
Any plan to add proxy setting for the app?
cas when the app start at first time, need download some depeends, in some situation network can not visit web directly.
so need to setting a network proxy to visit internet to download what app init needs.

**Comment by hellzerg** [comment]
@DreamUFO Problem solved?

**Comment by DreamUFO** [comment]
no not the DNS, my pc in the lan network can not usd dns.
maybe I can use the tool in the normal network. download all the depeends,then copy all to the lan pc.

**Comment by hellzerg** [comment]
Go to `C:\ProgramData\Optimizer\optimizer.json` and make `DisableAppsTool` TRUE.
Relaunch the app and test it.
@DreamUFO

**Comment by DreamUFO** [comment]
> Go to `C:\ProgramData\Optimizer\optimizer.json` and make `DisableAppsTool` TRUE. Relaunch the app and test it. @DreamUFO

this setting is working,but will stock at 
![QQ截图20231016100054](https://github.com/hellzerg/optimizer/assets/10512112/9f3b1baa-cfe1-415d-9509-6aca641f2c9a)
for a long time, then finally get in Main Window.
thanks for your help.
