### ISSUE TITLE
After optimization, I found that the folders in the main folder are no longer displayed. I want to restore them to their original state.

### ISSUE THREAD

**Issue by zhl111** [hellzerg/optimizer#397]
**Describe the bug**
After optimization, I found that the folders in the main folder are no longer displayed. I want to restore them to their original state.

but，I didn't choose the option to optimize the folder.

**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/29135984/84088c92-be2e-47e5-aa47-3fea0a8f0875)

![image](https://github.com/hellzerg/optimizer/assets/29135984/0a26e481-5eda-4017-91ce-20b6455566b2)

**Desktop (please complete the following information):**
 - Windows v11
- .NET Frameworks installed
 - Optimizer v1.5.8

**Comment by hellzerg** [comment]
Did you try resetting the Restore Classic File Explorer in Windows 11 tab?

**Comment by hellzerg** [comment]
@zhl111 Can you describe more?
