### ISSUE TITLE
add extended selector option

### ISSUE THREAD

**Issue by Shiro-zero** [hellzerg/optimizer#399]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I play with some settings and some are locked by the Optimizer but I can't undo the change because i dont know what option lock what.

**Describe the solution you'd like**
a way to force Optimizer to revert changes and an extended selector for the option (each change)

**Describe alternatives you've considered**
a way to uninstall the Optimizer

**Additional context**
I don't really know what to add

**Comment by hellzerg** [comment]
Tell me which of the tweaks in Optimizer, did not revert successfully, so I can improve them.
@Shiro-zero

**Comment by Shiro-zero** [comment]
the telemetry one did not turn off 

when i repair the app that turn off all the switch  but did not undo any change

**Comment by hellzerg** [comment]
Repair does not reset the options/tweaks.
@Shiro-zero
