### ISSUE TITLE
Reinforce policies got "This app has been blocked by your system admin"

### ISSUE THREAD

**Issue by Th3EvilGod** [hellzerg/optimizer#402]
Reinforce policies have changed the **UAC: Admin approval mode for built-in administrator account** to false, and I couldn't access the Windows phone link. I was getting "App has been blocked by your system admin" error.
![image](https://github.com/hellzerg/optimizer/assets/117441689/76a164ff-a4b6-452d-9c91-4a3d4497fab7)
![image](https://github.com/hellzerg/optimizer/assets/117441689/195d3aae-be8d-439f-af6d-475c874bc5c0)
![image](https://github.com/hellzerg/optimizer/assets/117441689/6eef52d7-8b19-4f11-83d3-d251dfbc3791)

Enabling the setting fixed the issue.

These are the applied settings to help with the troubleshooting. 
![image](https://github.com/hellzerg/optimizer/assets/117441689/90a31d3f-6ade-4505-9398-8d37bf33ac22)
![image](https://github.com/hellzerg/optimizer/assets/117441689/295cb8f3-f2f9-4e03-be08-88229d78ec5f)

**Comment by hellzerg** [comment]
This setting does not get touched from my app. Maybe you tried some other similar software in the past.
Did you try resetting the **Enhance Privacy**?

**Comment by chaiwanliang** [comment]
没有互联网连接，请重新刷新链接

**Comment by chaiwanliang** [comment]
#
![image](https://github.com/hellzerg/optimizer/assets/43395862/35eda7c3-5a61-434a-a820-a452b853a196)

**Comment by 3ht7pud22ih9i5elvjkou** [comment]
I faced the same issue. I didn't install other similar software and I has the same setting Th3EvilGod did above in UAC which stays the same(This can proof hellzerg doesn't touch this in optimizer). But it's still not working. Here are my settings in optimizer.
![image](https://github.com/hellzerg/optimizer/assets/25822331/2dd59ac7-cf71-4a85-9de4-62ef87d0d0df)
![image](https://github.com/hellzerg/optimizer/assets/25822331/895df6e1-d97f-4383-868a-3d7deb69e084)
![image](https://github.com/hellzerg/optimizer/assets/25822331/257fbf55-19c8-4e83-88ba-75731145378f)

**Comment by hellzerg** [comment]
@3ht7pud22ih9i5elvjkou Most like Enhance Privacy option

**Comment by 3ht7pud22ih9i5elvjkou** [comment]
> @3ht7pud22ih9i5elvjkou Most like Enhance Privacy option

![image](https://github.com/hellzerg/optimizer/assets/25822331/d2743ed9-90b1-4708-9cb1-d299f86eec32)
I finnaly found this option stops the phone link.

**Comment by hellzerg** [comment]
Great. I will add it to my FAQ section
