### ISSUE TITLE
RogueKiller detects Optimizer folder in C:\ProgramData as BitMiner.gen0

### ISSUE THREAD

**Issue by NickXDD** [hellzerg/optimizer#403]
RogueKiller detects Optimizer folder in C:\ProgramData as BitMiner.gen0. Should I be concerned?

**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/93096921/e8f5a3a2-68fc-4d6e-9567-2ae7b9f79811)

**Desktop (please complete the following information):**
 - Windows 10 latest version and build
- .NET Frameworks: installed
 - Optimizer version: newest

**Comment by NickXDD** [comment]
Additionally:

![image](https://github.com/hellzerg/optimizer/assets/93096921/a98ca40a-c306-42db-bbfd-83db226dd3d6)

**Comment by hellzerg** [comment]
If your app is downloaded from this github official source, you don't have to worry.
@NickXDD
