### ISSUE TITLE
Windows Hello Fail

### ISSUE THREAD

**Issue by DeleanDD** [hellzerg/optimizer#405]
Hello. I discovered a flaw in the program, in fact, it is not a flaw, but a cause that affects Windows Hello. If the "increased privacy" option is activated in the "Windows 11" tab, it causes Windows Hello to fail, which prevents entry into the system via fingerprint or facial recognition. I believe it is important to at least have a pop-up window to warn the user that when activating this option, it will disable Windows Hello. Thanks

**Comment by DHCPCD9** [comment]
I think it should be added to FAQ.

**Comment by hellzerg** [comment]
Yes, I will add it to the FAQ section!
I hope, resetting the **Enhance Privacy** restores the functionality.
