### ISSUE TITLE
16.1 is blocked with Windows Defender

### ISSUE THREAD

**Issue by kodiadon** [hellzerg/optimizer#406]
All the versions before 16.1 have installed with no problem.  When I try to update to 16.1 it gets blocked.  I did temporarily disable Defender and I was able to install it. But after re-enabling  Defender the program got deleted.

Windows 10  22H2
.NET Framework 4.8.1
Optimizer not installed (removed because Defender)

**Comment by hellzerg** [comment]
Unfortunately, I can't do anything about this. You can report the file as safe so it gets out of detection soon.

**Comment by kodiadon** [comment]
Ok. Just wondering why this version did this but all the other versions didn't

**Comment by imrightfr** [comment]
also why does it have a TROJAN VIRUS

**Comment by kodiadon** [comment]
I resolved the problem. I told Defender the program was safe and now it's working.

**Comment by hellzerg** [comment]
Unfortunately, it's marked unsafe due to the new functionality which removes the Edge.
