### ISSUE TITLE
It looks like it has a lot of viruses, why? If you say it's safe?

### ISSUE THREAD

**Issue by JohanderD4** [hellzerg/optimizer#407]
![image](https://github.com/hellzerg/optimizer/assets/62218018/caa22066-1e80-4ff8-8f11-b50177d3e17d)

If you see, it has a lot of viruses, and once used it does increase the performance but then it makes the pc very slow

**Comment by imrightfr** [comment]
dont do it use versions that have no viruses i had to download a anti virus  because my security was severe

**Comment by XkacpeRXx** [comment]
@imrightfr I downloaded it now. Yesterday showed me trojan. Now it seem to be okay. Could u verify that? I'll be very thankful

**Comment by meoowe** [comment]
Just dont download stuff like this ever - most of the time it will be a virus.
[https://www.virustotal.com/gui/file/e68aa2c093129f85706905201762db54964da1d57bf08c4f80e84f27e255fb7a](link to virustotal results for version 16.1)
Always have a antivirus on your pc especially if youre downloading random files off the internet

**Comment by Computment** [comment]
I think the reason it detects as a virus is  due to it not being a popular software AND It using administer power to change settings and block certain things

**Comment by flezus** [comment]
> @imrightfr I downloaded it now. Yesterday showed me trojan. Now it seem to be okay. Could u verify that? I'll be very thankful

The same thing happened to me yesterday. I use Kaspersky and it was deleting the program, I disabled Kaspersky and Windows Defender beeped. Today I downloaded it again and it worked normally, I don't know what it could have been.

**Comment by hellzerg** [comment]
It's because the newly added functionality that removes Edge.

**Comment by imrightfr** [comment]
so the amount of trojan viruses result to that?

**Comment by hellzerg** [comment]
@imrightfr yes.

**Comment by LZeugirdor** [comment]
> It's because the newly added functionality that removes Edge.

Honestly a really useful feature, sad that you had to remove it. I was able to remove edge using Linux to delete the Microsoft folder that edge is in, then to prevent reinstallation I symlinked the folder to null lol. Definitely something I recommend.
