### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by BatesyBoy** [hellzerg/optimizer#409]
It's a trojan; don't install

**Comment by hellzerg** [comment]
@BatesyBoy 
elaborate and show us proof of trojan activity from my app. 

show me exactly where in the code which is publicly available

**Comment by mentoriax** [comment]
Windows Defender shows a warning that a Trojaner is inside. You can allow it for shure, its all fine

**Comment by hellzerg** [comment]
It's 100% safe. I am still waiting to show me where the trojan is technically.

**Comment by mentoriax** [comment]
Hi, i have installed Windows 10 22H2 by a friend , fresh Install, after
that i direkt Install / use youre optimizer, Windows Defender whant to
Block the Download and say that a Trojaner / Script Something ist inside. I
dismissed IT and the Download was del...

deadmoon ***@***.***> schrieb am Fr., 27. Okt. 2023, 17:44:
