### ISSUE TITLE
Re-enable

### ISSUE THREAD

**Issue by utkusucu** [hellzerg/optimizer#411]
Can you add re-enabling options for settings.

**Comment by hellzerg** [comment]
what do you mean?

**Comment by utkusucu** [comment]
For example, I changed show all tray icons or disabled nvidia telemetry. How can I revert the changes for them.

**Comment by utkusucu** [comment]
For example I changed show all tray icons and disabled nvidia telemetry, how can I revert the changes.

**Comment by SERGEYBC** [comment]
Как отменить изменения?

**Comment by hellzerg** [comment]
You just turn the toggle off just like you enabled it
