### ISSUE TITLE
DIskless BSOD

### ISSUE THREAD

**Issue by dayzumn** [hellzerg/optimizer#415]
Hello Hellzerg,
Thank you for the great tool.
Whenever I optimize diskless (ccboot) image it goes BSOD. IRQL_NOT_LESS_OR_EQUAL blue screen of death occurs.
Win version 22H2 OS Build 19045.3448
Thank you

**Comment by hellzerg** [comment]
I don't understand. What is the diskless image?

**Comment by dayzumn** [comment]
A diskless node (or diskless workstation) is a workstation or personal computer without disk drives, which employs network booting to load its operating system from a server.
Programs such as CCBOOT, icafe8, CCU.

**Comment by hellzerg** [comment]
Well apparently, my app does not suport this kind of Windows images @dayzumn
