### ISSUE TITLE
Can't use Phone link app

### ISSUE THREAD

**Issue by RyuginShintai** [hellzerg/optimizer#418]
Can't use Phone link app because it's says "System admin blocked this function"

 - Windows 10 22H2

 - .NET Frameworks 4.8 installed
Optimizer
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13279135/Optimizer.log)

 - Optimizer version 16.2

**Comment by RyuginShintai** [comment]
Found solution to disable enchanced privacy

**Comment by rsforbes** [comment]
@RyuginShintai - Thanks for logging this issue. I ran into the same problem.
