### ISSUE TITLE
Startup apps cant delete

### ISSUE THREAD

**Issue by imaginetodo** [hellzerg/optimizer#420]
In the version 16.2, In the tab STARUP I can't delete the programs because the button does not appear. Also the menu does not appear correctly in its place
In the version 16.0 this problem dont exist

**Expected behavior**
I would like it to appear again to delete the programs.

**Screenshots**
![version 16 0](https://github.com/hellzerg/optimizer/assets/150598370/c1bd1230-a1e9-4726-9045-520eaf8f18ab)
![version 16 2](https://github.com/hellzerg/optimizer/assets/150598370/788f0e71-09f3-4785-aa36-0c973c961eee)

**Logs**
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13328101/Optimizer.log)

**Desktop (please complete the following information):**
 - Edición	Windows 10 Home
Versión	22H2
Instalado el	‎11/‎11/‎2023
Compilación del sistema operativo	19045.3570
Experiencia	Windows Feature Experience Pack 1000.19052.1000.0
- .NET Frameworks installed 
.NET Framework 4.8
 - Optimizer version 16.2

**Comment by hellzerg** [comment]
Okay, thanks,will fix it

**Comment by hellzerg** [comment]
You can update to v16.3 to get the fixed UI.
