### ISSUE TITLE
cant open optimizer

### ISSUE THREAD

**Issue by XTyrre** [hellzerg/optimizer#421]
when i restarted my pc i couldnt open it it just says optimizer is already running in the background. i want to change some settings but i cant open it

**Comment by XTyrre** [comment]
still doesnt work when i open it it just dissapears

**Comment by sebadamus** [comment]
> i wiewed this app in winrar and it said This program cannot be run in DOS mode. Idk what DOS even mean..

Post printscreens of the process you do.  Maybe you have an antivirus that block it or deletes the file, if it is 0 bytes its empty and will give the error you post last.

**Comment by XTyrre** [comment]
sain sen toimimaan mutta en voi ladata mitään microsoft storesta miten saan korjattua sen

**Comment by XTyrre** [comment]
and now i cant even update my windows

**Comment by hellzerg** [comment]
Any progress? @XTyrre

**Comment by XTyrre** [comment]
it works now but i cant use my windows key button it only works in games and its weird. if i delete uwp app and restore them does it restore only apps that i have deleted or all of them?

**Comment by hellzerg** [comment]
@XTyrre All of them.
