### ISSUE TITLE
It takes too long to open it in China

### ISSUE THREAD

**Issue by Xray22336** [hellzerg/optimizer#423]
**Describe the bug**
It takes too long to open this software in China maybe because it will connect to github.com when opening this software. However, in China, connecting to github is horribly slow.

**Expected behavior**
Please not let it connect to any website when opening this software.

**Screenshots**
none

**Logs**
none

**Desktop (please complete the following information):**
none

**Comment by hellzerg** [comment]
It contacts with github.com because it checks for update in startup

**Comment by hellzerg** [comment]
You can update to v16.3 and disable Update on Launch in Options tab!
