### ISSUE TITLE
GUI issue with "optimize performance"

### ISSUE THREAD

**Issue by stringyjosh94** [hellzerg/optimizer#424]
**Describe the bug**
when i enable the optimize performance toggle id also like to toggle the menu delay off and show all tray icons off but even after toggling them and rebooting or closing the app it always resets back to checked no matter what if the optimize performance is toggled.  

**Expected behavior**
enable Toggle Optimize performance then uncheck the menu delay and uncheck show all tray icons without them being rechecked after application exit or reboot.

 - Microsoft Windows 10 pro build 19045 
-net framework 4.8
 - v16.2

**Comment by hellzerg** [comment]
Actually, if you apply the toggle option with them unchecked, it will be okay.
