### ISSUE TITLE
Web research is not deactivated for normal user account

### ISSUE THREAD

**Issue by microbearlogist** [hellzerg/optimizer#427]
**Describe the bug**
I'm using a setup with two account:
- Admin
- Normal user

Same Optimizer template is applied to both (using administrator privileges on the normal user account).
But in the case of the normal user, web search from the taskbar is not disabled (although it is for the admin).

Is this a limitation inherent to normal user account or a bug from optimizer?

**Logs**

**Desktop (please complete the following information):**
 - Windows 10 22H2
- .NET Frameworks 3.1.426 core and 7.0.14 runtime
 - Optimizer 16.2

**Comment by hellzerg** [comment]
It's a limitation currently in the app. I will include a user-global disable for the web search.

**Comment by microbearlogist** [comment]
Thanks a  lot !

**Comment by hellzerg** [comment]
You can update to v16.3 to get the feature working!
