### ISSUE TITLE
Optimizer not work

### ISSUE THREAD

**Issue by lica326** [hellzerg/optimizer#428]
**Describe the bug**
My games are not more smooth i have all activated and nothing happened before they were runing smoother but now they don't work please help.
**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log.

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by hellzerg** [comment]
You may disabled Game Bar and Xbox service which you should NOT for the games to work properly

**Comment by lica326** [comment]
And if I have these two options disabled then it will go to see much smoother?

**Comment by hellzerg** [comment]
@lica326 Do your games work now?
