### ISSUE TITLE
Add "OffText" feature to ToggleSwitch

### ISSUE THREAD

**Issue by Hedreon** [hellzerg/optimizer#43]
'Should be like this:

When the switch isn't toggled:
_"Enable Example"_

When the switch is toggled:
_"Disable Example"_

The reason why I'm asking for that to be added is because I want to make it more simpler to understand for newbies (probably not but still) instead of when the switch is/isn't toggled: _"Disable Example"_

**Comment by hellzerg** [comment]
That will complicate things, regarding translation.

**Comment by Hedreon** [comment]
well I think you can ask him to translate the "Enable Example" string and I don't think it would complicate stuff..?

**Comment by hellzerg** [comment]
The mentality behind the switch mechanic is for any given switch to portray a static state, rather than what will happen fi you toggle the switch.

**Comment by Hedreon** [comment]
Oh.
