### ISSUE TITLE
Optimizer wont  open

### ISSUE THREAD

**Issue by DingyMachoMan** [hellzerg/optimizer#430]
everytime i open it its checking for requirements  and then it  just closes and nothing else

**Comment by hellzerg** [comment]
@DingyMachoMan 
I need logs from C:\ProgramData\optimizer\optimizer.log
as well as from event viewer

**Comment by DingyMachoMan** [comment]
> @DingyMachoMan I need logs from C:\ProgramData\optimizer\optimizer.log as well as from event viewer

how do i get to  that  i cant find it

**Comment by hellzerg** [comment]
@DingyMachoMan Try deleting the C:\ProgramData\Optimizer whole folder

**Comment by DingyMachoMan** [comment]
@hellzerg done do i just redownload now or what?

**Comment by hellzerg** [comment]
@DingyMachoMan you should be fine running the app

**Comment by DingyMachoMan** [comment]
@hellzerg now  it just says  its already running in the background  when i re install it

**Comment by DingyMachoMan** [comment]
@hellzerg and when i open with administrator it just says checking forr requirements then doesnt open same  problem

**Comment by hellzerg** [comment]
@DingyMachoMan Did you try latest version? Also check if it is running in task manager.

**Comment by DingyMachoMan** [comment]
@hellzerg i got the latest version and it wasnt running in task master

**Comment by hellzerg** [comment]
@DingyMachoMan So did it open?

**Comment by DingyMachoMan** [comment]
@hellzerg nope  nothin  changed

**Comment by hellzerg** [comment]
I need the logs @DingyMachoMan

**Comment by DingyMachoMan** [comment]
@hellzerg wherre  do i get that

**Comment by MrDromp** [comment]
Same problem for me here. My workaround was, to try [Releases](https://github.com/hellzerg/optimizer/releases) that's working, for me 15.4. I started 15.4 once, closed it and now the newest Version 16.3 is working too.

**Comment by B-l-a-z-e** [comment]
umh i cant open it says its already running in the background

**Comment by hellzerg** [comment]
@MrDromp Can you try the latest v16.4 and report if the issue is solved?

**Comment by DingyMachoMan** [comment]
> Same problem for me here. My workaround was, to try the last [Release](https://github.com/hellzerg/optimizer/releases) that's working, for me 15.4. I started 15.4 once, closed it and now the newest Version 16.3 is working too.

@MrDromp this is my  first time tryna get it tho

**Comment by DingyMachoMan** [comment]
@hellzerg version 16.4  works thanks man
