### ISSUE TITLE
Checkboxes "Show all tray icons" & "Remove menu delay" are allways checked

### ISSUE THREAD

**Issue by Jakiboy** [hellzerg/optimizer#431]
First for all, thanks for this awesome production!

## Description:

Under the **"Optimize Performance"** Option:  
Both checkboxes *"Show all tray icons"* & *"Remove menu delay"* are allways checked!  
Which is **maybe** an issue.

## Reproduce action:

1. Disable checkbox "Show all tray icons" OR "Remove menu delay" OR Both.
2. Close Optimizer.
3. Restart system *(Optional)*.
4. *"Show all tray icons"* & "Remove menu delay"* options are checked again.

## Excpected behavior:

The checkboxes *"Show all tray icons"* & *"Remove menu delay"* should stay unchecked after being updated.  
Or maybe disable these options if the testes doesn't met or not changeable.

## Screenshots:

![3265632](https://github.com/hellzerg/optimizer/assets/7604550/59a62bd6-80b8-4fa5-87df-529cd49bcbb6)

## Platform details:

* Optimizer 16.2
* Windows 10 Pro - 22H2 (64-bit).
* Tested on Windows 10 Pro - 22H2 (64-bit) VM (**Fresh install**).
* Location: *"C:\Program Files\Optimizer\Optimizer.exe"*.
* Tested on *"C:\Optimizer\Optimizer.exe"*.
* Optimizer runed as admin.

## Logs:

* [Optimizer.log](https://github.com/hellzerg/optimizer/files/13462629/Optimizer.log)

**Comment by hellzerg** [comment]
You can update to v16.3 to get the fixed UI
