### ISSUE TITLE
Updated/fixed Russian translation for Optimizer

### ISSUE THREAD

**Issue by Dimmitrius** [hellzerg/optimizer#435]
Hello,

The current Russian translation of Optimizer is not very accurate. I offer you a corrected translation, here is a link to it:
https://www.dropbox.com/scl/fi/n0w1xa8by5vr4d99fmgwi/Optimizer_16.2_RU_fixed.zip?rlkey=3gl99rokq68i3dt7hrkvyaeq6&dl=0
My version is probably not final and will require additional improvement, but for this I need to see how the translation looks in the program.
I have a lot of experience in software localization. Contact me at erodim@mail.ru if you need my additional help.

Regards,
Dmitry Yerokhin

**Comment by hellzerg** [comment]
@Dimmitrius  Unfortunately, the JSON file is in incorrect format, can you fix it?
