### ISSUE TITLE
MalwareByte Detects Virus

### ISSUE THREAD

**Issue by Computment** [hellzerg/optimizer#439]
I have run a malware byte test before and after downloading optimizer and malwarebyte detected 2 viruses after downloading and using it can you please tell me why optimizer is always detected as a virus from malwarebyte, Virustotal or other softwares?
![Screenshot_1](https://github.com/hellzerg/optimizer/assets/148971574/facd10c5-dd4e-40fc-b139-289843a15f4b)
![Screenshot_2](https://github.com/hellzerg/optimizer/assets/148971574/212bb90b-e3ab-45fd-8b30-9637a0c42293)

**Comment by techgamers2** [comment]
what malwarebyte detected is not a virus its a PUM potentially unwanted modification . its harmless u may hav tweaked ur system via winaero tweaker or similar program which hav the ability to disable MRT via registry change 
u can read more about this in this [article](https://winaero.com/disable-malicious-software-removal-tool/)  
and for virus total results all threat detected are false positive as this program has ability to disable microsoft defender and other system function to yield more performance as u can read in virus total> ikarus result section the threat detected is labeled as bat.disabler which explains tht . if u r still curious u can see the source code of the program and also its used by lot of people and my tech people recommends it
