### ISSUE TITLE
startup slow

### ISSUE THREAD

**Issue by fengymi** [hellzerg/optimizer#441]
Why is my startup so slow, taking a few minutes?

**Comment by hellzerg** [comment]
Your internet or your resolution to github.com is slow probably

**Comment by hellzerg** [comment]
You can update to v16.3 to fix the problem by disablign Update on Launch in Options tab

**Comment by fengymi** [comment]
I have upgraded and the same issue still exists
This is a log, I'm not sure if it's useful

![image](https://github.com/hellzerg/optimizer/assets/17907299/e8b3f7a6-1c43-4baa-a460-b728048cf58f)

**Comment by hellzerg** [comment]
@fengymi Go to C:\ProgramData\Optimizer and edit the optimizer.json.

Make DisableAppsTool to true and then open the app
