### ISSUE TITLE
Problem with options

### ISSUE THREAD

**Issue by doubleside2** [hellzerg/optimizer#442]
**Describe the bug**
the software does not start with [windows.](url)

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows 11 Home version 22h2
- .NET Frameworks version 4.8
 - Optimizer version 16.2
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13610858/Optimizer.log)

**Comment by doubleside2** [comment]
Hello,
Yes, it is displayed and active...

Il giorno ven 8 dic 2023 alle ore 15:01 deadmoon ***@***.***>
ha scritto:

**Comment by hellzerg** [comment]
@doubleside2 

Optimizer needs UAC allow access to be run at startup for administrative privileges
