### ISSUE TITLE
tpm check not working

### ISSUE THREAD

**Issue by Srlen** [hellzerg/optimizer#443]
**Describe the bug**
I tried to turn disable tpm check on but it seems not working 
**Expected behavior**
Must to allow me to upgrade to windows 11 in PC health check/Windows11InstallationAssistant
**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13631787/Optimizer.log)

**Desktop (please complete the following information):**
 - windows 10 - 22H2 - Build 19045._3693
- SDK 6.0.141 ( x64 ) 
 - 16.2

**Comment by hellzerg** [comment]
Unfortunately this method no longer works for bypassing update from Windows Update.
You should use this instead:

https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Skip_TPM_Check_on_Dynamic_Update.cmd
