### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by ImPuzzled** [hellzerg/optimizer#444]
**Describe the bug**
I run the optimizer it runs until inspecting hardware then crashes.

Im on Windows 11
**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/103962979/4e3f1126-00cd-4ef8-8730-7e3a01c14f93)

**Logs**
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13664917/Optimizer.log)
\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
OS Name	Microsoft Windows 11 Home Version	10.0.22635 Build 22635 x64

- .NET Frameworks installed C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
 - Optimizer version 16.2

**Comment by hellzerg** [comment]
@ImPuzzled 
Go to ProgramData\Optimize and delete the whole folder Optimizer

**Comment by ImPuzzled** [comment]
@hellzerg I deleted it and ran again and received the same error in logs.

**Comment by hellzerg** [comment]
Can you show me your Optimizer.json in C:\ProgramData\Optimizer?

@ImPuzzled

**Comment by ImPuzzled** [comment]
[Optimizer.json](https://github.com/hellzerg/optimizer/files/13782432/Optimizer.json)

**Comment by hellzerg** [comment]
The issue is fixed. Please update to v16.4.
