### ISSUE TITLE
[Feature Request] - Need A Toggle for Search and Weather ☑

### ISSUE THREAD

**Issue by techgamers2** [hellzerg/optimizer#447]
**Is your feature request related to a problem? Please describe.**

i like the other tweaks inside restore classic option provide but it also disables search icon and news and interest from taskbar . i get tht classic explorer was supposed to be tht way but a toggle option to enable search and news interest back would be great ! 
<details>
<summary>Screenshot</summary>
windows 10 
<br>
<img src="https://github.com/hellzerg/optimizer/assets/44696073/1fb07af9-7a37-46a2-ade6-d5f077218784">
</img>
</details>

**Describe the solution you'd like**

a simple toggleable option like u hav in "enhance privacy and optimize performance section " would be great for restore classic explorer section

**Describe alternatives you've considered**

i can enable search icon back by right clicking on taskbar >> search > show search icon but for news and interest i hav to do via [registry](https://www.tenforums.com/tutorials/178178-how-enable-disable-news-interests-taskbar-windows-10-a.html) change

**Additional context**

thank u so much for this project its a must after a fresh win install ❤️

**Comment by hellzerg** [comment]
You can update to v16.3 to get the feature working!
@techgamers2

**Comment by techgamers2** [comment]
tysm for this change .. although settings are working properly but getting this visual glitch ▼
![visualglitch](https://github.com/hellzerg/optimizer/assets/44696073/585ce4d6-75df-4484-a165-a7c329776f2e)
also i unchecked hide search and restart my pc but tick comes back in optimizer app but the setting persist my search icon is still there thts also maybe a visual bug

**Comment by hellzerg** [comment]
Ignore the checked option. The feature worked?

**Comment by techgamers2** [comment]
yes it did
