### ISSUE TITLE
Damaged Registry Keys Clean

### ISSUE THREAD

**Issue by MrDamenchoo800** [hellzerg/optimizer#448]
Most of the optimizers and performance apps always come with an obligatory subscriptions to do the complex things, like cleaning damaged registry keys.

It should come with a new section on the app named "Registry" where u can analize the registry with the app, and then it will pop up all the damaged keys, just like CCleaner.

I used CCleaner+ with the free trial, but now that its over, i think the high price its just a loss of money, thats why im requesting this.

With that, im pretty sure that the devices where Optimizer is downloaded will be as fast as a gaming pc sometimes, and it would help a lot, thats why i would like this to become a real option in the app.

(Sorry if my grammar is bad, im not an expert at english, but i do my best learning it)

**Comment by Jisll** [comment]
It’s not advisable to use apps like CCleaner to delete “allegedly” damaged registry keys. This can harm your system. There’s a “Registry” section for fixing potential issues. Be cautious!

**Comment by hellzerg** [comment]
As @Jisll stated, this app will never implement such an option, like a registry clenaup because it's actually useless in modern versions of Windows. This can harm way more than actually help your Windows become faster. 

Don't bother with these types of cleanup or apps.

@MrDamenchoo800
