### ISSUE TITLE
Problem with Enhance Privacy

### ISSUE THREAD

**Issue by dev1312000** [hellzerg/optimizer#449]
Used this option "Enhance Privacy" once and it crashed my biometrics opotion. Now the windows startup shows only pin option. Even if the system reads fingerprint, it doesn't open. I am so tensed on this.

**Comment by hellzerg** [comment]
@dev1312000 Reset the option. It's designed like this

**Comment by dev1312000** [comment]
Yes, it worked the second time. first time it got stuck. I am realy sorry for panicking. Actually I read that some people has severe issues because of this and I thought mine has too. 

This tool is extremely powerful and it just boosted my PC for regular performance where I don't even game but use engineering softwares a lot. I think we should make a manual on the saftey measures of usage so people can be careful on what they are really doing. Your wok has been amazing and thank you for making it free.

Sorry once again.

**Comment by dev1312000** [comment]
Yes, it worked the second time. first time it got stuck. I am realy sorry for panicking. Actually I read that some people has severe issues because of this and I thought mine has too.

This tool is extremely powerful and it just boosted my PC for regular performance where I don't even game but use engineering softwares a lot. I think we should make a manual on the saftey measures of usage so people can be careful on what they are really doing. Your wok has been amazing and thank you for making it free.

Sorry once again.

**Comment by hellzerg** [comment]
@dev1312000 Thank you. The check options are not really reflecting the change, but the choice is applied correctly.

**Comment by hellzerg** [comment]
@dev1312000 Thank you. I should mention this in the FAQ section
