### ISSUE TITLE
Windows 11 - Crash after "Checking for requirements"

### ISSUE THREAD

**Issue by PiotrMarzec** [hellzerg/optimizer#450]
1. Launch the app (both as admin, and as user, doesn't matter)
2. "Checking for requirements" window appears
3. "Checking for requirements" dissappears after 2-4 seconds
4. Nothing more happenes
5. App is not running in Task Manager

* Optimizer 16.3
* Removing C:\ProgramData\Optimizer folder doesn't help
* There is no C:\ProgramData\Optimizer\optimizer.log file (only file is optimizer.json, plus a few folders)
* Windows 11 22H2, all up to date
* .NET Framework 1.8.1 installed from https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer
* optimizer.json attached

[Optimizer.json](https://github.com/hellzerg/optimizer/files/13760078/Optimizer.json)

**Comment by floppy-wip** [comment]
Just to let you know, I have a similar problem, but in my case the application does not even start, when I click on it, it does nothing (I tried it as administrator and user) and also the folder that should be located as "C:\ProgramData Optimizer" is not created.

- Optimizer 16.3 and earlier
- There is no "C:\ProgramData\Optimizer" folder
- Windows 11 23H2 Canary (Build 26016.1012)
- NET Framework v4.8.1 installed from https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer

Reproduction steps:
1. Download the app and save it to any folder
2. Start the application (as admin or user, doesn't matter)
3. Nothing happens
4. The application doesn't appear in the Task Manager

**Comment by hellzerg** [comment]
@PiotrMarzec @floppy-wip 

What versions of Windows you running?
Also check that the .Net framework 4.5 and 4.8 is installed.

**Comment by hellzerg** [comment]
Otherwise, i need logs from Event Viewer

**Comment by PiotrMarzec** [comment]
* Windows version listed in the original post: Windows 11 22H2, all up to date as of today
* There is no .Net 4.5 listed at https://dotnet.microsoft.com/en-us/download/dotnet-framework - I've managed to find some older installer, but trying to install any older .Net (4.5, 4.7, 4.7.2) results in "newer version of .Net already installed"
* Event Log file attached
[event_log.zip](https://github.com/hellzerg/optimizer/files/13765790/event_log.zip)

**Comment by hellzerg** [comment]
@PiotrMarzec 

Can you test this experimental version?
[OptimizerTest1.zip](https://github.com/hellzerg/optimizer/files/13766153/OptimizerTest1.zip)

**Comment by PiotrMarzec** [comment]
It works :) Awesome, thank you!

**Comment by hellzerg** [comment]
@PiotrMarzec Okay, so I will release a hotfix version tomorrow

**Comment by hellzerg** [comment]
The issue is fixed. Please update to v16.4.

**Comment by JamminR** [comment]
@hellzerg - WIn10 22h2, new install - after trying to run optimizer 16.4 2-3 times without any success, i came back to the readme.md and noticed the pre-requisites. Went to my Win 'check for updates' and realized several hadn't installed yet, including .Net framework 4.8.1
It would be nice if Optimizer had a way to tell the user the framework is missing. (If it is already supposed to, well, 16.4 did not)
Those users who are less technically inclined would at least be given more direction for self-resolution
(Then again, those less inclinded probably aren't tweaking Windows)

**Comment by hellzerg** [comment]
@JamminR Thing is that because the app is developed on top of the .NET framework itself, if it is missing, it cannot even run to show a message or something. So yeah...
