### ISSUE TITLE
I cant open it on Windows 10

### ISSUE THREAD

**Issue by kook123kook** [hellzerg/optimizer#451]
**Describe the bug**
After i open the last version installer (16.3) in says checking requirements and fetching feed, and after that just crashes, it happened even after windows reset.

**Expected behavior**
I hope i can just use it

**Screenshots**

**Logs**
[Optimizer.log](https://github.com/hellzerg/optimizer/files/13777105/Optimizer.log)

**Desktop (please complete the following information):**
 - Windows version and build --- Edition	Windows 10 Pro
Version	22H2
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

- .NET Frameworks installed --- YES
 - Optimizer version --- 16.3

**Comment by hellzerg** [comment]
The issue is fixed. Please update to v16.4.
