### ISSUE TITLE
I cant open it

### ISSUE THREAD

**Issue by B-l-a-z-e** [hellzerg/optimizer#452]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by B-l-a-z-e** [comment]
When I want to open it it says that the optimizer is already running in the background

**Comment by hellzerg** [comment]
Can you upload the logs?

**Comment by B-l-a-z-e** [comment]
what logs?

**Comment by hellzerg** [comment]
I need the file in here
C:\ProgramData\Optimizer\optimizer.log

**Comment by B-l-a-z-e** [comment]
i dont find the file

**Comment by hellzerg** [comment]
@B-l-a-z-e 

Trying deleting whole folder C:\ProgramData\Optimizer
and download the latest version
