### ISSUE TITLE
problem with smart screen

### ISSUE THREAD

**Issue by failman34** [hellzerg/optimizer#453]
**Describe the bug**
after turning off the smart screen through the application I can no longer change it manually

**Expected behavior**

**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/134507457/4e08b807-2977-424f-ac28-fed8fb57955c)

**Desktop (please complete the following information):**
 - Windows version and build: Windows 11 Pro 23H2; 22631.2861
 - Optimizer version: 16.3

**Comment by hellzerg** [comment]
The issue is fixed. Please update to v16.4.
