### ISSUE TITLE
Modern standby

### ISSUE THREAD

**Issue by nonobrest29** [hellzerg/optimizer#457]
Bonjour,
Merci pour votre travail.
Pouvez-vous rajouter la désactivation de la modern standby.
Merci d'avance

**Comment by hellzerg** [comment]
@nonobrest29 I don't understand your language

**Comment by nonobrest29** [comment]
Good morning,
Thank you for your work.
Can you add deactivation of modern standby.
Thanks in advance

**Comment by hellzerg** [comment]
@nonobrest29 Okay, will do in next version

**Comment by nonobrest29** [comment]
thx

**Comment by hellzerg** [comment]
@nonobrest29 It's been added in v16.5.
