### ISSUE TITLE
Copilot is disabled on 23h2

### ISSUE THREAD

**Issue by dtadptvl** [hellzerg/optimizer#459]
I used to enable some features back when I used Windows 10 and it worked fine.
I decided to upgrade to Windows 11 23H2 for the use of Copilot
However Copilot does not show up despite all of the tricks I do to enable it, I even have no clue for Bing AI on Edge.
Then I disable all the features on Optimizer, Bing AI on Edge is back but still no sign of Copilot.
Gonna do a fresh install to get Copilot back

**Comment by hellzerg** [comment]
@dtadptvl There is a Disable Copilot option. Did you reset it?

**Comment by dtadptvl** [comment]
> @dtadptvl There is a Disable Copilot option. Did you reset it?

Hmm I never touched it. Is there any option to reset everything to its default?

**Comment by hellzerg** [comment]
@dtadptvl 

Reset Enhance Privacy and restart. Maybe it will work, but maybe your windows version does not support Copilot at all.

**Comment by dtadptvl** [comment]
somehow after some restarts, copilot's back
thanks
