### ISSUE TITLE
If Copilot does not show up for no reason, turn on "Disable Copilot AI" then turn it off. Restart your computer and Copilot shall work fine again

### ISSUE THREAD

**Issue by dtadptvl** [hellzerg/optimizer#460]
I encountered loss of Copilot. Here's the way to fix it

**Comment by hellzerg** [comment]
@dtadptvl Maybe this means that Copilot was already disabled on your Windows for unknown reason.

Copilot on Windows is in preview, so maybe that's why

**Comment by dtadptvl** [comment]
@hellzerg I used your app on Win10 before OTA upgrading to Win11. Probably thats why Copilot was disabled
