### ISSUE TITLE
Windows defender is not working

### ISSUE THREAD

**Issue by Staichi54** [hellzerg/optimizer#463]
After changing some options, windows defender is not function anymore, a message appear  and is just a black screen

![Captura de pantalla 2024-01-09 211509](https://github.com/hellzerg/optimizer/assets/73539099/0c983cfb-c740-450d-a174-c4e3544a7a38)

 - Windows 11 23H2
- .NET Framework 4.8.1
 - Optimizer 16.4

**Comment by hellzerg** [comment]
Which options you did enable?
Also, try resetting Smart screen and Enhance Privacy to see if it's working.

@Staichi54

**Comment by Staichi54** [comment]
i just reset the pc, im not gonna enable the enchanted pivacy bc the smart screen is not in my pc

**Comment by Staichi54** [comment]
Happened again, i guess im gonna use the telemetry switches

**Comment by hellzerg** [comment]
@Staichi54 Tell me exactly what did you enable to identify the problem

**Comment by Staichi54** [comment]
Almost everythoing in the win 11 part, except the sensor disabler (even without touch it, the sensor is disabled)

**Comment by hellzerg** [comment]
@Staichi54 You should not enable all the options blindly, because they can cause problems. Especially Smartscreen and Enhance Privacy.

**Comment by hellzerg** [comment]
@Staichi54 Did you disable Defender from Advanced tab too ?

**Comment by Staichi54** [comment]
I downloaded the app again, this is what i always activate

![IMG_20240110_153440_440.jpg](https://github.com/hellzerg/optimizer/assets/73539099/10da3dee-818a-47d8-98f2-787cecbc37a6)

![IMG_20240110_153445_351.jpg](https://github.com/hellzerg/optimizer/assets/73539099/943a7a4f-54a4-4cc7-8e6c-330a3320063d)

**Comment by Staichi54** [comment]
> @Staichi54 Did you disable Defender from Advanced tab too ?

No

**Comment by Staichi54** [comment]
dw guys, i just go to win 10 again, is 1000x times better than 11
