### ISSUE TITLE
Microsoft Intune Company Portal

### ISSUE THREAD

**Issue by krtek2k** [hellzerg/optimizer#464]
Intune Company Portal app wont work with some of the settings enabled. Resetting them or enabling them back wont fix this issue
Syncing is stuck on loading, and checking the device wont work
Microsoft Intune Company Portal 11.2.360.0

 - Windows Pro
 - Optimizer version 16.4

From Intune LOGS:

<![LOG[[Win32App] ----------------------------------------------------- application poller starts. ----------------------------------------------------- ]LOG]!><time="09:19:26.2754999" date="1-12-2024" component="IntuneManagementExtension" context="" type="2" thread="10" file="">
<![LOG[System.Exception: GetAADJoinInfo - Failed to get Azure AD Join information using NetGetAadJoinInformation.  hr:1
   at Microsoft.Management.Services.IntuneWindowsAgent.AgentCommon.AADJoinHelper.GetAADJoinInfo()]LOG]!><time="09:19:26.2754999" date="1-12-2024" component="IntuneManagementExtension" context="" type="2" thread="10" file="">
<![LOG[Failed to check if device is WPJ, ex is System.Exception: GetAADJoinInfo - Failed to get Azure AD Join information using NetGetAadJoinInformation.  hr:1
   at Microsoft.Management.Services.IntuneWindowsAgent.AgentCommon.AADJoinHelper.GetAADJoinInfo()
   at Microsoft.Management.Services.IntuneWindowsAgent.AgentCommon.AADJoinHelper.IsDeviceWPJ()]LOG]!>

<![LOG[AAD token is empty. Fetching new AAD token.]LOG]!><time="09:16:52.2906230" date="1-12-2024" component="DataCollection" context="" type="1" thread="4" file="">
<![LOG[GetAADAuthToken - Domain join information can't be null or empty.]LOG]!><time="09:16:52.2926732" date="1-12-2024" component="DataCollection" context="" type="3" thread="4" file="">

**Comment by krtek2k** [comment]
Found it, its in Windows 10 group > Privacy > Disable Telemetry Services

This has to be enabled :(

**Comment by hellzerg** [comment]
Unfortunately @krtek2k
