### ISSUE TITLE
Optimiser 16.4 messed up my pc

### ISSUE THREAD

**Issue by kobaalt** [hellzerg/optimizer#471]
**Describe the bug**
after clicking "restart to apply changes", my pc showed no issue until i was faced with the lock screen where when i pressed spacebar/dragged the screen up, my screen blurred as if the login screen was loading but just stayed like that for around 30 seconds before snapping straight back to the start displaying the time. because of this issue i had to enter the recovery settings screen and factory reset my pc which ended up being very time consuming.

**Expected behavior**
i expected my pc to restart and windows function without any issue

**Screenshots**
here were my settings before applying the changes
![image2](https://github.com/hellzerg/optimizer/assets/138726602/0e6b6e32-e8ab-49a5-a1aa-6e350215030c)
![image](https://github.com/hellzerg/optimizer/assets/138726602/33f463a2-fb86-42e4-80b2-28c6a1623c5d)

**Logs**
unfortunately deleted due to factory reset, sorry :(

**Desktop (please complete the following information):**
Windows 11 Home
.NET Frameworks installed (4.8.09032)
Optimizer version 16.4

**Comment by hellzerg** [comment]
Hello, I don't think Optimizer caused this behavior. This is the first time that kind of issue pops up.

Did you try to restart your PC from the lock screen, to see if the problem would persist upon restart?

**Comment by krtek2k** [comment]
I have not experienced any kind of unexpected results on multiple PCs and Windows 10. Might be W11 related.

**Comment by kobaalt** [comment]
> Hello, I don't think Optimizer caused this behavior. This is the first time that kind of issue pops up.
> 
> Did you try to restart your PC from the lock screen, to see if the problem would persist upon restart?



> Hello, I don't think Optimizer caused this behavior. This is the first time that kind of issue pops up.
> 
> Did you try to restart your PC from the lock screen, to see if the problem would persist upon restart?

yes i restarted my pc multiple times

**Comment by hellzerg** [comment]
Did you try to reset all the options you flipped back off and restart?

**Comment by kobaalt** [comment]
> Did you try to reset all the options you flipped back off and restart?

no, i couldnt do that because i was unable to log into my pc

**Comment by Animl23** [comment]
> Hello, I don't think Optimizer caused this behavior. This is the first time that kind of issue pops up.
> 
> Did you try to restart your PC from the lock screen, to see if the problem would persist upon restart?

YES IT FUCKING DID. I CAN"T ACCESS ANYTHING.....you fucking MORONS

**Comment by hellzerg** [comment]
Your PC is a POS machine? What do you mean? @Animl23

**Comment by Animl23** [comment]
Go fuck your punk ass with gkass you worthless cuntOn Mar 1, 2024, at 1:12 AM, deadmoon ***@***.***> wrote:﻿
Your PC is a POS machine? What do you mean? @Animl23

**Comment by hellzerg** [comment]
@kobaalt what's your status about this issue?

**Comment by kobaalt** [comment]
i recovered all my files after the factory reset and never used optimiser again
