### ISSUE TITLE
вирус.

### ISSUE THREAD

**Issue by oltko** [hellzerg/optimizer#472]
При скачивании вирус w 11 23h2 защитник заблокировал скачивание.

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by Rusmer** [comment]
Open source virus?
It can't be, you can check it yourself by looking at the source code.

**Comment by hellzerg** [comment]
Yes. it's 100% false positive. Just make sure that you download the official app from this github repo. You can also check the Sha256 hash to make sure you are fine.
