### ISSUE TITLE
Stuck while executing fetching feed

### ISSUE THREAD

**Issue by djerryz** [hellzerg/optimizer#477]
Stuck while executing fetching feed:
![image](https://github.com/hellzerg/optimizer/assets/24947060/1a4ec4e3-925a-4ec9-8597-1efb47a5eb1f)

**Comment by hellzerg** [comment]
@djerryz Slow internet probably. How long it's stuck there?

**Comment by KemonDream** [comment]
Hi, it infinitely stuck there. What server it connects to?

**Comment by sJackee** [comment]
Hi, use VPN
