### ISSUE TITLE
Garbled Simplified Chinese Characters Displayed

### ISSUE THREAD

**Issue by devieed** [hellzerg/optimizer#478]
Description:
The Optimizer application's interface language was set to Simplified Chinese, but it displayed garbled characters instead. This issue occurred consistently throughout the interface.

Expected Behavior:
The application should accurately display Simplified Chinese characters.

Screenshots
![fff](https://github.com/hellzerg/optimizer/assets/161264781/0177024f-d704-49e0-869d-7656c3b81dd4)

Logs
`
Windows 11 Pro - 23H2 (64-bit)
Optimizer 16.4 - .NET Framework 4.8 - Experimental build: False

[ERROR] [2/26/2024 8:37:01 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [2/26/2024 8:46:56 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [2/26/2024 8:52:08 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()

[ERROR] [2/26/2024 8:58:18 AM] in function [Integrator.TakeOwnershipExists]
Object reference not set to an instance of an object.

   at Optimizer.IntegratorHelper.TakeOwnershipExists()
`

Operating System: Tiny version of Windows 11 (Version: 23H2, Build: 22631.3155)

Thank you for your attention to this matter.

**Comment by stevenhobs** [comment]
This is caused by the os self. You need to add the Chinese fonts and change the locale. 这是系统本身的问题，用的tiny11吧，添加回中文字体，控制面板改区域。
