### ISSUE TITLE
edge browser is managed by your organization, I need a way to revert only these changes so i can use Autofill in edge browser again as resetting the settings in optimizer didn't revert it

### ISSUE THREAD

**Issue by FluXolo** [hellzerg/optimizer#480]
**Describe the bug**
i can't use autofill anymore as it got disabled when i enabled enhance privacy in optimzer i think

**Expected behavior**
when i disable enhance privacy and disable (disable spell checking) the autofill should work again and the message in title goes away

**Screenshots**
![image](https://github.com/hellzerg/optimizer/assets/74671564/16f4bdf1-7665-40e5-abd0-2de942542e09)
![image](https://github.com/hellzerg/optimizer/assets/74671564/9cd78ac7-8b79-442c-9c1f-5dcb5d0400af)
![image](https://github.com/hellzerg/optimizer/assets/74671564/c280bfa4-35dd-410a-8d26-754474e6fcba)

**Logs**

[Optimizer.log](https://github.com/hellzerg/optimizer/files/14547336/Optimizer.log)

**Desktop (please complete the following information):**
 - Windows 11, version 23H2
 - Optimizer-16.4.exe

**Comment by hellzerg** [comment]
I will issue a fix as soon as possible, thanks for the detailed info.

**Comment by hellzerg** [comment]
@FluXolo You should be fine now.

**Comment by lovetingyuan** [comment]
still have the problem
