### ISSUE TITLE
16.4 - Repeated Crash if single attempt made to run without .Net 4.8.1

### ISSUE THREAD

**Issue by JamminR** [hellzerg/optimizer#481]
**Describe the bug**
Optimizer continously crashes at startup if run once before .Net Framework 4.8.1 is installed - even after installation of .Net
Downloaded Optimizer 16.4 exe from hellzberg github repository.
Ran Optimizer as admin - asked to confirm running unknown publisher app, then nothing. No window. No Windows Applications event log entry. Tried several times.
Checked readme.md and FAQs. Saw readme requirements '.net framework 4.8.1'
Realized I had not run Windows updates - ran windows updates - though it mentioned a .net framework 4.8.1 update of some sort....
after PC restart, application still would not run.
Went to microsoft downloads for .net and got runtime framework for .net 4.8.1.
Installed. Restarted PC for good measure
Re-Ran optimizer - after prompt to run as admin - still no window. No event log.
In searching of previous Issues here for crash at startup - found a randome recommendation step to delete C:\programdata\Optimizer and try again.
Deleted that folder.
Re-Ran Optimizer.
Now runs fine

**Expected behavior**
1) Running without prerequisite installed just throw some error other than 'nothing' crash.
2) Running again after prerequisite installed should work without manually deleting c:\programdata\Optimizer

**Screenshots**
N/A

**Logs**
None - were deleted in order to get application working.

**Desktop (please complete the following information):**
 - Windows version and build = Win 10 Pro 22H2 - Fresh install.
- .NET Frameworks installed = Not at first, then 4.8.1
 - Optimizer version = 16.4

**Comment by hellzerg** [comment]
You should have kept the logs before deleting the folder. It would help.

**Comment by JamminR** [comment]
That may be true, but until i submitted the bug which has the prompt to attach and where the logs were, i didn't know specific logs existed or where they were. Chicken - egg. Even the closed issue in which I saw the 'delete the entire folder' suggestion existed didn't have logs location, just a continued developer asking for them without telling the submitter where they were/how to get that info.
I'm presume you as a helper/developer might be able to replicate the issue by uninstalling .Net - deleting the optimizer programdata folder, then performing my steps as listed in bug report.
I'm moving on - i'm mid-rebuild of a home prod system and have hours of work remaining.

**Comment by hellzerg** [comment]
@JamminR Thing is the .NET apps do not tell you that the framework is missing from the system when running them, nor produce any detailed error message, because it can't be run in the first place. So yeah...
