### ISSUE TITLE
INTERNET run without proxy

### ISSUE THREAD

**Issue by tuffss** [hellzerg/optimizer#483]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tuffss** [comment]
IM TRYING TO CUT TIES WITH AZURE ! I DONT HAVE A  BUSINESS ANYMORE ,I HAVE BEEN TRYING FOR A MONTH AND I CANT FIND ON LINE TO ERASE EVERTHING ,LIKE MACHING ,APPS ADD .. SO I THOULT IF I NOY CONNECT WITH A PROXY,,,THAT WOULD STOP AZURE FROM RUNNING...?????

**Comment by tuffss** [comment]
USA

**Comment by hellzerg** [comment]
I don't understand what exactly do you want. @tuffss
