### ISSUE TITLE
Problèmes d'accentuation dans la version française du logiciel "Optimizer"

### ISSUE THREAD

**Issue by Anita6623** [hellzerg/optimizer#484]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hellzerg** [comment]
Can you describe the problem in english please?

**Comment by Joren-vanGoethem** [comment]
he's saying the accents are wrong in french but who cares

**Comment by hellzerg** [comment]
@Anita6623 we need contributors for fixing the french translation

**Comment by Anita6623** [comment]
Hi,
I can help you with the English/French translation.
Best regards

**Comment by Error-Cezar** [comment]
@Anita6623 thats next level yapping
