### ISSUE TITLE
I cannot open Microsoft store and setting in Windows 11

### ISSUE THREAD

**Issue by VaxM** [hellzerg/optimizer#485]
I accidently messed up the UWP apps unistaller

**Comment by hellzerg** [comment]
You can hopefully restore all UWP apps @VaxM

**Comment by VaxM** [comment]
> You can hopefully restore all UWP apps @VaxM

how can i do it though. i have tried using powershell but didnt work

**Comment by hellzerg** [comment]
@VaxM Did you follow the guide that restores all UWP apps?
