### ISSUE TITLE
Snappy File Driver would seal the deal for this Win optimizer!

### ISSUE THREAD

**Issue by JayRad111** [hellzerg/optimizer#486]
Snappy driver has been a huge savior for me in the last year. If not already considered, it should be looked into! Lightweight, quick, simple, and more and more digestible with each use. Thank god for p2p!

**Comment by Squtzy** [comment]
> Snappy driver has been a huge savior for me in the last year. If not already considered, it should be looked into! Lightweight, quick, simple, and more and more digestible with each use. Thank god for p2p!

Didn't the original creator sell the project or something so it is no longer open-source and/or no longer really that safe to use?

**Comment by hellzerg** [comment]
@JayRad111 @Squtzy 
This app will not be included for the reasons stated above. Sorry for the inconvenience.
