### ISSUE TITLE
Widget meteo and news disappear anymore...

### ISSUE THREAD

**Issue by sypqys** [hellzerg/optimizer#487]
Hello !

I don't understand why, I want to restore and have my widget...

Win 11 Home 23H2
- .NET Frameworks 4.8
 - Optimizer v. 16.4

![ShareX_o9k6pMGtSQ](https://github.com/hellzerg/optimizer/assets/27967268/c2ef00cf-f15e-4770-8d07-08779efe7159)

**Comment by hellzerg** [comment]
I don't understand what do you mean

**Comment by sypqys** [comment]
![0 QQdbYOaHJFZShdNY](https://github.com/hellzerg/optimizer/assets/27967268/0baa1163-91f2-46b3-8f37-f317d4c50588)

this widget disappear but I have correct this issue...
