### ISSUE TITLE
SERIOUS bug when deleting startup items!

### ISSUE THREAD

**Issue by CN-zhouyk** [hellzerg/optimizer#489]
**Describe the bug**
Startup items got wrongly deleted.

**Expected behavior**
The program should delete the items I chose, instead of other random items.
I suspect something went wrong when ordering the items by their names, that's when it occurred.

**Desktop (please complete the following information):**
Windows 10 Pro - 22H2 (64-bit)

**Comment by hellzerg** [comment]
@CN-zhouyk Nice finding, it will be fixed soon.

**Comment by hellzerg** [comment]
It's fixed in latest v16.5 @CN-zhouyk
