### ISSUE TITLE
IF ACTIVATE WINDOWS SHOWS UP FOR YOU AFTER ACTIVATING ANYTHING IN THIS TRY THIS

### ISSUE THREAD

**Issue by MrTwatWaffle** [hellzerg/optimizer#491]
If your "Activate Windows" This keeps showing up after you activate sum in this enter this command in PowerShell as admin:

sfc /scannow

should detect 1 issue and fix it, it has fixed the activate windows thing for me because of this program

**Comment by hellzerg** [comment]
This is not related to Optimizer.

**Comment by MrTwatWaffle** [comment]
the optimizer has caused that issue for me my b ig
