### ISSUE TITLE
microsoft edge search suggestions

### ISSUE THREAD

**Issue by TheSrBig** [hellzerg/optimizer#497]
I don't know what happened but the function that suggests me a page that I have visited before is not there anymore, for example, if I want to go to studiolab.sagemaker.aws, I have to write the complete page, and before just writing studi... it already told me which page to go, and I don't have that function anymore.

**Comment by hellzerg** [comment]
@TheSrBig I will investigate it

**Comment by hellzerg** [comment]
@TheSrBig It's the Disable Edge Telemetry option.
