### ISSUE TITLE
Few wishes

### ISSUE THREAD

**Issue by mrkaban** [hellzerg/optimizer#5]
Make the window "About the program" and indicate in it a license.

As far as I understand, the license of the program gnu gpl?

Not enough detailed description of each button! Please describe help. A program is potentially dangerous without such a description.

It is advisable to change the computer restart to apply the settings.

What about translation into other languages? I can try to help with the translation into Russian.

Added to my site about free software, it is in Russian, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/optimizer-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C.html).

**Comment by hellzerg** [comment]
Hello

We can work together to translate the program into various languages.

Where do you wish to communicate more private so we can start working on translations?

**Comment by mrkaban** [comment]
I am ready to help translate into Russian, only the functionality of some buttons is not clear to me.

It would be convenient for me to communicate via e-mail, here is my e-mail address info@mrkaban.ru.

**Comment by mrkaban** [comment]
I sent you a transfer, for some reason it never appeared = (

**Comment by hellzerg** [comment]
What transfer?

**Comment by mrkaban** [comment]
You wrote to me on the indicated mail and I sent a translation in response. I can't find the answer, since it was sent most likely from info @ mrkaban, and the site was then on a different hosting.
![111](https://user-images.githubusercontent.com/14289360/119355586-a3f61e00-bccf-11eb-9ece-8913ae62085a.png)

**Comment by hellzerg** [comment]
I will need updated translations because version after version, new functions have been implemented.

**Comment by mrkaban** [comment]
Throw off here what you need to translate, I will try to translate again.

**Comment by hellzerg** [comment]
I have some things going on right now, so we will do the translation roughly in a month.
Thanks for your interest and time!

**Comment by hellzerg** [comment]
Hello, you could start translating the buttons and text messages in each tab interface.
There are too much.

**Comment by mohammadwildali** [comment]
I would i help translating to arabic ..
justsad.eng@gmail.com.

**Comment by mrkaban** [comment]
So you throw off here what you need to translate. I already sent via mail many years ago and the translation was eventually lost.

**Comment by hellzerg** [comment]
So, here is what needs to be translated.
More will come in following days.
[optimizer-translate.txt](https://github.com/hellzerg/optimizer/files/6574269/optimizer-translate.txt)

**Comment by mrkaban** [comment]
Here is the translation into Russian. I would like to look at the translation in the program before the release is published for possible corrections.
[optimizer-translate.txt](https://github.com/hellzerg/optimizer/files/6575057/optimizer-translate.txt)

**Comment by hellzerg** [comment]
Of course, it will be tested thoroughly. I am gonna need extra text to be translated soon. That is the basics.

**Comment by hellzerg** [comment]
This is a test build for RU translation.
You can instantly change the language from Options.

https://github.com/hellzerg/optimizer/raw/master/lab/Optimizer-RU-Test.exe

Also, I'd like a few more translations, here is the extra text file.
[optimizer-translate-extra.txt](https://github.com/hellzerg/optimizer/files/6580614/optimizer-translate-extra.txt)

**Comment by mrkaban** [comment]
Here, translated, the first corrected. The only thing I'm worried about is that suddenly not all the inscriptions will fit.
[optimizer-translate.txt](https://github.com/hellzerg/optimizer/files/6581662/optimizer-translate.txt)
[optimizer-translate-extra.txt](https://github.com/hellzerg/optimizer/files/6581663/optimizer-translate-extra.txt)

**Comment by hellzerg** [comment]
Have you tried the version I've sent you?

**Comment by mrkaban** [comment]
Yes, I made a couple of phrases longer. The problem of translation into Russian is that some short two words in English can be translated as 5 words in Russian, and when trying to shorten, you need to check visually that the meaning is not lost.

**Comment by mohammadwildali** [comment]
I can not help with russianonly english to arabichere is the extra translation to arabic


| Use default folder icon | إستخدام الأيقونة الإفتراضية للمجلد |
| Download website icon (favicon) | تحميل أيقونة الموقع (favicon) |
| No icon | لا يوجد أيقونة |
| DNS Cache is being generated, try again later! | DNS Cache قيد الإنشاء,يرجى المحاولة لاحقا |
| DNS Cache is running | DNS Cache قيد الإستخدام |
| No backups found! | لا يوجد نسخة إحتياطية ! |
| Startup Manager | مدير بدء التشغيل |
| PC Cleaner | تنظيف الجهاز |
| Pinger Tool | أداة البنغ |
| HOSTS Editor | محرر  HOSTS |
| Apps Downloader | تحميل التطبيقات |
| Restart Explorer | إعادة تشغيل المتصفح |
| Exit       | خروج |



    On Wednesday, June 2, 2021, 12:23:15 AM GMT+3, deadmoon ***@***.***> wrote:  
 
 


This is a test build for RU translation.
You can instantly change the language from Options.

https://github.com/hellzerg/optimizer/raw/master/lab/Optimizer-RU-Test.exe

Also, I'd like a few more translations, here is the extra text file.
optimizer-translate-extra.txt

**Comment by mohammadwildali** [comment]
i can not help with russian
    On Wednesday, June 2, 2021, 05:50:23 AM GMT+3, Алексей ***@***.***> wrote:  
 
 


Here, translated, the first corrected. The only thing I'm worried about is that suddenly not all the inscriptions will fit.
optimizer-translate.txt
optimizer-translate-extra.txt

**Comment by hellzerg** [comment]
Man, I can't replace your corrections in my file, I don't understand a thing now.
Take the translation list and correct as necessary. Be careful not to break the format of the JSON.

[RU.zip](https://github.com/hellzerg/optimizer/files/6583328/RU.zip)

After your corrections, it's all ready.

**Comment by hellzerg** [comment]
@mohammadwildali 
You need to translate the big file too.

**Comment by mrkaban** [comment]
I meant to look in the program, but okay, let's assume that everything is fine, if anything, I will check it at release and correct it again for the next version.

> Man, I can't replace your corrections in my file, I don't understand a thing now.
> Take the translation list and correct as necessary. Be careful not to break the format of the JSON.
> 
> [RU.zip](https://github.com/hellzerg/optimizer/files/6583328/RU.zip)
> 
> After your corrections, it's all ready.

I meant to look in the program, but okay, let's assume that everything is fine, if anything, I will check it at release and correct it again for the next version.

**Comment by hellzerg** [comment]
@mrkaban 

Actually, we gonna need to translate the help messages over each switch.

**Comment by mrkaban** [comment]
Ok, throw off what you need to translate here, and I'll try to do it.

My interest is in more free software with interface translation into Russian, as I run a large free software portal (as I mentioned in the very first post).

**Comment by hellzerg** [comment]
Okay, here it is.

[optimizer-help-tips.txt](https://github.com/hellzerg/optimizer/files/6583404/optimizer-help-tips.txt)

**Comment by mrkaban** [comment]
Translated
[optimizer-help-tips.txt](https://github.com/hellzerg/optimizer/files/6583791/optimizer-help-tips.txt)

**Comment by hellzerg** [comment]
Okay, v8.4 is out, with full Russian localization.
If any problems occur, notify me.

**Comment by mohammadwildali** [comment]
I'll start translating to arabic on weekends after 48 hours 

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 2, 2021 at 3:53 PM, ***@***.***> wrote:   


Closed #5.

**Comment by mrkaban** [comment]
I made edits to the main translation file =) Apparently they did not notice.
[optimizer-translate.txt](https://github.com/hellzerg/optimizer/files/6584807/optimizer-translate.txt)

**Comment by mohammadwildali** [comment]
I'm using my mobile phone now .This is how words appears..When i get a chance very soon .i'll use a pc and start reading all emails and start translating to arabic....

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 2, 2021 at 4:20 PM, ***@***.***> wrote:   


I made edits to the main translation file =) Apparently they did not notice.
optimizer-translate.txt

**Comment by hellzerg** [comment]
@mrkaban Could you send me exactly the corrected words, with english next to them, so I can easily replace them?

**Comment by hellzerg** [comment]
@mohammadwildali Okay, whenever you can start the translation.

**Comment by mrkaban** [comment]
I made changes, I attach the file!
[RU.zip](https://github.com/hellzerg/optimizer/files/6585647/RU.zip)

**Comment by hellzerg** [comment]
Okay, I'll correct them in next version.

**Comment by hellzerg** [comment]
Disable Media Player Sharing needs shorter translation.

**Comment by mrkaban** [comment]
Let's write "Отключить Media Player Sharing". It's all right?

**Comment by hellzerg** [comment]
Before the correction it was shorter.

**Comment by mrkaban** [comment]
Then so "Откл. Media Player Sharing"

**Comment by hellzerg** [comment]
Отключить обмен медиаплеером. Better?

**Comment by mrkaban** [comment]
Yes!

**Comment by hellzerg** [comment]
Done.
