### ISSUE TITLE
Aplications do not respond in short period of time

### ISSUE THREAD

**Issue by TheSrBig** [hellzerg/optimizer#500]
I have a big problem on Windows that when playing for example Minecraft and is a problem that really bothers me too much is that when playing as it gets for half a second or less, it appears that the application or the game "does not respond", but automatically then that is removed, and that happens as a lapse of time like every 20 seconds. This happens and it is very annoying, it happens with all applications, even "Windows + R", and before this did not happen to me. and it didn't happen before, before using the program.

https://streamable.com/ywegs2
https://streamable.com/wke9h4

![image](https://github.com/hellzerg/optimizer/assets/89810837/3c13b42a-1698-47d8-8d27-eacb99a23419)
whyyyyyy

**Comment by hellzerg** [comment]
@TheSrBig Hello. Have you tried resetting the options you had enabled? That is really strange.
