### ISSUE TITLE
All my folders and some desktop programs are deleted

### ISSUE THREAD

**Issue by amirshaker000** [hellzerg/optimizer#501]
![image](https://github.com/hellzerg/optimizer/assets/74258437/91e64a5a-cc6e-4739-acb8-7f60cf7f9979)
When I restarted my computer, the desktop was empty
and cant find the desktop folder in user
![Uploading image.png…]()

[Optimizer.log](https://github.com/hellzerg/optimizer/files/15251706/Optimizer.log)

 - windows 11 pro
- .NET Frameworks 4.8
 - 13.9

**Comment by hellzerg** [comment]
@amirshaker000 I suspect from your logs that you enabled the Uninstall OneDrive, right?
