### ISSUE TITLE
Remove Diagnostics from Enhance Privacy

### ISSUE THREAD

**Issue by Zacgamingproalt** [hellzerg/optimizer#503]
Hi I wish that Enhance Privacy doesn't disable diagnostics or is an extra option under it. The reason that I don't want to disable it is that it  disables troubleshooters, correct me if I'm wrong. If I am do you know a possible solution. Besides of this Optimizer is great! Thanks for creating it! Also thanks in advance!

**Comment by hellzerg** [comment]
@Zacgamingproalt 

Did you check this setting?

https://www.tenforums.com/attachments/tutorials/404442d1706334999t-turn-off-automatic-recommended-troubleshooting-windows-10-a-recommended-troubleshooting.png

**Comment by Zacgamingproalt** [comment]
Yes I did and just noticed this, sorry for posting an issue.
![image](https://github.com/hellzerg/optimizer/assets/169378045/f2033340-4f71-4e66-838a-7f6898cbad1f)
