### ISSUE TITLE
Lateral Bar and Copilot Button doenst show

### ISSUE THREAD

**Issue by TheSrBig** [hellzerg/optimizer#507]
![image](https://github.com/hellzerg/optimizer/assets/89810837/a45fb52c-0c47-40aa-ac77-fdad4d6f70b6)
![image](https://github.com/hellzerg/optimizer/assets/89810837/a56b7600-edab-4eb1-8679-b1133b1a2af1)

what option is making this...

**Comment by hellzerg** [comment]
Apparently it has to do with Disabling Edge telemetry and/or Copilot. Havw you tried resetting them ?
@TheSrBig
