### ISSUE TITLE
[Rename Request] "Disable Search" option should be changed to " Disable Search Indexing "✅

### ISSUE THREAD

**Issue by TecnikOfficial** [hellzerg/optimizer#508]
**Is your feature request related to a problem? Please describe.**
I have seen people get confused when seeing disable search option . they think it will disable windows search functionality completely
<details>
<summary>Screenshot</summary>
windows 10 
<br>
<img src="https://github.com/hellzerg/optimizer/assets/44696073/234eba38-7d33-419b-9291-7146be764ba7">
</img>
</details>

**Describe the solution you'd like**
"Disable Search "option should be changed to " Disable Search Indexing "

**Describe alternatives you've considered**
I know its mentioned in "disable search " description that it disables search service which is theoretically right but many people thinks that it will also disable whole search functionality . if possible - put disables windows search service (search indexing) in tweak description.

**Additional context**
I know its a small issue that doesn't impact the program functionality . but do consider my request if possible ( thank you )❤️

**Comment by hellzerg** [comment]
I am including the renaming in the upcoming version.
