### ISSUE TITLE
Ransom:BAT/DisableDefender.B!dha !!!

### ISSUE THREAD

**Issue by DriTAllan** [hellzerg/optimizer#509]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by DriTAllan** [comment]
Ransomware found today ! Ransom:BAT/DisableDefender.B!dha

**Comment by DriTAllan** [comment]
Ransomware found today ! - Ransom:BAT/DisableDefender.B!dha

**Comment by hellzerg** [comment]
False positive obviously.

**Comment by WAZOWSKY-1** [comment]
Hola, descargué el archivo Hellzerg Optimizer en github y Microsoft Defender colocó una ventana que decía Ransom:BAT/DisableDefender.B!dha
estado: error
Artículos afectados:
D:\Juego de PC\Descargas\optimizer-master.zip
D:\Pc Game\Descargas\optimizer-master.zip->optimizer-master/Optimizer/Resources/Scripts/DisableDefenderSafeMode1903Plus.bat
archivo web: D:\Juego de PC\Descargas\optimizer-master.zip|about:internet|pid:6288,ProcessStart:133678810057246067
