### ISSUE TITLE
Problem with disabling defender 

### ISSUE THREAD

**Issue by tharun0120** [hellzerg/optimizer#51]
when using the disable windows defender it works on start up i can see in the settings defender has been in some way made to think that there is another antivirus software present but after sometime like 5mins after startup defender gains control again and works as normal. Am I doing something wrong? It would be great if the defender stays disabled!

**Comment by hellzerg** [comment]
Which build of Windows 10 are you using?

**Comment by tharun0120** [comment]
21H1 Build 19043.1081

**Comment by hellzerg** [comment]
https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/security-malware-windows-defender-disableantispyware

**Comment by tharun0120** [comment]
So its not gonna work. Thats sad! Is there any other workaround. Even i did the disable anti spyware registry edit before using your optimizer but i didnt even get that message like your anti virus manages the security but using yours its chnaging it

**Comment by hellzerg** [comment]
There is a way, but you need to restart into safe-mode and disable Defender services.

**Comment by tharun0120** [comment]
But disabling defender services require like trusted installer access right it would prerty much say access denied! I havent tried disabling it in safe mode. I will give it a try!!

**Comment by hellzerg** [comment]
[DefenderDisable-SafeMode.zip](https://github.com/hellzerg/optimizer/files/6719870/DefenderDisable-SafeMode.zip)

Try running this BAT script as admin in safe-mode.
It should disable Defender completely.

**Comment by tharun0120** [comment]
Thanks!

**Comment by tharun0120** [comment]
it works Thanks!!
