### ISSUE TITLE
 Ransomware found today ! Ransom:BAT/DisableDefender.B!dha

### ISSUE THREAD

**Issue by DriTAllan** [hellzerg/optimizer#510]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by DriTAllan** [comment]
Ransomware found today ! Ransom:BAT/DisableDefender.B!dha

**Comment by DriTAllan** [comment]
Ransomware found today ! Ransom:BAT/DisableDefender.B!dha

**Comment by DriTAllan** [comment]
Ransomware found today ! Ransom:BAT/DisableDefender.B!dha

**Comment by techgamers2** [comment]
its false positive . as this program has ability to disable defender which is actual hidden behind command so u dont need to worry about accidently toggling it

**Comment by hellzerg** [comment]
False positive obviously.

**Comment by WAZOWSKY-1** [comment]
Hello, I downloaded the Hellzerg Optimizer file on github and Microsoft Defender placed a window saying Ransom:BAT/DisableDefender.B!dha
status: error
Affected items:
D:\Pc Game\Downloads\optimizer-master.zip
D:\Pc Game\Downloads\optimizer-master.zip->optimizer-master/Optimizer/Resources/Scripts/DisableDefenderSafeMode1903Plus.bat
webfile: D:\Pc Game\Downloads\optimizer-master.zip|about:internet|pid:6288,ProcessStart:133678810057246067
