### ISSUE TITLE
optimizer 16.5 marked as avirus by avast 

### ISSUE THREAD

**Issue by m0usaa** [hellzerg/optimizer#514]
when i download last version of the program it always blocked by avast i cant run it anymore ....... may you fix this please

**Comment by techgamers2** [comment]
YA its recently been flagged by microsoft edge browser also with its inbuilt smartscreen protection 
<details>
<summary>Screenshot for detection : </summary>
Edge v126
<br>
<img src="https://github.com/hellzerg/optimizer/assets/44696073/5c02ea2e-3af2-4543-8674-b0945811bcc7">
</img>
</details>
<details>
<summary>Reported As false positive : </summary>
Edge v126
<br>
<img src="https://github.com/hellzerg/optimizer/assets/44696073/ba70990d-a224-4407-8b1c-21d631ae2a7f">
</img>
</details>
@hellzerg report as false positive [Microsoft Smartscreen Feedback](https://feedback.smartscreen.microsoft.com/smartscreenfaq.aspx#)

**Comment by hellzerg** [comment]
@TecnikOfficial 

Thanks for the support. I hope the problem is fixed by now!
