### ISSUE TITLE
Enabling "Enhance Privacy" disables fingerprint for log in.

### ISSUE THREAD

**Issue by wDRxxx** [hellzerg/optimizer#515]
After enabling "Enhance Privary" I can't use fingerprint on my laptop. This problem is actual since 2022 (#208 #188).

**Comment by hellzerg** [comment]
@wDRxxx 

I think the Biometrics should be disabled after choosing "Enhance Privacy tweak".
The description states it clearly.
I will update the FAQ section also about this.
