### ISSUE TITLE
Add back "Uninstall Microsoft Snipping Tool, also known has ScreenSketch

### ISSUE THREAD

**Issue by 8ternity** [hellzerg/optimizer#517]
**Is your feature request related to a problem? Please describe.**
I remember the option was there in the past to uninstall the new Microsoft Capture Tool, now with Powersheell, it's doesn't work too. The software still present in the system when we hit PRINTSCREEN button. Can't uninstall it. Frustrating.

**Describe the solution you'd like**
Have the option into Windows 11 optimisation to disable the Snipping Tool/ScreenSketch

Thank a lot and great work! Nice tool!

**Comment by hellzerg** [comment]
@8ternity 

I think you can uninstall it through UWP Apps section?

**Comment by 8ternity** [comment]
@hellzerg Unfortunately no. It's still installed and i don't see it into the UWP Apps section "Windows 11".

Here some captures

![2024-07-06_20h35_40](https://github.com/hellzerg/optimizer/assets/16780421/75ab76d2-c09f-4a05-8a73-c7e53f4080fb)

![2024-07-06_20h36_11](https://github.com/hellzerg/optimizer/assets/16780421/62aea050-d9b7-4f58-9c4e-6798e4572b62)

![2024-07-06_20h36_32](https://github.com/hellzerg/optimizer/assets/16780421/933151f1-8773-4371-95e0-d836ed9d6f81)

I remember in the past it was listed. It's look like Windows has found another way to install it without listing it after Windows updates or something else.
