### ISSUE TITLE
is detected as virus and trojan

### ISSUE THREAD

**Issue by AshiK6907X** [hellzerg/optimizer#519]
when i used the old version 15.5 for a quite a time now after i downloaded it  i scanned it virus total it detected as trojan but no problem had with it but now new version as released i downloaded it and windows started to block it as virus and unable to download also so i guess it has virus or something it got more 7/41 in virus total i forgot to take ss of virus total but i uploaded of windows defender 

i think it is not safe now,are you guys also face same issue?
![optimizer blocked](https://github.com/hellzerg/optimizer/assets/100853195/6b630437-3f8d-427e-8b72-bd0e1c12072d)
![optimzer blocked removed](https://github.com/hellzerg/optimizer/assets/100853195/4e674012-81d2-4446-9ffc-a282e668255d)

**Comment by hellzerg** [comment]
It's false positive. Better report it as safe if you want to help.

**Comment by BNX070** [comment]
for me it's showing this: Trojan.KillAV

**Comment by AshiK6907X** [comment]
> It's false positive. Better report it as safe if you want to help.

Sure how to do it in proper way?

**Comment by AshiK6907X** [comment]
> for me it's showing this: Trojan.KillAV

i also seen that does your defender blocking it  my is latest btw

**Comment by master7720** [comment]
If this were a virus, it wouldn't have 13k stars. Plus, the source code is fully open source, so if there was a virus, someone would have already spotted it in the code.

**Comment by hellzerg** [comment]
This application is out on the wild since at least 2016 and is trusted like a rock.

**Comment by vfggf95565** [comment]
https://www.virustotal.com/gui/file/8b29c9349e7a814e30cce1cfb788f5a21740c798268b0a45ab805195faad9105

**Comment by master7720** [comment]
> 16.6 : https://www.virustotal.com/gui/file/8b29c9349e7a814e30cce1cfb788f5a21740c798268b0a45ab805195faad9105 16.5 : https://www.virustotal.com/gui/file/26c64c2fafcd264b8130462ff6e40a6498ec6937fe95d5e83964388ae9597c4d

false positives are very common with virus total

**Comment by kalimaenergy** [comment]
Same issue on my side with ESET Antivirus, since 16.6 release.

**Comment by master7720** [comment]
> Same issue on my side with ESET Antivirus, since 16.6 release.

report it as a false positive

**Comment by bynafrez08** [comment]
for those who are curious what this application does at the system and network level. I have run it in a sandbox with Windows 10 and these are the results it gave me: 

https://app.any.run/tasks/5ef2574c-2e61-4282-90a1-f57561e608f4

The principle detects malicious activity at the process level, but 0 threats at the end of the .exe file execution.

![image](https://github.com/hellzerg/optimizer/assets/77644245/27ae3a49-f403-45e8-899b-57442a0b1474)

**Comment by hellzerg** [comment]
@bynafrez08 The part that says it's accessing raw profile github data, is the version check I do with the version.txt in the repo itself
