### ISSUE TITLE
Problem with Enchance Privacy

### ISSUE THREAD

**Issue by alfeinsl** [hellzerg/optimizer#521]
I have a problem with Enhanced Privacy. I can't turn it off. I've already toggled the switch off and restarted, but the settings still show 'Some of these settings are managed by your organization.'

**Comment by alfeinsl** [comment]
Problem fix after I try from this site
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-some-of-these-settings-are-managed-by/d4cb2836-be2d-42c4-889f-6ece8c6de0e5

**Comment by hellzerg** [comment]
@alfeinsl the link is invalid, can you send me the proper one?

**Comment by alfeinsl** [comment]
I can access the link. I don't know why you can't access it. I will screenshot the fixes.
![image](https://github.com/hellzerg/optimizer/assets/34530178/bb19feda-d835-42c7-b1ce-dee07b17c598)
