### ISSUE TITLE
Startup Programs Delete option is not displayed.

### ISSUE THREAD

**Issue by danijaus** [hellzerg/optimizer#523]
**Describe the bug**
I used to use this program several months ago, now I have used it again in Windows 11, but wanting to delete some applications that run at system startup, the option is not shown.
**Expected behavior**

**Screenshots**
![Captura de pantalla (6)](https://github.com/user-attachments/assets/cb3b2c55-acb4-4202-8977-01820cd98f0b)

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log
[Optimizer.log](https://github.com/user-attachments/files/16185451/Optimizer.log)

**Desktop (please complete the following information):**
 - Windows 11 Home single Language 64 bit
- .Net Framework 4.8
 - Optimizer version 16.6

**Comment by hellzerg** [comment]
I think it's fixed in v16.7, please confirm.

**Comment by danijaus** [comment]
> I think it's fixed in v16.7, please confirm.

Oh, yes. It is now solved. Thanks for everything.
![Captura de pantalla (6)](https://github.com/user-attachments/assets/65501a58-a89c-480f-b638-3c8cb1aa3b2a)
