### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by Tom3235469** [hellzerg/optimizer#525]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build
- .NET Frameworks installed
 - Optimizer version

**Comment by Tom3235469** [comment]
My games are so buggy
that I can't play on my computer can you guys help me to not lag my games

**Comment by hellzerg** [comment]
We don't support game problems if the problem is not related to the system tweaking.
