### ISSUE TITLE
Trojan in exe

### ISSUE THREAD

**Issue by jagusztinl** [hellzerg/optimizer#526]
**Describe the bug**
Trojan in the latest release 

**Expected behavior**
remove it

**Screenshots**
<img width="265" alt="o" src="https://github.com/user-attachments/assets/7f32951a-7d25-4ee8-a895-13119acefc9f">

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build Win11, HP Wolf and Sureclick
- .NET Frameworks installed
 - Optimizer version 16.6

**Comment by master7720** [comment]
false positive

**Comment by hellzerg** [comment]
There are no malware in the app. Just make sure you download from official repo and check against the SHA256 hash provided.
