### ISSUE TITLE
Ethernet not working after changing DNS

### ISSUE THREAD

**Issue by immortalshortie** [hellzerg/optimizer#527]
I was messing around with the DNS settings on the optimizer and I never had a problem where changing the DNS and flushing it will make my ethernet cable unidentified.
![image](https://github.com/user-attachments/assets/e815c3fa-6b10-4390-afd3-1232caae91e6)

**Comment by hellzerg** [comment]
Try resetting your network adapter in Windows or configure the DNS manually from network properties.
