### ISSUE TITLE
just delete all malware in ur fake optimizer🥱

### ISSUE THREAD

**Issue by wazadev** [hellzerg/optimizer#529]
![Captura de pantalla 2024-08-03 135652](https://github.com/user-attachments/assets/5192cffe-c601-40c4-94e0-7b3f27d591ec)

**Comment by Jisll** [comment]
"wazedev" but has no exerpience in computer science & malware, nice...

this software is open-source.

**Comment by hellzerg** [comment]
There are no malware in the app. It's false positive. Also, I wouldn't trust Avast today, it's too bad.

**Comment by biluqxv** [comment]
usaba avast en 2024 💀💀💀
