### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by randomdudeBoy** [hellzerg/optimizer#530]
**Is your feature request related to a problem? Please describe.**
can you please add a reduce background processes to help gaming, And a internet booster.

**Describe the solution you'd like**
I'm talking about the processes in windows at the tsk manager it slows down my pc and for network boosting like remove bandwidth optimize network and maybe give suggestions on how to improve it because you need to be an expert to do this.

**Describe alternatives you've considered**
for gaming i would do priority mode to focus on games and for network optimizer things like remove power saving and search for best dns and stop background things from using the network 

**Additional context**
advertise the app and get a team to make updates faster

**Comment by hellzerg** [comment]
Almost all of these options exist in the app.
