### ISSUE TITLE
Unusable UWP Apps tab

### ISSUE THREAD

**Issue by Zanzibar-dotcom** [hellzerg/optimizer#531]
**Describe the bug**
In the UWP Apps tab, the list of programs is populated in a way that the words are compressed and overlaid over each other; in short, it's unreadable and thus unusable.  Prior versions of this program did not seem to have this issue.

**Expected behavior**
I expected that there would be a functional list of items from which I could select apps to uninstall or modify.

**Screenshots**
See below

**Logs**
No error was created as a result; this is just the behavior of the program.

**Desktop (please complete the following information):**
 - Windows 11 Home 23H2
- .NET Framework 4.8
 - Optimizer version 16.2
![Cropped image](https://github.com/user-attachments/assets/573a9987-55fa-4172-b3dc-b2fc591a9bee)

**Comment by hellzerg** [comment]
I think it's fixed in v16.7, please confirm.

**Comment by Zanzibar-dotcom** [comment]
Sure enough, it's fixed.  I gotta say, I like your program quite a bit -
thanks for making it!
