### ISSUE TITLE
Re-enable registry backups

### ISSUE THREAD

**Issue by henris42** [hellzerg/optimizer#533]
M$ made a huge mistake by disabling the registry backups.

Please make a switch in the UI so we can enable that easily again.

**Comment by hellzerg** [comment]
There is no such an option that I am aware of.
Can you point to a document or a page talking about this?

**Comment by henris42** [comment]
Its a single registry key. See this: 
https://www.makeuseof.com/windows-11-automatic-registry-backups/

**Comment by hellzerg** [comment]
It's added in v16.7
