### ISSUE TITLE
Problem with Virustotal

### ISSUE THREAD

**Issue by spierrard** [hellzerg/optimizer#535]
Hello,
the last version 16.7 as many detections of malware on Virustotal 13/75 

Rapport by Virustotal
https://www.virustotal.com/gui/file/03a234060541b686ac4265754aff43df9325c21383f90e17f831e67965d717f8

What do you think of that ?

Best regards

**Comment by hellzerg** [comment]
False positives. You can mark it as safe so the situation can be improved.
