### ISSUE TITLE
Doesn't open on Windows 10 version 1909

### ISSUE THREAD

**Issue by RZMiRaN** [hellzerg/optimizer#54]
So I'm keeping my PC on version 1909 because it has the fastest bootup speed, When I open your file on my PC, it opens for less than a second and closes immediately, while I tried it on my work laptop which is running Windows 10 version 20H2, it worked perfectly fine.

The reason why I'm sure it is the windows version: I updated my PC to version 20H2 just to try if your tool would actually open, and it did! but since the 20H2 version is way too slow, I'm not willing to keep it so I downgraded back to version 1909.

**Comment by hellzerg** [comment]
Can you send the log file located in C:\ProgramData\Optimizer ?

**Comment by RZMiRaN** [comment]
[Optimizer.log](https://github.com/hellzerg/optimizer/files/6802502/Optimizer.log)

**Comment by hellzerg** [comment]
I just tried in on a 1909 VM and it works fine.
Try deleting the entire C:\ProgramData\Optimizer folder and try launching again.

**Comment by RZMiRaN** [comment]
Everything works fine now, thank you for your time and sorry about the late response.

**Comment by hellzerg** [comment]
It might have been a corrupt JSON settings file.

**Comment by RZMiRaN** [comment]
Could be, thank you, I appreciate your hard work.
