### ISSUE TITLE
We've blocked Optimizer-16.7.exe because it was infected with Win32: Miscx-genX- gen

### ISSUE THREAD

**Issue by nicathasanli** [hellzerg/optimizer#542]
Hi everyone, today I tried to download .exe file from latest release, but immediately my antivirus popped up window:
![Screenshot 2024-09-02 181052](https://github.com/user-attachments/assets/91866942-cee1-48e8-a6a1-9098b5784605)

I tried to download source code.zip folder got the same error again. Please suggest me

**Comment by xhabdo** [comment]
so its not safe to use? 
ive seen so many poeple installing it

**Comment by master7720** [comment]
A lot of antivirus software, especially the not-so-great ones like Avast and McAfee, tend to throw false positives. This software is completely open source, so if you're curious, you can check out the code yourself.

**Comment by master7720** [comment]
> A lot of antivirus software, especially the not-so-great ones like Avast and McAfee, tend to throw false positives. This software is completely open source, so if you're curious, you can check out the code yourself. If you can report it as a false positive.

**Comment by master7720** [comment]
> Hi everyone, today I tried to download .exe file from latest release, but immediately my antivirus popped up window: ![Screenshot 2024-09-02 181052](https://private-user-images.githubusercontent.com/58861181/363717987-91866942-cee1-48e8-a6a1-9098b5784605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQ2MzIsIm5iZiI6MTcyNTMzNDMzMiwicGF0aCI6Ii81ODg2MTE4MS8zNjM3MTc5ODctOTE4NjY5NDItY2VlMS00OGU4LWE2YTEtOTA5OGI1Nzg0NjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMzIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTU5ZDA2YmI0YWFkMjYxOWM2ODRjOGVhNDNiZGNkZDMyY2UyM2NjNDNmZmVmNzNiZTM4Mzg4Y2QzZDIxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H05KiJp905_c9uSv0ZMMlsq6rkxfwp17M0UiGYFvTT0)
> 
> I tried to download source code.zip folder got the same error again. Please suggest me

I checked out your profile and noticed you're a C++ developer. That's awesome because the entire project is in C++, with a bit of batch scripting too. If you’re skeptical, feel free to take a look at the source code. Also, just a heads up for the future since you clearly know your way around coding, it’s better to dive into the source code instead of just relying on free antivirus software to label your apps as viruses. It’ll definitely help you come off as a dummy. Thanks you, and have a great day!

**Comment by master7720** [comment]
> > Hi everyone, today I tried to download .exe file from latest release, but immediately my antivirus popped up window: ![Screenshot 2024-09-02 181052](https://private-user-images.githubusercontent.com/58861181/363717987-91866942-cee1-48e8-a6a1-9098b5784605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQ2MzIsIm5iZiI6MTcyNTMzNDMzMiwicGF0aCI6Ii81ODg2MTE4MS8zNjM3MTc5ODctOTE4NjY5NDItY2VlMS00OGU4LWE2YTEtOTA5OGI1Nzg0NjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMzIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTU5ZDA2YmI0YWFkMjYxOWM2ODRjOGVhNDNiZGNkZDMyY2UyM2NjNDNmZmVmNzNiZTM4Mzg4Y2QzZDIxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H05KiJp905_c9uSv0ZMMlsq6rkxfwp17M0UiGYFvTT0)
> > I tried to download source code.zip folder got the same error again. Please suggest me
> 
> I checked out your profile and noticed you're a C++ developer. That's awesome because the entire project is in C++, with a bit of batch scripting too. If you’re skeptical, feel free to take a look at the source code. Also, just a heads up for the future since you clearly know your way around coding, it’s better to dive into the source code instead of just relying on free antivirus software to label your apps as viruses. It’ll definitely help you come off less as a dummy. Thanks you, and have a great day!

**Comment by hellzerg** [comment]
The app is safe. They're all false positives unfortunately.

**Comment by hellzerg** [comment]
Please mark it as safe in your antivirus provider to avoid similar issues in the future.
