### ISSUE TITLE
Flagged as a "Suspicious Object" in ESET Security software

### ISSUE THREAD

**Issue by sweckform2** [hellzerg/optimizer#543]
**Describe the bug**
All versions of ESET security software flag Optimizer as a "Suspicious Object"

**Expected behavior**
On system that have ESET Security installed, the Optimizer file is quarantined automatically and all downloads and attempts to access it are restricted. While workaround exist, these are too cumbersome and time-demanding for the average user and because of this bug, you lose a lot of potential customers.

**Screenshots**

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log

**Desktop (please complete the following information):**
 - Windows version and build - 23H2 as of 03.09.2024
- .NET Frameworks installed - all versions are installed
 - Optimizer version - 16.4 onwards

**Comment by master7720** [comment]
some antivirus software tend to throw false positives. This software is completely open source, so if you're curious, you can check out the code yourself. If you can please report it as a false positive.

**Comment by hellzerg** [comment]
We cannot do anything for false positives as the antivirus providers have become more strict lately. 

The app is safe though. Please mark it as safe to avoid similar issues in the future.
