### ISSUE TITLE
Power & Battery + Sleep feature completely gone

### ISSUE THREAD

**Issue by mikecuongg** [hellzerg/optimizer#555]
**Describe the bug**
The power & battery on settings are inaccessible (crashed) and Sleep can't be found under Power Plan on the Control Panel (it's completely gone while there's no config related to Sleep mode)

**Expected behavior**
Sleep should work as normal, now I can't use Sleep

**Screenshots**
![image](https://github.com/user-attachments/assets/bf3f1c4d-2b07-49e3-a86b-49cf198fc001)
![image](https://github.com/user-attachments/assets/fde110af-f77e-453d-9065-ec7accfe882a)
This is my configuration on Optimizer - i did tried disable Hibernation b4 don't know if that's gonna help

**Logs**
Please, upload the required log file located in C:\ProgramData\Optimizer\optimizer.log
[Optimizer.log](https://github.com/user-attachments/files/17130810/Optimizer.log)

**Desktop (please complete the following information):**
 - Windows version and build:  Windows 11 23H2 Build 22631.4169
- .NET Frameworks installed: Yes
 - Optimizer version: 16.7 (latest)
 
 There are 2 issues currently open regarding this issue, one is in Chinese and the other is abandoned.
I've tried SFC scan and DISM but nothing seems too work.

**Comment by mikecuongg** [comment]
I provide most information I can in the form, if there's more needed I sure can offer more. Can someone reach out to me for this?

**Comment by hellzerg** [comment]
Reset Disable Modern standby in Windows 11 tab

**Comment by mikecuongg** [comment]
> Reset Disable Modern standby in Windows 11 tab

Thanks for the quick responses. I do not expect to receive it this early. 
It works. any chance you could get this to the FAQ page or something?
anyway I'll close the issue for now
