### ISSUE TITLE
How to execute silently ? 

### ISSUE THREAD

**Issue by neilime** [hellzerg/optimizer#6]
Hi,

Optimizer is a very usefull sofware that I want to use in a script I have created for configuring my windows 10 computer.

Is it possible to call optimizer via cmd or powershell without showing the GUI (silently) by passing settings / config as an argument ?

It would be great

Thank you

**Comment by hellzerg** [comment]
Hi,

You mean the options in Universal & Windows tabs?

**Comment by neilime** [comment]
No, for instance in a batch file

```batch
echo Execute optimizer with providen config...
echo.

C:\Optimizer-4.8.exe /S -config C:\tmp\optimizer.config 

echo Done
echo.

```

**Comment by hellzerg** [comment]
Okay, I'll start doing it, wait for it in the next few days.

**Comment by hellzerg** [comment]
Hi, do you want to try the build before releasing it?

**Comment by neilime** [comment]
Yes please, It would be great.

**Comment by hellzerg** [comment]
Just edit the right conf file, using true/false and pass it like this:
optimizer.exe /windows7.conf

[optimizer-test.zip](https://github.com/hellzerg/optimizer/files/3763386/optimizer-test.zip)

**Comment by neilime** [comment]
I've made a first attempt with default config "all to false":

Config : 
Windows 10
Dark Theme Enabled

`optimizer.exe /windows10.conf`

It has installed OneDrive, and disabled DarkTheme.

I was expected that nothing happend with config "all to false", Am I wrong ?

**Comment by hellzerg** [comment]
Well, yes, FALSE means it defaults the setting, TRUE applies the tweak.
Do you want an additional third option, like ignore?

**Comment by neilime** [comment]
Yes why not

**Comment by hellzerg** [comment]
Sorry for the delay, new version is out!
Use null for ignoring options.

**Comment by neilime** [comment]
OK thanks.
