### ISSUE TITLE
Working on Italian translation

### ISSUE THREAD

**Issue by Ziocash** [hellzerg/optimizer#60]
I'm currently working on Italian translation

**Comment by hellzerg** [comment]
Nice!

**Comment by Ziocash** [comment]
### Italian translation
I've done it.
I suggest to use this issue for further improvements.

I hope to have done it the more correct as possible.
Let me know if there are any issues with text or formats.

[IT.json.txt](https://github.com/hellzerg/optimizer/files/7539047/IT.json.txt)

**Comment by hellzerg** [comment]
Nice job, everything is correct. But there's a little more to translate, because of the new version. It's just 18 new small lines, don't worry

[new-tags.txt](https://github.com/hellzerg/optimizer/files/7545328/new-tags.txt)
y.

**Comment by Ziocash** [comment]
No problem, done 

[new-tags.txt](https://github.com/hellzerg/optimizer/files/7546648/new-tags.txt)

**Comment by hellzerg** [comment]
Nice! Italian translation is ready from v10.6!
