### ISSUE TITLE
deleted folders without permission and i can not recover them

### ISSUE THREAD

**Issue by LucianPopaLVP** [hellzerg/optimizer#63]
used the cleanup function of this app and deleted all my files from desktop and can not find them anywhere....even tried disk drill!!

wth????

**Comment by hellzerg** [comment]
How is that possible? Cleaner deletes temporary folder in AppData.

**Comment by LucianPopaLVP** [comment]
> How is that possible? Cleaner deletes temporary folder in AppData.

I don't know, but as soon I used this they disappeared. Tried lots of tools like disk drill and other and can't find my files anywhere in my computer and I had a few important files I was working. Any idea what functions broke my computer and how can i reverse it?

**Comment by hellzerg** [comment]
Which options have you checked?
Did you have any documents saved in AppData\Local\Temp ?

**Comment by LucianPopaLVP** [comment]
> Which options have you checked? Did you have any working documents saved in AppData\Local\Temp ?

For clean up i checked all the options...only have one document opened, which would be in temp file. Even though, disk drill would find those files in a deep scan but can not find anywhere. If they are deleted and recoverable and they are not anywhere in my PC where are they? And why just the ones on desktop? All the other files in my user folder are all there intact.

**Comment by LucianPopaLVP** [comment]
> Well, my code determines the user Temp folder using this function: Path.GetTempPath().
> 
> The only possible way this function could return your Desktop folder is custom environment variables. Which means TEMP variable is modified to point to %USERPROFILE%\Desktop.
> 
> Could you run the aforementioned function and return the result ?

doesn't return anything. So, if it deleting files is there anyway to get them back or my file are gone gone?

**Comment by hellzerg** [comment]
Unfortunately, yes.
But it should return something. Create an console app in Visual Studio and do the following:

![Capture](https://user-images.githubusercontent.com/3146835/135238654-d12a5551-e7db-4b04-a867-7dfab6c0d9b3.PNG)

**Comment by LucianPopaLVP** [comment]
> %USERPROFILE%\Desktop.

it returns my user folder where i have all my files saved but not the ones i had on desktop.

**Comment by LucianPopaLVP** [comment]
> Unfortunately, yes. But it should return something. Create an console app in Visual Studio and do the following:
> 
> ![Capture](https://user-images.githubusercontent.com/3146835/135238654-d12a5551-e7db-4b04-a867-7dfab6c0d9b3.PNG)

used this:

using System;

static void Main(string[] args)
{
    Console.WriteLine(System.IO.Path.GetTempPath());
    Console.ReadLine();
}

the console returns:
'ConsoleApp3.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.10\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

'ConsoleApp3.exe' (CoreCLR: clrhost): Loaded 'C:\Users\lucya\source\repos\ConsoleApp3\bin\Debug\net5.0\ConsoleApp3.dll'. Symbols loaded.

'ConsoleApp3.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.10\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

The program '[12228] ConsoleApp3.exe' has exited with code 0 (0x0).

is this what you are interested in?

**Comment by hellzerg** [comment]
If you use Run Dialog and enter %TEMP%, where does it go?

**Comment by LucianPopaLVP** [comment]
> %TEMP%

goes to C:\\Users\lucyan\AppData\Local\Temp

**Comment by hellzerg** [comment]
I don't know how your Desktop files have been deleted. That should not happen.

**Comment by LucianPopaLVP** [comment]
> I don't know how your Desktop files have been deleted. That should not happen.

I am always cleaning my temp files through Windows, really don't understand why they got deleted just by using a clean up function of a program...and since they got deleted through this no tools can see them anymore....tried Disk Drill, Test Disk, EaseUS and no succes!
So I guess the program is set to delete files forever.

**Comment by hellzerg** [comment]
Yes, unfortunately. If your system disk is an SSD, recovery tools don't work anyway.

**Comment by hellzerg** [comment]
Desktop shortcuts got deleted too?

**Comment by LucianPopaLVP** [comment]
> Desktop shortcuts got deleted too?

Yes, i have a NVME drive . A few desktop shortcuts left, which is really wierd. Don't understand since everything is installed on this drive only and the same program files directory.

**Comment by hellzerg** [comment]
If you repeat the action, what would happen?

**Comment by LucianPopaLVP** [comment]
> If you repeat the action, what would happen?

not going to run it again since we don't know what happen and don't want to affect drive data anymore maybe I will be lucky to recover some of the lost ones. Any idea how to work around this since you wrote the whole code?

**Comment by hellzerg** [comment]
It's unexplained, really. I hope your files weren't so important and be lucky to recover them.
