### ISSUE TITLE
[BUG] Classic Right Click Menu not working in v10.5

### ISSUE THREAD

**Issue by HypedDomi** [hellzerg/optimizer#68]
I'm currently using Windows 11 v21H2 with Optimizer v10.5
On my Laptop with the same Windows Version and Optimizer v10.4, classic right click Menu is working well. When I downgrade to v10.4 Classic Shell is working. 

![image](https://user-images.githubusercontent.com/50876016/141803872-fc8cd88d-d40a-47ad-9752-d04b32c465bc.png)

**Comment by hellzerg** [comment]
Using latest Windows 11 build, fully updated?

**Comment by HypedDomi** [comment]
Yeah. But figured out that its not a Problem with Optimizer. One Program that i have trys to "repair" the Rightclick menu on startup and removes the classic one.

**Comment by hellzerg** [comment]
So, it's working properly?

**Comment by HypedDomi** [comment]
yeah. sry for disturbing you

**Comment by hellzerg** [comment]
It's fine!
