### ISSUE TITLE
Feature request: apply *without* restart

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hellzerg/optimizer#7]
It would be nice to be able to enable tweaks but then restart _later_.

**Comment by hellzerg** [comment]
Apply & Restart button does not apply anything, it's just a quick way to restart system.
I should change the button text in the next version.

**Comment by LinuxOnTheDesktop** [comment]
> I should change the button text in the next version.

I fear that you did not do so!

**Comment by hellzerg** [comment]
Tweaks are already applied without restart.

**Comment by LinuxOnTheDesktop** [comment]
I am sorry, but you miss the point. The point is: whilst you said that you would change _the button text_, you have not done so.

**Comment by hellzerg** [comment]
Okay. I will change it in next version. But keep in mind that some options DO need restarting to take effect.
