### ISSUE TITLE
Any config files with recommended settings for this program?

### ISSUE THREAD

**Issue by blesphy1** [hellzerg/optimizer#70]
Im a big newbie and im not entirely sure which of the many options i want to enable/disable with optimizer.

is there some sort of recommended settings list for windows 10 that i can use? 

Thanks in advance for any help

**Comment by hellzerg** [comment]
Start with these options:

Universal:

Enable Performance Tweals
Disable Network Throttling
Disable Error Reporting
Disable Telemetry Tasks
Disable Media Player Sharing
Disable HomeGroup

**Comment by rezorustavi** [comment]
Hello! Please add the function of defining the settings that were made before starting the optimizer
Здравствуйте! Добавьте пожалуйста функию определения настроек, которые были сделаны до запуска оптимизера

**Comment by blesphy1** [comment]
thanks!
