### ISSUE TITLE
Defining pre-launch settings

### ISSUE THREAD

**Issue by rezorustavi** [hellzerg/optimizer#72]
Hello! Please add the function of defining the settings that were made before starting the optimizer
Здравствуйте! Добавьте пожалуйста функию определения настроек, которые были сделаны до запуска оптимизера

**Comment by hellzerg** [comment]
What do you mean? Can you be more specific please?

**Comment by lifeowner** [comment]
Please read this:
https://github.com/hellzerg/optimizer/blob/master/CONFS.md
It could be useful in your case. If you need any further help do not hesitate to write ahead here.
