### ISSUE TITLE
"Open Command Promt here" forcibly added to my Context Menu after use v10.7 (and maybe older)

### ISSUE THREAD

**Issue by MrCatEsq** [hellzerg/optimizer#73]
After I applied changes made by program and restarted my Win 8.1 x64, I see "Open Command Promt here" element in the Context Menu (right click to open) of my system. 

There is no option to disable it, there is no record for this in the Integrator tab of optimizer v10.7.

I didn't enable Performance Tweaks.
I didn't change anything in Integrator tab.

**Comment by RonnySay** [comment]
I also found the "open command prompt here" element after applying changes. To remove it, open regedit and go to Computer\HKEY_CLASSES_ROOT\Directory\Background\Shellex. You'll some some CMD folder there, simply delete it. If it's not there, go further into "ContextMenuHandlers". I'm not sure where it is coz I already deleted mine some days ago.

**Comment by hellzerg** [comment]
Performance tweaks adds this to menu for simplicity.

**Comment by hellzerg** [comment]
Add/Delete 'Open with CMD' option has been transfered to Integrator/Ready-made menus from v10.8.
