### ISSUE TITLE
Can't reenable windows update 

### ISSUE THREAD

**Issue by bluthewolf** [hellzerg/optimizer#74]
Hello! I've been trying this app for a few days and it has been working pretty well for me as i have noticed many improvements with the performance on my PC for Windows 11.  However, there was an update that I found important for me to update to, and I tried to turn off the "Disable Automatic Updates" "Disable Feature Updates" and "Disable Insider Service" (as I am on an insider build to run Windows 11), and even when those are off, the app has no effect on fixing these things, as Windows update keeps failing and says retry. 

Many of the toggles I turn on, like Enable Taskbar Color, I notice if I turn it off, it doesn't apply any effect, and I would have to go to my settings to manually turn it off, So I assume this is the same for everything else. Is there a way I can fix the Windows Update issue?

**Comment by hellzerg** [comment]
Please, send me the optimizer.log file in C:\ProgramData\Optimizer or by copying the log from the app's Options > View errors.

**Comment by hellzerg** [comment]
Try to import the REG file I've attached you. If you don't know, you should rename it to ".reg" and then double-click it.
After that, restart your device and try to update.

[Restore_Windows_Update.reg.txt](https://github.com/hellzerg/optimizer/files/7650376/Restore_Windows_Update.reg.txt)

**Comment by bluthewolf** [comment]
While it allowed it to go further than just showing the retry, I get a new error. I don't know if this is out of the Optimizer's reach or if something happened, as I was able to update to Win 11 updates before, but had to disable the TPM check in order to update. Although I am not sure if the Optimizer has turned it off or some other setting in Windows.

![Screenshot 2021-12-03 103641](https://user-images.githubusercontent.com/95483345/144629870-6cfd34b1-0161-4f9d-8d5f-462a308841b1.png)

**Comment by hellzerg** [comment]
Try disabling TPM checks using the app.

**Comment by bluthewolf** [comment]
I tried turning it on through the app but when I restarted I saw the check was off

**Comment by hellzerg** [comment]
So, something's new on Microsoft's end. This is a insider build after all.
