### ISSUE TITLE
Feature request - support for more disabled useless services

### ISSUE THREAD

**Issue by Felipefpl** [hellzerg/optimizer#75]
customized builds of win10 found on the internet has 50 processes, maybe less being used by the OS, it would be REALLY nice if optimizer came with support to disable EVERY useless services including Windows Defender Antivirus/SearchApp.exe to have more RAM/CPU available.

**Comment by hellzerg** [comment]
In order to disable Windows Defender you need to restart into safe-mode. It's not that easy anymore. Optimizer can do it.

Do you have any useless services list in mind?

**Comment by Felipefpl** [comment]
I already disabled defender thanks to another program.

Regarding the useless services i never found a site with the name of all services that can be disabled. But there are some out there. Aside defender the searchapp.exe is the most annoying pest of win10 i can think of.

**Comment by hellzerg** [comment]
SearchApp.exe is not a problem because Cortana and Web search can be disabled properly with Optimizer, greatly reducing its footprint. If you completely kill the process, start menu will not even work.

**Comment by Felipefpl** [comment]
Strange, i decided to make a search about searchapp.exe and didnt see any mention of this here for example:

https://answers.microsoft.com/en-us/windows/forum/all/how-do-you-disable-searchappexe-from-running-so/c4cb54ae-0763-4160-90fc-4913620b276b

**Comment by hellzerg** [comment]
I'm trying to find a way to disable Defender without restarting in safe-mode. I hope it will work. it will be so good.

**Comment by Felipefpl** [comment]
That would be GREAT! I hope you're lucky. 👍

**Comment by Felipefpl** [comment]
> Do you have any useless services list in mind?

here are good lists: https://windowsreport.com/disable-windows-services/#:~:text=You%20can%20safely%20disable%20all%2048%20Windows%2010,would%20be%20inadvisable%20to%20stop%20the%20Xbox-related%20services.

https://www.wilderssecurity.com/threads/windows-10-which-services-disable.378804/

**Comment by Felipefpl** [comment]
This was closed because the services will be added to optimizer?

**Comment by hellzerg** [comment]
I will think about adding some of them.
