### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by btwise** [hellzerg/optimizer#77]
Very good frame, I hope to finish an excellent work together!

For Windows 10/ 11, disabling the `sysmain` service should be recommended by many

Turning off disk defragmentation is also a good optimization for solid-state drive users

The network sharing function of Windows system has always been a nightmare for ordinary users. A series of operations such as adjusting user permissions, adjusting sharing options and adjusting security policies are expected to be realized as a simple option

Also want to add a driver operation module
    
For printer didn't install driver model, how to get the printer model through hardware ID key word, and then match the web model, and then automatically download and install, in our country, have a special offer almost all of the printer driver, the driver be repackaged, use dpinstall installation, it will convenient to many users(https://www.drvsky.com/)

**Comment by hellzerg** [comment]
What do you mean?
