### ISSUE TITLE
Conf files problem

### ISSUE THREAD

**Issue by franciscodimattia** [hellzerg/optimizer#8]
When using conf files in Windows 10, there are some options that cannot be used or they break execution.
Some of them are:
"DisableMediaPlayerSharing"
"BlockSkypeAds"
"DisableAutomaticUpdates"
"ExcludeDrivers"

EDIT: I am using Optimizer 4.9 and Windows 10.0.18363

**Comment by hellzerg** [comment]
I have just tried the options you mentioned and they are working properly. Are you sure your .conf file is valid?
