### ISSUE TITLE
add  customizability for shells and  add micro.exe  to the list 

### ISSUE THREAD

**Issue by XxnittanixX** [hellzerg/optimizer#81]
also add alacritty  add som phot editor applications  and  video edditng applications  make this the unofficial store  and  tweaker i garentee it will be big

**Comment by XxnittanixX** [comment]
also add  a way to change showmenu 400 to 50  in registry

**Comment by XxnittanixX** [comment]
Computer\HKEY_CURRENT_USER\Control Panel\Desktop

**Comment by hellzerg** [comment]
What's micro.exe?

What's showmenu 400 to 50 in Registry?

**Comment by XxnittanixX** [comment]
micro .exe is a binary for  text editing on  windows terminal its quick and extensive written in go lang   you can find it here 
https://github.com/zyedidia/micro its open source  and still in development also u should warn people with the log4 java thing 

Computer\HKEY_CURRENT_USER\Control Panel\Desktop\menushowdelay  look at that change from 400 to 25 for windows 11 and 10

**Comment by hellzerg** [comment]
Micro app is in portable format I see. It's better to add only installers in app feed.

What's wrong about menushowdelay being 25 in Windows 10/11?

**Comment by XxnittanixX** [comment]
> Micro app is in portable format I see. It's better to add only installers in app feed.
> 
> What's wrong about menushowdelay being 25 in Windows 10/11?

well alot actually  it was too slow for me  so i figured  maybe everyone would like a faster  window  show  shortcut  so i set mine to 1  and  it instantly is loaded

**Comment by hellzerg** [comment]
MenuShowDelay is set to 8, instead of 1.
