### ISSUE TITLE
"Adblocker" host file brick your Windows

### ISSUE THREAD

**Issue by BelovedTomboyishGirl** [hellzerg/optimizer#82]
Hello,

I wanna report a problem when i was using the option for adding basic adblock to your host file in the program,
After reboot it totally brick your PC and you can't open almost all programs, DNS Client CPU Usage became very high, and you have to go in Safemode for reset the host file to default configuration.

**Comment by hellzerg** [comment]
Yes. DNS Client is detecting the modifications in hosts file and rebuilds its cache. You have to wait to finish, before accessing the internet. That's how DNS Client service works by design.
