### ISSUE TITLE
Help me please (more on ss)

### ISSUE THREAD

**Issue by 2lay** [hellzerg/optimizer#83]
Hey i was using this optimizer and what is the name of the tweak that will let me enable this once again?
![image](https://user-images.githubusercontent.com/82117939/146653457-33844d13-bde6-490b-9a46-9a7f85036eb1.png)

**Comment by hellzerg** [comment]
![image](https://user-images.githubusercontent.com/3146835/146667489-7ed3907b-d110-4fa8-8bff-b2076c7dbcc3.png)
