### ISSUE TITLE
winrar, 7zip drag and drop doesn't work after tweaking

### ISSUE THREAD

**Issue by SkyyMC** [hellzerg/optimizer#84]
hey i have tweaked my pc and winrar and 7zip doesn't seem to work with drag an drop it says "Drag and drop function failed"
![image](https://user-images.githubusercontent.com/43611579/146689417-8d753ffd-a42f-4dc3-a50c-8155765381ca.png)

**Comment by hellzerg** [comment]
Maybe your 7zip/WinRAR or explorer.exe runs with admin rights?
