### ISSUE TITLE
UI infelicity: which graphic signifies that a tweak is enabled

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [hellzerg/optimizer#85]
Thank you for your software. I have version 10.9.

I take it that what one sees in the following screenshot signifies that the 'Disable Media Player Sharing' tweak is _on_, i.e. that Media Player sharing is disabled. But am I correct? It should be easier to tell. The reddish-colour somewhat suggests that the tweak is _off_, and there is no tooltip or anything else to make plain whether the tweak is in force (or will be, after a reboot) or not.

![image](https://user-images.githubusercontent.com/47056543/149179020-fecb5c60-8d12-4158-b6db-f8b58990925e.png)

**Comment by hellzerg** [comment]
Yes. Color suggests that Media Player Sharing is Disabled (OFF).
There are explanatory tooltips when you hover over each toggle. They should work. No?
