### ISSUE TITLE
WIndows 10 - This app can't run on your PC.

### ISSUE THREAD

**Issue by tekstacey** [hellzerg/optimizer#86]
Optimizer-11.1.exe

Windows 10
10.0.19044 Build 19044

This app can't run on your PC.
To find a version for your PC, check with the software publisher.

**Comment by hellzerg** [comment]
Have you tried previous versions?

**Comment by SniperWasTaken** [comment]
Antivirus Issue?

**Comment by hellzerg** [comment]
> Antivirus Issue?

Seems like this is the case.
