### ISSUE TITLE
How do I run it ?????

### ISSUE THREAD

**Issue by SAAD2020AI** [hellzerg/optimizer#9]

**Comment by SAAD2020AI** [comment]
Plzzz help !!!!!

**Comment by hellzerg** [comment]
What do you mean?

**Comment by SAAD2020AI** [comment]
Sorry to disturb you , actually the first time I downloaded the file , it showed me that it cannot find the file specified , so I re-downloaded it and this time it worked. And thank you for looking into the matter !!
