### ISSUE TITLE
Crashes on Windows 7 x32

### ISSUE THREAD

**Issue by XICIZATO** [hellzerg/optimizer#90]
The latest version 1.4 crashes on Windows 7 x32
The previous 1.3 is working successfully

**Comment by hellzerg** [comment]
Can you find the craah log in Event Viewer?

**Comment by XICIZATO** [comment]
https://pastebin.com/h3B8vY35

**Comment by hellzerg** [comment]
[Optimizer-test.zip](https://github.com/hellzerg/optimizer/files/7970023/Optimizer-test.zip)

Unzip this build and test it.

**Comment by XICIZATO** [comment]
http://s01.geekpic.net/di-N3EHK4.png
There is a launch!
1.4 crashed at launch.

**Comment by hellzerg** [comment]
Okay. So test build works. Wait for the fix.

**Comment by hellzerg** [comment]
[Optimizer-test2.zip](https://github.com/hellzerg/optimizer/files/7970376/Optimizer-test2.zip)

Try this. And send me the Optimizer.log file after running.

**Comment by XICIZATO** [comment]
after running
https://dropmefiles.com/ibs8f

**Comment by hellzerg** [comment]
[Optimizer-test3.zip](https://github.com/hellzerg/optimizer/files/7971812/Optimizer-test3.zip)

Again. Send me the log after running.

**Comment by XICIZATO** [comment]
404

**Comment by hellzerg** [comment]
[Optimizer-test3.zip](https://github.com/hellzerg/optimizer/files/7972430/Optimizer-test3.zip)

**Comment by XICIZATO** [comment]
[Optimizer-test3.log.zip](https://github.com/hellzerg/optimizer/files/7972491/Optimizer-test3.log.zip)

**Comment by hellzerg** [comment]
Okay. Should be fixed now. Update to v11.5.
