### ISSUE TITLE
I can't open optimizer 11.6

### ISSUE THREAD

**Issue by ismatt3w** [hellzerg/optimizer#95]
I can't open the 11.6 optimizer, I can only open the 11.3 version, why is this happening? 
![image](https://user-images.githubusercontent.com/99362698/153282666-6d343235-e8d0-4da2-b124-59f41dc748cf.png)
![image](https://user-images.githubusercontent.com/99362698/153282737-d3be2e81-889c-4f2a-babe-15b75ef50eec.png)

**Comment by hellzerg** [comment]
Send me the optimizer.log file located in C:\ProgramData\Optimizer.

**Comment by ismatt3w** [comment]
This?

**Comment by ismatt3w** [comment]
I send file in the gmail

**Comment by ismatt3w** [comment]
I just reinstalled optimizer 11.3 and deleted the optimizer folder from program data, and now there is the optimizer.log file and I also downloaded 11.6 but it doesn't let me open it anymore :(
![image](https://user-images.githubusercontent.com/99362698/153308542-ac1717f8-8f60-4c48-98c2-d28e3fc30798.png)
[Optimizer.log](https://github.com/hellzerg/optimizer/files/8036843/Optimizer.log)

**Comment by hellzerg** [comment]
Can you run Optimizer 11.6 from CMD, like this: "Optimizer.exe /disable=indicium" ?

**Comment by ismatt3w** [comment]
> Can you run Optimizer 11.6 from CMD, like this: "Optimizer.exe /disable=indicium" ?

Ok, i gonna try

**Comment by ismatt3w** [comment]
> Can you run Optimizer 11.6 from CMD, like this: "Optimizer.exe /disable=indicium" ?

![image](https://user-images.githubusercontent.com/99362698/153455891-c109f14e-fbec-4221-9050-06af7d9add38.png)
is not open :/

**Comment by ismatt3w** [comment]
> Can you run Optimizer 11.6 from CMD, like this: "Optimizer.exe /disable=indicium" ?

the only thing that comes out at the end is, Loading your hardware specifications

**Comment by hellzerg** [comment]
If you do "Optimizer.exe /reset" with v11.6.
What is happening?

**Comment by ismatt3w** [comment]
> If you do "Optimizer.exe /reset" with v11.6, what is happening?

![image](https://user-images.githubusercontent.com/99362698/153460073-1de71669-b417-4d8b-bdba-880ce049cda8.png)
Now it didn't open with the command xD?

**Comment by ismatt3w** [comment]
> If you do "Optimizer.exe /reset" with v11.6, what is happening?

try again to open the optimizer from cmd and now the language panel is opened, let me check if it can or not

**Comment by ismatt3w** [comment]
> If you do "Optimizer.exe /reset" with v11.6, what is happening?

nah, nothing happened, it just closes when it gets to the loading hardware specs

**Comment by ismatt3w** [comment]
> If you do "Optimizer.exe /reset" with v11.6, what is happening?

Gg

**Comment by hellzerg** [comment]
[Optimizer-test.zip](https://github.com/hellzerg/optimizer/files/8042955/Optimizer-test.zip)

Try this build.

**Comment by hellzerg** [comment]
Come here https://discord.gg/MFDxMjr2 and let's solve the problem.

**Comment by hellzerg** [comment]
Problem solved successfully, please update to v11.7.
